### ISSUE TITLE
Register an existing standby node

### ISSUE THREAD

**Issue by DimCitus** [citusdata/pg_auto_failover#101]
At the moment our command `pg_autoctl create postgres` knows how to register a pre-existing PostgreSQL instance when it's a primary server. This allows users to provision as usual and only then register to the monitor.

There are two main cases when registering an existing standby:

  1. we only have a pre-existing PGDATA directory with a base backup copy ready for recovery and connection
  2. the standby is already running and in recovery

In the first case we should check that the `system_identifier` is the same as in the primary server and then continue with the standby initialisation as usual, only skipping the `pg_basebackup` step.

In the second case, we should still check that the `system_identifier` is the same as in the primary server, and then verify that the setup is done according to pg_auto_failover expectations:

  1. list all the setup that we do when creating a standby (replication slot, primary_conninfo, password, HBA, PostgreSQL configuration, pg_stat_wal_receiver, etc)
  2. either implement a way to check that everything is in place in a way that allows us to implement a failover, or override the existing settings with the pg_auto_failover settings for a standby and restart the standby
  3. register the standby to the monitor either as WAIT_STANDBY (if the primary is not ready yet, which is visible from the standby by the lack of an entry in pg_stat_wal_receiver) or in CATCHINGUP state

This is a brain dump, the actual implementation might differ to a large extend with the thinking here, though I think this is the general idea we should pursue here.

**Comment by MichaelDBA** [comment]
To me, this is a showstopper.  We simply cannot use pg_basebackup to create a standby since our size is about 30TB.  It would take pg_basebackup forever practically speaking!  The only tool that I know of that can restore VLDBs is pgbackrest.  Will consider this tool only when that practicality is available.  I don't know why this "enhancement" is not prioritized.

**Comment by DimCitus** [comment]
Hi @MichaelDBA ; thanks for your feedback and interest in pg_auto_failover. This item has been prioritised to our next release, 1.4. We are currently finishing the packages for release 1.3. So be sure to try again soon!

**Comment by MichaelDBA** [comment]
Thanks for the update.  Will check back in 1.4.  Will also peruse the code to see if I feel capable.

**Comment by MichaelDBA** [comment]
Guess I can't close this issue, so feel free to do so.

**Comment by DimCitus** [comment]
> Guess I can't close this issue, so feel free to do so.

The idea would be to close it when we have merged a PR that fixes it, that's our process. Also you might notice that the issue has been flagged for Milestone 1.4 (see also https://github.com/citusdata/pg_auto_failover/milestone/8).

**Comment by MichaelDBA** [comment]
oh coolio!!!!

**Comment by JelteF** [comment]
Closing this, since #276 has been merged.

**Comment by MichaelDBA** [comment]
yippie, one major drawback is now gone! Keep up the good work.

**Comment by JelteF** [comment]
Packages for 1.4.0 have just been published. (1.4.0 is the first version with this change).
