### ISSUE TITLE
can not destroy a data node when monitor is not available

### ISSUE THREAD

**Issue by mtuncer** [citusdata/pg_auto_failover#119]
Issued `pg_autoctl do destroy --pgdata primary` on a data node that expects a monitor on the same node.

Command did not terminate even after waiting for 5 minutes. Log message from pg_autoctl is below

```
13:41:41 INFO  Managing PostgreSQL installation at "primary"
13:41:41 INFO  Removing local node from the pg_auto_failover monitor.
13:41:41 WARN  Failed to connect to "postgres://autoctl_node@localhost:6000/pg_auto_failover", retrying until the server is ready
```

**Comment by DimCitus** [comment]
Fixed in https://github.com/citusdata/pg_auto_failover/commit/bd5d9f92c125561af8c0a542e79c897ce900d959, release in 1.2.
