### ISSUE TITLE
Design decisions regarding to fault-tolerance

### ISSUE THREAD

**Issue by maksm90** [citusdata/pg_auto_failover#12]
Hello everyone!
Thanks for the interesting extension and adjacent tool (`pg_autoctl` utility).

I would like to know how cluster deals with different faults. Especially:

- What happens if master node appears in isolation from monitor and other node? Will there be multimaster layout and as consequence split brain?

- Is the monitor a single point of failure? What happens if monitor node falls?

**Comment by lfittl** [comment]
Thanks for reaching out @maksm90!

Re: primary showing up in isolation: The failover is initiated by the monitor detecting unavailability - the primary itself does not make this decision. Therefore the monitor node protects against split brain, and acts as the source of truth.

Re: monitor failure: If the monitor fails, the primary and secondary continue operating. Since all connections go directly to the primary, the application stays available. However, automated failovers are disabled until the monitor comes back.

The system is designed to tolerate the failure of any one node in the system, but (intentionally) not designed for two node failures in the current release.

**Comment by maksm90** [comment]
Hi @lfittl! Thanks for your fast response.

Some notes following your answer.

> the primary itself does not make this decision. Therefore the monitor node protects against split brain, and acts as the source of truth.

The primary have to **fence** itself in such case. Split-brain takes place here if replication was asynchronous and some client connections **remain hanging** on old master. This could avoid if clients themselves **detect** through periodic checking of monitor that primary node is not actual by now.

> If the monitor fails, the primary and secondary continue operating. Since all connections go directly to the primary, the application stays available. However, automated failovers are disabled until the monitor comes back.

It makes sense to incorporate some consensus protocol (e.g. raft) into monitor and keepers nodes so that functions of monitor is delegated to other agent if one falls

**Comment by dimitri** [comment]
Hi @maksm90, thanks for the interest and the kind words.

About fault tolerance in case of losing a node or in terms of network partition, you can read our documentation chapter that (hopefully) clarifies the decision making process we have implemented here. The documentation is available at https://pg-auto-failover.readthedocs.io/en/latest/fault-tolerance.html#network-partitions.

This part of the documentation seems most relevant to your first question here and the question of fencing. Our fencing implementation consists of shutting down Postgres on the primary node when we detect a network split: we can't connect from the primary node to neither the monitor nor the secondary (we get that information from Postgres system views, as documented at https://www.postgresql.org/docs/10/monitoring-stats.html#PG-STAT-REPLICATION-VIEW).

Here's what our documentation says about network isolation of the primary node:

> Primary can’t connect to Monitor

> Then it could be that either the primary is alone on its side of a network split, or that the monitor has failed. The keeper decide depending on whether the secondary node is still connected to the replication slot, and if we got a secondary, continues to serve PostgreSQL queries.

> Otherwise, when the secondary isn’t connected, and after the NETWORK_PARTITION_TIMEOUT has elapsed, the primary considers it might be alone in a network partition: that’s a split brain situation and there’s but one way to prevent it. The primary stops, and report a new state of DEMOTE_TIMEOUT.

**Comment by maksm90** [comment]
Hi @dimitri!
Thanks for your detailed response.

One yet question:
> The monitor is implemented as a PostgreSQL extension, so when you run the command pg_autoctl create monitor a PostgreSQL instance is initialized, configured with the extension, and started. The monitor service is embedded into a PostgreSQL service.

Why monitor node is embedded into PostgreSQL instance (as extension)? AFAICS this node is not responsible for user DB workload and doesn't participate in replication anyway. IMO it's proper to implement monitor as separate service without assigning to PostgreSQL.

I leave this issue as open for other curious users. You can close it when you'll see fit.

**Comment by dimitri** [comment]
We could have written the monitor with other tooling that's true. It being a Postgres extension gives us a lot of things for free, such as concurrency, transaction support, advanced locking infrastructure, transaction aware error handling, durability for the monitor state, a well known API and protocol that our client software already knows about (SQL, the Postgres protocol). So using Postgres for the monitor is a huge win for us here.

Closing the issue now, if more questions arise please feel free to add them here, re-opening the issue if action is needed!
