### ISSUE TITLE
README Please provide alternate recipe for adding repos

### ISSUE THREAD

**Issue by pete23** [citusdata/pg_auto_failover#13]
curl https://install.citusdata.com/community/deb.sh | sudo bash

Encouraging people to blindly execute content from the internet as root is as dangerous as it is convenient - on both security grounds and failure modes. Please provide alternate default instructions to add your repos.

(I hasten to add that this project looks awesome and I’ll be looking to see if we can drop some homegrown equivalents - thank you for opening this!)

**Comment by lfittl** [comment]
Good feedback - I agree we should provide alternate instructions here that contain the manual setup process for the repository.

**Comment by DimCitus** [comment]
So package cloud instructions are at the following page. I think the best way forward is to link those places from our documentation, which I am going to do in a PR:

  https://packagecloud.io/citusdata/community/install#manual-deb
  https://packagecloud.io/citusdata/community/install#manual-rpm
