### ISSUE TITLE
Support debian/ubuntu style PostgreSQLclusters

### ISSUE THREAD

**Issue by DimCitus** [citusdata/pg_auto_failover#135]
When using debian or ubuntu packages, `apt-get install postgresql` creates a cluster in `/var/lib/postgresql/11/main` (or another version), with configuration files in `/etc/` (both `PostgreSQL.conf` and `pg_hba.conf`.

  1. `pg_basebackup` is not copying the files from `/etc` so creating the standby node will fail (see #63) ; so `pg_autoctl create Postgres` could move the files over to `PGDATA`
  2. we want `pg_autoctl run` to be started as a service, and prevent the usual Postgres service to run (in some cases we need to ensure that the local Postgres is NOT running to avoid split-brain), so `pg_autoctl` should change debian configuration:
      - `mv /etc/postgresql/11/main/postgresql.conf` to $PGDATA
      - `mv /etc/postgresql/11/main/pg_hba.conf` to $PGDATA
      - `mv /etc/postgresql/11/main/pg_ident.conf` to $PGDATA
      - rename `/etc/postgresql/11/main/start.conf` to `start.conf.orig`
      - create `/etc/postgresql/11/main/start.conf` with the content `disabled` and a pg_auto_failover comment about DO NOT EDIT THIS FILE
      - issue a log WARN about integration with systemd or something else
  3. we may add symlinks to the 3 configuration files from `/etc/postgresql/11/main` to ease the life of our debian/ubuntu users.
  4. we need to actually edit the `postgresql.conf` file from debian, to comment out the lines where it changes `config_file` and `hba_file` and `ident_file` to use the default values (in PGDATA) again
  5. we should do this operation for any situation where the configuration files are not found in PGDATA, as our step to *own* the cluster.

**Comment by mtuncer** [comment]
This requirement does not address the case when user creates a new data directory via `pg_createcluster` . You can create a database directory as follows

`pg_createcluster -d /tmp/mydb 11 newdb`

This would create 2 directories
`/tmp/mydb` for `$PGDATA`
`/etc/postgresql/11/newdb` for storing configuration files

I haven't found a way to make association between 2 yet.

**Comment by DimCitus** [comment]
I think that the association is the value of the `data_directory` setting in the configuration file, when it is not the default value:

```
#------------------------------------------------------------------------------
# FILE LOCATIONS
#------------------------------------------------------------------------------

# The default values of these variables are driven from the -D command-line
# option or PGDATA environment variable, represented here as ConfigDir.

#data_directory = 'ConfigDir'       # use data in another directory
                    # (change requires restart)
#hba_file = 'ConfigDir/pg_hba.conf' # host-based authentication file
                    # (change requires restart)
#ident_file = 'ConfigDir/pg_ident.conf' # ident configuration file
                    # (change requires restart)
```
