### ISSUE TITLE
re-adding nodes after losing the monitor

### ISSUE THREAD

**Issue by vventirozos** [citusdata/pg_auto_failover#14]
Hello! 
First of all thanks for the effort you guys put into this, also kudos for using pg_rewind, awesome stuff !

While testing, i came across the following scenario : say that you lose the monitor some reason (in my test i just deleted the container). Replication keeps working, no issues there, but when i bring a new monitor up, i can add the master by removing the state file and issuing a "pg_autoctl create postgres", but when i try to add the slave, i get :
" 08:52:55 ERROR pg_autoctl doesn't know how to register an already existing standby server at the moment ". Of course, i can add it by rebuilding the slave but i was wondering if theres an alternative way doing this that won't require slave rebuild.

**Comment by dimitri** [comment]
Hi @vventirozos!

You're right: at the moment we don't have an easy way forward after losing the monitor node. We have ideas for implementing full fault tolerance for the monitor node. It might take some time before we get there.

Meanwhile, we could make it possible to re-register existing nodes from their local configuration. I can think of several ways to do it, either at the node level with a new `pg_autoctl` command, or (maybe better) at the monitor level with a new “auto-register active nodes” mode of operations that you would activate only in that case.
