### ISSUE TITLE
Postgres logs written to stderr not passed through

### ISSUE THREAD

**Issue by Bouke** [citusdata/pg_auto_failover#143]
I'm running postgres through pgautofailover using systemd. I want a simple logging setup, available through journalctl. So when running a single postgres node, the default `log_destination = stderr` would be fine. However pgautofailover owns the postgres process and doesn't appear to be forwarding the stderr output. As a result, journalctl only shows the log output from pgautofailover (parent process), but not postgres (child process). The output to stderr appears to be ignored.

**Comment by DimCitus** [comment]
Hi @Bouke ; thanks for using pg_auto_failover. The Postgres logs can be setup in the PostgreSQL configuration files. Also note that `pg_autoctl` is not the parent process for `postgres` as it only calls `pg_ctl start`, which does the double fork() unix strategy to launch services. 

What you see is that systemd somehow tracks the Postgres process as having been started by pg_autoctl, when this happens. Try `systemctl restart pgautofailover` and you should see that Postgres is not restarted and not listed anymore in the CGroup output from `systemctl status pgautofailover`.

Please consider setting up PostgreSQL logs the PostgreSQL way.
