### ISSUE TITLE
Build error on centos-8

### ISSUE THREAD

**Issue by gvaleika** [citusdata/pg_auto_failover#207]
Hi,

While compiling on centos8 machine master and release-1.2 branches I'm getting this error:

```
gv@centos8-1 pg_auto_failover]$ make
make -C src/monitor/ all
make[1]: Entering directory '/home/gv/work/pg_auto_failover/src/monitor'
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -std=c99 -Wall -Werror -Wno-unused-parameter -Iinclude -I/usr/pgsql-12/include -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o metadata.bc metadata.c
make[1]: /usr/lib64/ccache/clang: Command not found
make[1]: *** [/usr/pgsql-12/lib/pgxs/src/makefiles/../../src/Makefile.global:1044: metadata.bc] Error 127
make[1]: Leaving directory '/home/gv/work/pg_auto_failover/src/monitor'
make: *** [Makefile:25: monitor] Error 2
```

It seems somehow related to the location of extension makefiles.

clang is installed, but there is no /usr/lib64/ccache/clang thing. What are other prerequisites to build it in such environment?

Master compiles without issues on Archlinux. This machine  also doesn't have /usr/lib64/ccache/clang but everything works.

Best regards

**Comment by DimCitus** [comment]
Hi @gvaleika ; same prerequisites as the build dependencies for the Postgres package on you platform. The compiler invocation line is from `pg_config --cc`. I don't know how to install Postgres package build-dependencies on a RPM platform, so you'll have to find that out...

**Comment by gvaleika** [comment]
Hi,
for the record - this was not related to dependencies. Succeeded to compile using:

`make CLANG=/usr/bin/clang`

Without this build scripts get clang path from
/usr/pgsql-12/lib/pgxs/src/Makefile.global line LANG = /usr/lib64/ccache/clang

This as I understand is part of proper PG distribution.

My pg_config --cc returns gcc. I don't know how clang is related to pg_auto_failover build.
