### ISSUE TITLE
Monitor is down

### ISSUE THREAD

**Issue by barakshr** [citusdata/pg_auto_failover#208]
the monitor is a single point of failure 
is there any way to create a backup monitor on a different machine that will take charge?

**Comment by DimCitus** [comment]
At the moment we don't have disaster recovery integrated in pg_auto_failover. Our plan is to integrate DR capabilities and cover the monitor itself with our implementation. At the moment please consider using your own backup & restore solution for the monitor, with sync WAL archiving if possible.
