### ISSUE TITLE
repeat test failover failed

### ISSUE THREAD

**Issue by RazgrizHsu** [citusdata/pg_auto_failover#210]
![image](https://user-images.githubusercontent.com/3889141/77740423-32c8c580-704e-11ea-80c4-3cac2f5bf7b8.png)

when db01 is master, disconnect from lan,
then after 30 seconds i can see that db02 switch to primary,
then reconnect db01, db01 will be secondary,
then i disconnect db02 from lan, the monitor don't do anything, 
i'm trying to reboot monitor, the log still stay on `contacting the monitor to LISTEN to its events.`
i don't know what's wrong with monitor, 
because db02 still stay on primary... even IP unreachable

**Comment by DimCitus** [comment]
Hi @RazgrizHsu ; could you share `pg_autoctl` logs and `pg_autoctl show events` for us to have enough data to understand your situation?

**Comment by RazgrizHsu** [comment]
@DimCitus sorry, because it's online database,
i switch to pgpool2 few days ago,
i guess reason is i'm using DNS name like ( monitor.raz.lan, db01.raz.lan )
maybe use /etc/hosts name can resolve this issue,
but i haven't try, still thank you :D
