### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by Kriss64** [citusdata/pg_auto_failover#22]
Hi. I'm trying to setup pg_auto_failover on a CentOS machine (with rh-postgresql10). 
After successfully running yum install -y pg-auto-failover10_11, 
when I tried to run pg_autoctl to create monitor, it says pgautofailover extension is also required. 

After reading the README.md file, I came to know that this  extension is installed when we build from source. 

Now, When I ran make command inside pg_auto_failover/src, I got below error: 

```
[root@dc2-rhel1 monitor]# make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -std=c99 -Wall -Werror -Wno-unused-parameter -Iinclude -I/usr/include -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o metadata.o metadata.c
In file included from metadata.c:17:0:
metadata.h:16:30: fatal error: storage/lockdefs.h: No such file or directory
 #include "storage/lockdefs.h"
                              ^
compilation terminated.
make: *** [metadata.o] Error 1

```
Since it was looking for storage/lockdefs.h file, I downloaded it from postgresql server code and pasted it inside /usr/include/pgsql/server/storage/  and ran make command again which resulted in following error: 

```
[root@dc2-rhel1 monitor]# make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -std=c99 -Wall -Werror -Wno-unused-parameter -Iinclude -I/usr/include -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o metadata.o metadata.c
In file included from /usr/include/pgsql/server/access/genam.h:20:0,
                 from metadata.c:19:
/usr/include/pgsql/server/storage/lock.h:528:16: error: redefinition of ‘struct xl_standby_lock’
 typedef struct xl_standby_lock
                ^
In file included from metadata.h:16:0,
                 from metadata.c:17:
/usr/include/pgsql/server/storage/lockdefs.h:48:16: note: originally defined here
 typedef struct xl_standby_lock
                ^
In file included from /usr/include/pgsql/server/access/genam.h:20:0,
                 from metadata.c:19:
/usr/include/pgsql/server/storage/lock.h:533:3: error: conflicting types for ‘xl_standby_lock’
 } xl_standby_lock;
   ^
In file included from metadata.h:16:0,
                 from metadata.c:17:
/usr/include/pgsql/server/storage/lockdefs.h:53:3: note: previous declaration of ‘xl_standby_lock’ was here
 } xl_standby_lock;
   ^
metadata.c:22:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
                                 ^
compilation terminated.
make: *** [metadata.o] Error 1
```

Now I'm stuck here. 
Please let me know if I'm missing something.

**Comment by lfittl** [comment]
@Kriss64 Thanks for reaching out!

You shouldn't need to build from source in order to install the extension - the packages do provide the extension. What was the exact error you got?

**Comment by marcocitus** [comment]
You'll need the postgresql11-devel package (or postgresql-server-dev-11 on
Debian/Ubuntu) to build pg_auto_failover from source.

**Comment by Kriss64** [comment]
Hi @lfittl , below is the error: 

-bash-4.2$ /usr/pgsql-11/bin/pg_autoctl create monitor --pgdata /var/opt/rh/rh-postgresql10/lib/pgsql/data/
16:24:09 INFO  Installing pg_auto_failover monitor in existing PostgreSQL instance at "/var/opt/rh/rh-postgresql10/lib/pgsql/data/" running on port 5432
16:24:09 INFO  The user "autoctl" already exists, skipping.
16:24:09 INFO  The database "pg_auto_failover" already exists, skipping.
16:24:09 ERROR Failed to create extension "pgautofailover"[58P01]: ERROR:  could not open extension control file "/opt/rh/rh-postgresql10/root/usr/share/pgsql/extension/pgautofailover.control": No such file or directory

16:24:09 ERROR Failed to create extension pgautofailover
16:24:09 FATAL Failed to install pg_auto_failover monitor, see above for details

Let me know how to install this extension so that I can proceed further.

**Comment by lfittl** [comment]
@Kriss64 Could you try using the Postgres packages from PGDG (the official Postgres repository), instead of the ones that come bundled with CentOS?

**Comment by Kriss64** [comment]
@lfittl, The version of postgres server has to be rh-postgresql10 for my testing. 
can you tell me which package are you talking about?

**Comment by lfittl** [comment]
@Kriss64 I'm referencing the Postgres packages provided by the Postgres project itself at https://yum.postgresql.org/

My understanding is that we currently don't support using any other Postgres packages, as the paths are different, and our packages are compiled against a particular Postgres package as well. cc @thanodnl 

If you have to use the Postgres packages provided by CentOS, building from source would be the way to go - @marcocitus referenced whats needed for that earlier.

**Comment by mtuncer** [comment]
@DimCitus do we have any actionable item on this ? I am inclined to close the issue

**Comment by DimCitus** [comment]
Closing the issue now, for clean-up purposes. If more help is needed, please consider re-opening with more information.
