### ISSUE TITLE
do_commands without debug

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#229]
why not do_commands without debug?

**Comment by DimCitus** [comment]
Hi @RekGRpth ; thanks for your interest in pg_auto_failover.

While some of the PG_AUTOCTL_DEBUG commands can turn useful in some advanced problematic situations to help debug and sometimes fix a production environment, most of the PG_AUTOCTL_DEBUG commands are exposed for us developers to be able to do some unit testing on our lower level features.

Most of the PG_AUTOCTL_DEBUG commands when used in production would damage your installation or make it impossible for pg_auto_failover to then orchestrate. Please refrain from using this API as much as possible, unless your goal is to dive in the details of our implementation to better understand it, in the lab.
