### ISSUE TITLE
monitor without own database

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#231]
how about use monitor without own database?
monitor may use primary database
and then by replication all information will be available on all standby databases
when host with primary database is down, then first (by order of registering) standby becomes primary and other standbys connect to new primary
when old primary is up, it check all known standbys, is some becomes primary

**Comment by DimCitus** [comment]
Hi @RekGRpth. The goal of the monitor being on a separated node is to be able to recognise network splits and avoid split-brain situations in those cases. You can read more about this idea in the documentation section at https://pg-auto-failover.readthedocs.io/en/latest/fault-tolerance.html#network-partitions.

**Comment by RekGRpth** [comment]
> the monitor being on a separated node

but in this case monitor database is not protect of crash!

**Comment by DimCitus** [comment]
Yes the monitor is a SPOF (Single Point of Failure) at the moment in pg_auto_failover. The important thing to remember is that Postgres does NOT need our monitor to implement replication, so nothing breaks when you lose the monitor. The only thing missing at this point in time is your ability to failover. 

Our roadmap includes providing a fault tolerance mechanism for the monitor, and we're thinking in terms of disaster recovery for that node.

**Comment by RekGRpth** [comment]
May be use memcached instead of monitor with database?
