### ISSUE TITLE
How to replace secondary node with my new machine ?

### ISSUE THREAD

**Issue by hancci** [citusdata/pg_auto_failover#268]
**How to replace secondary node with my new machine ?**

I am using both primary and secondary nodes. ( pg_autoctl version 1.2 )
So I'd like to know how to replace all machines most gracefully without downtime. ( or minimal downtime )
I don't want to perform `pg_autoctl create postgres`  for minimal downtime.
I think it will perform `pg_basebackup` and It may take a long time. 

**My scenarios is as follows**
  * **Step 1**. Install and restore a new standby node with pg_basebackup from prior secondary node's pgdata.
  * **Step 2**. Put a prior secondary node in a MAINTENANCE state. `pg_autoctl enable maintenance`
  * **Step 3**. Stop keeper in a prior secondary node. `pg_autoctl stop`
  * **Step 4**. Update node information in the montor  `update node set nodename='new-secondary' where nodeid='2';`
  * **Step 5**. Copy pg_autoctl.cfg , pg_autoctl.state from prior secondary to new one.
  * **Step 6**. Stop prior secondary database `pg_ctl stop` and start new secondary database `pg_ctl start`
  * **Step 7**. Start keeper in a new secodary node. `pg_autoctl start`
  * **Step 8**. Disable maintenance mode in a new secodary node. `pg_autoctl disable maintenance`
  * **Step 9**. Switchover primary and secondary `pg_autoctl perform switchover`
  * **Step 10**. Repeat from step 1 to 9
  
**Is it possible and reasonable ?**
Could I get some help please.

Regards,
Han

**Comment by DimCitus** [comment]
Hi @hancci ; thanks for your questions and your patience. I just saw this issue today, sorry. So in the meantime the current version of pg_auto_failover is 1.4.2 and multiple standby nodes is a fully supported feature. With the current code, just add two new nodes, and then perform a manual promotion, then drop the two nodes you want to remove.
