### ISSUE TITLE
How to avoid monitor node to became a SPOF

### ISSUE THREAD

**Issue by msurendar** [citusdata/pg_auto_failover#295]
Hello Team,

I have been setting up a postgres HA + automate failover on Production env. Since doing that, noticed monitor node will be Single point of failure if it goes down. So how can i avoid this ? 

Can i set monitor node as HA ? or any other possible ways ?

Regards,
Surendar M

**Comment by msurendar** [comment]
Hello Team,

As i said earlier, I crashed monitor server after taking backup of monitor database (pg_basebackup) and .config folder backup. After crash, when i restored the database with backup am unable to do failover after that ? It seems monitor was not working properly after restoration.

How do i overcome this ? What's the action has to taken for monitor server to avoid failures ?

Regards,
Surendar M

**Comment by DimCitus** [comment]
Hi @msurendar ; thanks for using pg_auto_failover and opening an issue here!

We know that the monitor is a SPOF and our current answer is to use backup & archiving solutions such as pgbackrest on this node. You need to have a copy with the current state, so a base backup without the archiving of the WAL files is going to be problematic.

Our plan is to later include Disaster Recovery (and PITR) features in pg_auto_failover for the monitor, and even later for the Postgres nodes. We're not there yet though.

For more specific advice, please share more specific errors. In that case feel free to open this issue again with more content, of course.
