### ISSUE TITLE
Recommendations (or instructions) to setup a read replica

### ISSUE THREAD

**Issue by dantti** [citusdata/pg_auto_failover#320]
I've configured pg_auto_failover, I tried to add a third node expecting it to perhaps be another read replica in async mode, but it doesn't allow to more than 2 nodes.

Could some docs/recommendations be added to the docs on how to do this setup?

I wonder how this would behave if there is too much WAL lag that pg_backup has to be issues again, and I believe it would need to be done manually, could pg_auto_failover automate this too?

**Comment by DimCitus** [comment]
Hi @dantti, 

Thanks for your interest in pg_auto_failover. As of version 1.3, we only support a single architecture with two nodes, the primary and the secondary. Starting in version 1.4, to be released “very soon now”, you will be able to achieve what you ask by using:

    pg_autoctl create postgres ... --replication-quorum false

**Comment by DimCitus** [comment]
The ability to add more than one standby node is going to be released very soon in pg_auto_failover 1.4 and the documentation for it is already finished and has been merged. You can have a look at https://pg-auto-failover.readthedocs.io/en/latest/architecture-multi-standby.html.

**Comment by dantti** [comment]
Awesome thanks, one critics that pg_auto_failover got on #postgres was that it would keep working if a node fails, is it possible now in 1.4 that it stops working it it doesn't have a sync replication? The reasoning was data integrity that could be compromised in case the last node failed (I understand that business continuity was chosen to be more important but I wonder that now with more nodes it could be configured).

I think now I only miss the libpq ability to connect to write-only and I think it also doesn't disconnects when you do a manual switchover. But this is not up to you anyway..

**Comment by DimCitus** [comment]
> Awesome thanks, one critics that pg_auto_failover got on #postgres was that it would keep working if a node fails, is it possible now in 1.4 that it stops working it it doesn't have a sync replication? The reasoning was data integrity that could be compromised in case the last node failed (I understand that business continuity was chosen to be more important but I wonder that now with more nodes it could be configured).

Yeah that's a fair critique, although when you only have one standby blocking writes doesn't make sense. What we achieve with a single standby is a good failover mechanism. If you lose the standby, you can't failover anymore, and we bail out. There's no way to achieve good support for both data durability and service availability with only two nodes (one primary, one secondary). 

Starting in pg_auto_failover 1.4 it is now possible to have 3 nodes, one primary, two secondaries. Then you can setup [number-sync-standbys](https://pg-auto-failover.readthedocs.io/en/latest/architecture-multi-standby.html#number-sync-standbys) to 1 and continue with sync replication when losing one standby. Basically you need at least `number-sync-standbys + 1` standby nodes with `replication-quorum` to implement both data durability and service availability. That's the trick that allows serving writes when losing a standby, without impacting your data durability.

The default in pg_auto_failover 1.4 is to automatically switch `number_sync_standbys` from zero to one when a second standby (with `replication-quorum`) is added.

> I think now I only miss the libpq ability to connect to write-only and I think it also doesn't disconnects when you do a manual switchover. But this is not up to you anyway..

I guess you mean using the following connection string to connect to your formation:

```
$ pg_autoctl show uri
      Type |    Name | Connection String
-----------+---------+-------------------------------
   monitor | monitor | postgres://autoctl_node@localhost:5500/pg_auto_failover?sslmode=require
 formation | default | postgres://localhost:5502,localhost:5501/postgres?target_session_attrs=read-write&sslmode=require
```

That's the client-side parts of HA. We can't solve client-side HA on the server-side, and pg_auto_failover scope is managing what happens on the server-side when there is a failover. So yeah, you're right, this is not up to pg_auto_failover anyway.
