### ISSUE TITLE
Transition from catchingup to secondary takes a long time

### ISSUE THREAD

**Issue by JelteF** [citusdata/pg_auto_failover#329]
For some reason on an empty cluster, when adding a standby for the first time the transition from `catchingup` to `secondary` takes 15 seconds. 
```
12:46:30 7863 INFO  The version of extension "pgautofailover" is "1.3" on the monitor
12:46:30 7863 INFO  Reloaded the new configuration from "/home/jelte/.config/pg_autoctl/home/jelte/work/pg_auto_failover/node2/pg_autoctl.cfg"
12:46:30 7863 INFO  pg_autoctl service is running, current state is "catchingup"
12:46:45 7863 INFO  Monitor assigned new state "secondary"
12:46:45 7863 INFO  FSM transition from "catchingup" to "secondary": Convinced the monitor that I'm up and running, and eligible for promotion again
12:46:45 7863 INFO  Creating replication slot "pgautofailover_standby_1"
12:46:45 7863 INFO  Transition complete: current state is now "secondary"
```

I'm not sure what's happening here. Maybe it is expected. However, it's a bit weird that it takes 15 seconds while seemingly nothing happens. Note, `pg_basebackup` has already completed at that point. Also when looking at `pgautofailover.node` both nodes report the same LSN for quite some time already.

**Comment by JelteF** [comment]
Fixing this would likely benefit:
1. Time spent in CI
2. Time that the change-run dev cycle takes
3. Time cluster spends in an unhealthy state
4. Possibly it would find an underlying issue that might have other unintented side effects

**Comment by onderkalaci** [comment]
I also realized this

**Comment by DimCitus** [comment]
One thing that might be of importance is that we switch from CATCHINGUP to SECONDARY only after the health has been probed “good” from the monitor, even when `pg_autoctl` on the node-active client process reports that Postgres is running. That's good precautions, but we only check a node health so often.

It might be a good idea to check every second or even more frequently when a node is in CATCHINGUP state?

The following diff allows to have more information about the health check timings from the monitor console output. I think we should prepare a PR that extends this idea and also creates an event in our event table, allowing to make debugging even easier by our users. We would need a new `InsertEventWithCurrentState` function and possibly a new column for the health of the node in the event table, but maybe the description could be enough to expose the background activity to the end-users.

``` diff
modified   src/monitor/health_check_metadata.c
@@ -15,6 +15,7 @@
 
 #include "health_check.h"
 #include "metadata.h"
+#include "notifications.h"
 
 #include "access/htup.h"
 #include "access/tupdesc.h"
@@ -172,6 +173,8 @@ SetNodeHealthState(char *nodeName, uint16 nodePort, int healthState)
 
 	if (HaMonitorHasBeenLoaded())
 	{
+		char message[BUFSIZE] = { 0 };
+
 		initStringInfo(&query);
 		appendStringInfo(&query,
 						 "UPDATE " AUTO_FAILOVER_NODE_TABLE
@@ -185,6 +188,12 @@ SetNodeHealthState(char *nodeName, uint16 nodePort, int healthState)
 
 		spiStatus = SPI_execute(query.data, false, 0);
 		Assert(spiStatus == SPI_OK_UPDATE);
+
+		LogAndNotifyMessage(message, sizeof(message),
+							"Node %s:%d is marked as %s by the monitor",
+							nodeName,
+							nodePort,
+							healthState == 0 ? "unhealthy" : "healthy");
 	}
 	else
 	{
```
