### ISSUE TITLE
What is formation and group??

### ISSUE THREAD

**Issue by atulsingh20081** [citusdata/pg_auto_failover#362]
Hi Team,

This is not an issue but I wanted information about formation and group. Apart from this can monitor  manage multiple clusters of postgres with replication.

For eg -> I have node a & node b which are in one cluster and replication of data happens between them.
Similarly I have node c & node d which run in one cluster and replication of data happens between them.
Can monitor manage both of these clusters?

This is not an issue but I wanted information about these things, didnt know how to reach out to you guys. If there is an alternate place to raise such questions please do let me know .

**Comment by DimCitus** [comment]
Hi @atulsingh20081, thanks for asking! In pg_auto_failover terms you have then two formations, each one with a group of two services. Formation "one" with group 0 and nodes a and b, formation "two" with group 0 and nodes c and d. 

We might want to explain that better in the docs, leaving this issue open with that in mind.

**Comment by atulsingh20081** [comment]
Thanks @DimCitus for the quick reply.

How about these commands for the above mentioned scenario
For cluster in which node a & node b is there :

pg_autoctl create postgres --nodename **node_a** --pgport 6001 --formation **form1** --group 0 --monitor postgres://autoctl_node@localhost:6000/pg_auto_failove
pg_autoctl create postgres --nodename **node_b** --pgport 6001 --formation **form1** --group 0 --monitor postgres://autoctl_node@localhost:6000/pg_auto_failover

For cluster in which node c & node d is there :
pg_autoctl create postgres --nodename **node_c** --pgport 6001 --formation **form2** --group 0 --monitor postgres://autoctl_node@localhost:6000/pg_auto_failove
pg_autoctl create postgres --nodename **node_d** --pgport 6001 --formation **form2** --group 0 --monitor postgres://autoctl_node@localhost:6000/pg_auto_failover


Can you please take a look and let me know if these are correct?

**Comment by DimCitus** [comment]
Some comments apply:
  1. you need to first create the formations using `pg_autoctl create formation`
  2. the `--nodename` needs to be the hostname used by the other nodes when connecting to the node, so your commands require a DNS service to resolve "node_a" for you from every node on the system, same with other nodes of course

**Comment by atulsingh20081** [comment]
What do nodes in same formation, but different groups signify?

**Comment by DimCitus** [comment]
See https://pg-auto-failover.readthedocs.io/en/latest/architecture.html#group:

> The notion of a formation that contains multiple groups in pg_auto_failover is useful when setting up and managing a whole Citus formation, where the coordinator nodes belong to group zero of the formation, and each Citus worker node becomes its own group and may have Postgres standby nodes.

**Comment by atulsingh20081** [comment]
If I have to create a formation where should I run the command pg_autoctl create formation, on host where monitor is running or on host where actual db instance is running?

**Comment by DimCitus** [comment]
The formation is going to be created on the monitor. You can use any client connection to the monitor to do that though. So that's up to you to decide. I would mostly run the `pg_autoctl create formation` command from the monitor node itself, I think.

**Comment by atulsingh20081** [comment]
Hi @DimCitus ,

pg_autoctl create postgres --nodename 10.233.233.40 --formation configdb --pgport 5432 --monitor postgres://autoctl_node@10.233.233.34:5432/pg_auto_failover

postgres: unrecognized option '--nodename 10.233.233.40 --formation'
05:33:30 FATAL Failed to set the monitor URI: use either --monitor postgresql://... or --disable-monitor

I am getting this issue while creating a standalone server. Can you please help?

**Comment by atulsingh20081** [comment]
Hi @DimCitus 

Getting the following error while starting a secondary DB:
Command --> pg_autoctl create postgres --nodename 10.233.233.40 --pgport 5432 --monitor postgres://autoctl_node@10.233.233.34:5432/pg_auto_failover --formation configdb


06:07:50 INFO  Continuing from a previous `pg_autoctl create` failed attempt
06:07:50 INFO  PostgreSQL state at registration time was: PGDATA does not exists
06:07:50 INFO  FSM transition from "wait_standby" to "catchingup": The primary is now ready to accept a standby
06:07:50 INFO  The primary node returned by the monitor is 10.233.233.35:5432
06:07:50 INFO  Initialising PostgreSQL as a hot standby
06:07:50 INFO  Running /usr/pgsql-11/bin/pg_basebackup -w -h 10.233.233.35 -p 5432 --pgdata /var/lib/pgsql/11/backup/10.233.233.40 -U pgautofailover_replicator --write-recovery-conf --max-rate 100M --wal-method=stream --slot pgautofailover_standby ...
06:07:51 ERROR pg_basebackup: initiating base backup, waiting for checkpoint to complete
pg_basebackup: checkpoint completed
pg_basebackup: write-ahead log start point: 0/2C000028 on timeline 1
pg_basebackup: starting background WAL receiver
    0/24925 kB (0%), 0/1 tablespace (...ackup/10.233.233.40/backup_label)
pg_basebackup: could not send replication command "START_REPLICATION": ERROR:  replication slot "pgautofailover_standby" does not exist
13069/24925 kB (52%), 0/1 tablespace (...backup/10.233.233.40/base/1/2658)
24935/24935 kB (100%), 0/1 tablespace (.../10.233.233.40/global/pg_control)
24935/24935 kB (100%), 1/1 tablespace                                         
pg_basebackup: write-ahead log end point: 0/2C0000F8
pg_basebackup: waiting for background process to finish streaming ...
pg_basebackup: child process exited with error 1
pg_basebackup: removing contents of data directory "/var/lib/pgsql/11/backup/10.233.233.40"

06:07:51 ERROR Failed to run pg_basebackup: exit code 1
06:07:51 ERROR Failed initialise standby server, see above for details
06:07:51 ERROR Failed to transition from state "wait_standby" to state "catchingup", see above.


Any idea what am I doing wrong?

**Comment by DimCitus** [comment]
Hi @atulsingh20081 ; which version of pg_auto_failover are you using in your report?

The problem you are having is `pg_basebackup: could not send replication command "START_REPLICATION": ERROR:  replication slot "pgautofailover_standby" does not exist`. We need more logs from the monitor and the primary to understand the situation better.
