### ISSUE TITLE
Disaster recovery process

### ISSUE THREAD

**Issue by henrygodwin** [citusdata/pg_auto_failover#381]
Hello all,

I'm relatively new to postgres and pg_auto_failover so apologies if this is a stupid question. I've got a two node cluster working perfectly and now I'm thinking about DR. There is a fast amount of information about restoring data in Postgres, but I can't find much specific to pg_auto_failover.

I was hoping to use Veeam Agent for Linux to create transactionally consistent file system backup, but I'm slightly confused about this would work in a clustered environment. 

Say I have two nodes in the cluster, prod-db1 (primary read/write) and prod-db2 (secondary read only), plus the monitor node. Veeam is configured to take backups every 15 minutes of both nodes, At 10am we figure out that something isn't right with the data and we need to restore to 6am that morning.

What would the sequence of events be to get the cluster back to 6am? Do I shutdown both of the nodes, plus the monitor node, restore the 6am file system backup containing the pgdata folder from the primary node to both the primary and the secondary? Then restart the nodes and the monitor?

Would it be better to use PITR and WAL Archiving? Is there anything specific in need to know about using this with pg_auto_failover?

Thanks,

Henry

**Comment by DimCitus** [comment]
Hi @henrygodwin ; thanks for using pg_auto_failover and the feedback here.

The method you describe might be the easiest way to implement the DR yes. It is possible to use `pg_autoctl create postgres` on-top of an existing PGDATA that comes from your backup and recovery mechanism. In version 1.3 that only works on the primary, in version 1.4 (soon to be released) that works for either the primary or a secondary node.

You can use a new formation on the monitor, or swipe the existing monitor and start from scratch there too, both are possible ways to do it. You can also `pg_autoctl drop node` for the previous running system to clean-up the monitor registrations.

Finally I don't know how to compare Veeam and classic PITR and WAL Archiving for Postgres. In general, it's best to use PITR and WAL archiving, see if Veeam supports that mode of operations.
