### ISSUE TITLE
Bulk feedback on master branch pre 1.4 release

### ISSUE THREAD

**Issue by trecloux** [citusdata/pg_auto_failover#385]
Hi All,

This issue is following a [twitter thread](https://twitter.com/tapoueh/status/1301025400810766338) with @DimCitus.

As an introduction, we (https://github.com/auchanretailfrance) are evaluating pg_auto_failover in a Kubernetes context and started to build an Helm chart to support this context. If we succeed, we will opensource the Helm chart.

After testing a custom build of master branch ( commit 0e4d2c972f3265789c5bbfb60a26ef9d76e6bc57 ), here is our feedback.

- pg_autofailover is generating PostgreSQL tuning parameters.
  With PostgreSQL >= 12, these parameters are duplicated in `postgresql-auto-failover.conf` and `postgresql-auto-failover-standby.conf`
  With PostgreSQL < 12, these parameters are duplicated in `postgresql-auto-failover.conf` and `recovery.conf`.
  When PostgreSQL 11 is parsing `recovery.conf` file, it raises an error and PostgreSQL can't start.
  This is a blocker for PostgreSQL 11.

- in a container environment, it looks like the postgresql tuning is based on the host resources, not on the container/cgroup limits. Ex `7537 MB` for a container with 1GB memory limit.

- `--nodename` parameter was replaced by `--hostname`, this is breaking existing scripts and CLI error message does not mention the new parameter name. It might be interesting to outline this change in the release notes, and/or in the CLI error message.

**Comment by trecloux** [comment]
Here are the details to reproduce the recovery.conf parsing error

- build docker image from Dockerfile at root of repository
```
sudo docker build -t pg_auto_failover .
Sending build context to Docker daemon  7.312MB
Step 1/15 : FROM debian:buster-slim
 ---> c7346dd7f20e
....
Step 15/15 : ENV PATH $PATH:/usr/lib/postgresql/11/bin
 ---> Running in abc9e556baeb
Removing intermediate container abc9e556baeb
 ---> ebe48efec9b2
Successfully built ebe48efec9b2
Successfully tagged pg_auto_failover:latest

```

- create the container, create the monitor, run the monitor 

```
sudo docker run -ti --user postgres --name pg_autofailover  pg_auto_failover
postgres@c7950c4aaba4:/usr/src/pg_auto_failover$ /usr/lib/postgresql/11/bin/pg_autoctl create monitor --pgdata /tmp/monitor --hostname localhost --pgport 5432 --pgctl /usr/lib/postgresql/11/bin/pg_ctl --auth trust --no-ssl
19:59:50 6 WARN  No encryption is used for network traffic! This allows an attacker on the network to read all replication data.
19:59:50 6 WARN  Using --ssl-self-signed instead of --no-ssl is recommend to achieve more security with the same ease of deployment.
19:59:50 6 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details on how to improve
19:59:50 6 INFO  Using default --ssl-mode "prefer"
19:59:50 6 INFO  Initialising a PostgreSQL cluster at "/tmp/monitor"
19:59:50 6 INFO  /usr/lib/postgresql/11/bin/pg_ctl initdb -s -D /tmp/monitor --option '--auth=trust'
19:59:55 6 INFO  Started pg_autoctl postgres service with pid 25
19:59:55 25 INFO   /usr/lib/postgresql/11/bin/pg_autoctl do service postgres --pgdata /tmp/monitor -v
19:59:55 6 INFO  Started pg_autoctl monitor-init service with pid 26
19:59:55 31 INFO   /usr/lib/postgresql/11/bin/postgres -D /tmp/monitor -p 5432 -h *
19:59:55 25 INFO  Postgres is now serving PGDATA "/tmp/monitor" on port 5432 with pid 31
19:59:57 26 WARN  NOTICE:  installing required extension "btree_gist"
19:59:57 26 INFO  Granting connection privileges on 127.0.0.0/8
19:59:57 26 INFO  Your pg_auto_failover monitor instance is now ready on port 5432.
19:59:57 26 INFO  Monitor has been successfully initialized.
19:59:57 6 WARN  pg_autoctl service monitor-init exited with exit status 0
19:59:57 25 INFO  Postgres controller service received signal SIGTERM, terminating
19:59:57 25 INFO  Stopping pg_autoctl postgres service
19:59:57 25 INFO  /usr/lib/postgresql/11/bin/pg_ctl --pgdata /tmp/monitor --wait stop --mode fast
19:59:58 6 INFO  Waiting for subprocesses to terminate.
19:59:58 6 INFO  Stop pg_autoctl
postgres@c7950c4aaba4:/usr/src/pg_auto_failover$ /usr/lib/postgresql/11/bin/pg_autoctl run --pgdata /tmp/monitor
20:00:09 46 INFO  Started pg_autoctl postgres service with pid 49
20:00:09 49 INFO   /usr/lib/postgresql/11/bin/pg_autoctl do service postgres --pgdata /tmp/monitor -v
20:00:09 46 INFO  Started pg_autoctl listener service with pid 50
20:00:09 50 INFO   /usr/lib/postgresql/11/bin/pg_autoctl do service listener --pgdata /tmp/monitor -v
20:00:09 50 INFO  pg_auto_failover monitor is ready at postgres://autoctl_node@localhost:5432/pg_auto_failover?sslmode=prefer
20:00:09 56 INFO   /usr/lib/postgresql/11/bin/postgres -D /tmp/monitor -p 5432 -h *
20:00:09 49 INFO  Postgres is now serving PGDATA "/tmp/monitor" on port 5432 with pid 56
20:00:09 50 INFO  The version of extension "pgautofailover" is "1.3" on the monitor
20:00:09 50 INFO  Contacting the monitor to LISTEN to its events.
```

- start an other shell in the same container, create and start node1

```
sudo docker exec -ti pg_autofailover bash 
postgres@c7950c4aaba4:/usr/src/pg_auto_failover$ /usr/lib/postgresql/11/bin/pg_autoctl create postgres --pgdata /tmp/node1 --name node1 --hostname localhost --pgport 5433 --pgctl /usr/lib/postgresql/11/bin/pg_ctl --auth trust --no-ssl --dbname ha  --monitor 'postgres://autoctl_node@localhost:5432/pg_auto_failover?sslmode=prefer'
20:02:36 80 WARN  No encryption is used for network traffic! This allows an attacker on the network to read all replication data.
20:02:36 80 WARN  Using --ssl-self-signed instead of --no-ssl is recommend to achieve more security with the same ease of deployment.
20:02:36 80 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details on how to improve
20:02:36 80 INFO  Using default --ssl-mode "prefer"
20:02:36 80 INFO  Started pg_autoctl postgres service with pid 82
20:02:36 82 INFO   /usr/lib/postgresql/11/bin/pg_autoctl do service postgres --pgdata /tmp/node1 -v
20:02:36 80 INFO  Started pg_autoctl node-init service with pid 83
20:02:37 83 INFO  Registered node 1 (localhost:5433) with name "node1" in formation "default", group 0, state "single"
20:02:37 83 INFO  Writing keeper state file at "/var/lib/postgresql/.local/share/pg_autoctl/tmp/node1/pg_autoctl.state"
20:02:37 83 INFO  Writing keeper init state file at "/var/lib/postgresql/.local/share/pg_autoctl/tmp/node1/pg_autoctl.init"
20:02:37 83 INFO  Successfully registered as "single" to the monitor.
20:02:37 83 INFO  FSM transition from "init" to "single": Start as a single node
20:02:37 83 INFO  Initialising postgres as a primary
20:02:37 83 INFO  Initialising a PostgreSQL cluster at "/tmp/node1"
20:02:37 83 INFO  /usr/lib/postgresql/11/bin/pg_ctl initdb -s -D /tmp/node1 --option '--auth=trust'
20:02:42 4146 INFO   /usr/lib/postgresql/11/bin/postgres -D /tmp/node1 -p 5433 -h *
20:02:42 83 INFO  CREATE DATABASE ha;
20:02:43 82 INFO  Postgres is now serving PGDATA "/tmp/node1" on port 5433 with pid 4146
20:02:44 83 INFO  CREATE EXTENSION pg_stat_statements;
20:02:44 83 INFO  Transition complete: current state is now "single"
20:02:44 83 INFO  keeper has been successfully initialized.
20:02:44 80 WARN  pg_autoctl service node-init exited with exit status 0
20:02:44 82 INFO  Postgres controller service received signal SIGTERM, terminating
20:02:44 82 INFO  Stopping pg_autoctl postgres service
20:02:44 82 INFO  /usr/lib/postgresql/11/bin/pg_ctl --pgdata /tmp/node1 --wait stop --mode fast
20:02:44 80 INFO  Waiting for subprocesses to terminate.
20:02:44 80 INFO  Stop pg_autoctl
postgres@c7950c4aaba4:/usr/src/pg_auto_failover$ /usr/lib/postgresql/11/bin/pg_autoctl run --pgdata /tmp/node1
20:02:46 4166 INFO  Started pg_autoctl postgres service with pid 4169
20:02:46 4169 INFO   /usr/lib/postgresql/11/bin/pg_autoctl do service postgres --pgdata /tmp/node1 -v
20:02:46 4166 INFO  Started pg_autoctl node-active service with pid 4170
20:02:46 4170 INFO   /usr/lib/postgresql/11/bin/pg_autoctl do service node-active --pgdata /tmp/node1 -v
20:02:46 4170 INFO  Reloaded the new configuration from "/var/lib/postgresql/.config/pg_autoctl/tmp/node1/pg_autoctl.cfg"
20:02:46 4170 INFO  pg_autoctl service is running, current state is "single"
20:02:46 4180 INFO   /usr/lib/postgresql/11/bin/postgres -D /tmp/node1 -p 5433 -h *
20:02:46 4169 INFO  Postgres is now serving PGDATA "/tmp/node1" on port 5433 with pid 4180
20:02:46 4170 WARN  PostgreSQL was not running, restarted with pid 4180
```

- start an other shell and create node 2

```
sudo docker exec -ti pg_autofailover bash  
postgres@c7950c4aaba4:/usr/src/pg_auto_failover$ /usr/lib/postgresql/11/bin/pg_autoctl create postgres --pgdata /tmp/node2 --name node2 --hostname localhost --pgport 5434 --pgctl /usr/lib/postgresql/11/bin/pg_ctl --auth trust --no-ssl --dbname ha  --monitor 'postgres://autoctl_node@localhost:5432/pg_auto_failover?sslmode=prefer'
20:04:33 4630 WARN  No encryption is used for network traffic! This allows an attacker on the network to read all replication data.
20:04:33 4630 WARN  Using --ssl-self-signed instead of --no-ssl is recommend to achieve more security with the same ease of deployment.
20:04:33 4630 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details on how to improve
20:04:33 4630 INFO  Using default --ssl-mode "prefer"
20:04:33 4630 INFO  Started pg_autoctl postgres service with pid 4632
20:04:33 4632 INFO   /usr/lib/postgresql/11/bin/pg_autoctl do service postgres --pgdata /tmp/node2 -v
20:04:33 4630 INFO  Started pg_autoctl node-init service with pid 4633
20:04:33 4633 INFO  Registered node 2 (localhost:5434) with name "node2" in formation "default", group 0, state "wait_standby"
20:04:33 4633 INFO  Writing keeper state file at "/var/lib/postgresql/.local/share/pg_autoctl/tmp/node2/pg_autoctl.state"
20:04:33 4633 INFO  Writing keeper init state file at "/var/lib/postgresql/.local/share/pg_autoctl/tmp/node2/pg_autoctl.init"
20:04:33 4633 INFO  Successfully registered as "wait_standby" to the monitor.
20:04:33 4633 INFO  FSM transition from "init" to "wait_standby": Start following a primary
20:04:33 4633 INFO  Transition complete: current state is now "wait_standby"
20:04:34 4633 INFO  FSM transition from "wait_standby" to "catchingup": The primary is now ready to accept a standby
20:04:34 4633 INFO  Initialising PostgreSQL as a hot standby
20:04:34 4633 INFO   /usr/lib/postgresql/11/bin/pg_basebackup -w -d application_name=pgautofailover_standby_2 host=localhost port=5433 user=pgautofailover_replicator sslmode=prefer --pgdata /tmp/backup/node_2 -U pgautofailover_replicator --verbose --progress --max-rate 100M --wal-method=stream --slot pgautofailover_standby_2
20:04:34 4633 INFO  pg_basebackup: initiating base backup, waiting for checkpoint to complete
20:04:35 4633 INFO  pg_basebackup: checkpoint completed
20:04:35 4633 INFO  pg_basebackup: write-ahead log start point: 0/2000060 on timeline 1
20:04:35 4633 INFO  pg_basebackup: starting background WAL receiver
20:04:35 4633 INFO      0/31493 kB (0%), 0/1 tablespace (/tmp/backup/node_2/backup_label    )
20:04:35 4633 INFO  31503/31503 kB (100%), 0/1 tablespace (.../backup/node_2/global/pg_control)
20:04:35 4633 INFO  31503/31503 kB (100%), 1/1 tablespace                                         
20:04:35 4633 INFO  pg_basebackup: write-ahead log end point: 0/2000130
20:04:35 4633 INFO  pg_basebackup: waiting for background process to finish streaming ...
20:04:41 4633 INFO  pg_basebackup: base backup completed
20:04:41 4633 INFO  Writing recovery configuration to "/tmp/node2/recovery.conf"
20:04:41 4633 WARN  Contents of "/tmp/node2/postgresql-auto-failover.conf" have changed, overwriting
20:04:41 4676 INFO   /usr/lib/postgresql/11/bin/postgres -D /tmp/node2 -p 5434 -h *
20:04:51 4632 ERROR Failed get postmaster pid, file "/tmp/node2/postmaster.pid" does not exists
20:04:51 4632 ERROR Failed to get Postgres pid, see above for details
20:04:51 4632 WARN  Postgres logs from "/tmp/node2/startup.log":
20:04:51 4632 ERROR 2020-09-02 20:04:41.254 UTC [4676] LOG:  listening on IPv4 address "0.0.0.0", port 5434
20:04:51 4632 ERROR 2020-09-02 20:04:41.254 UTC [4676] LOG:  listening on IPv6 address "::", port 5434
20:04:51 4632 ERROR 2020-09-02 20:04:41.264 UTC [4676] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5434"
20:04:51 4632 ERROR 2020-09-02 20:04:41.285 UTC [4676] LOG:  redirecting log output to logging collector process
20:04:51 4632 ERROR 2020-09-02 20:04:41.285 UTC [4676] HINT:  Future log output will appear in directory "log".
20:04:51 4632 WARN  Postgres logs from "/tmp/node2/log/postgresql-2020-09-02_200441.log":
20:04:51 4632 ERROR 2020-09-02 20:04:41.291 UTC [4678] LOG:  database system was interrupted; last known up at 2020-09-02 20:04:35 UTC
20:04:51 4632 FATAL 2020-09-02 20:04:41.396 UTC [4678] FATAL:  unrecognized recovery parameter "track_functions"
20:04:51 4632 ERROR 2020-09-02 20:04:41.398 UTC [4676] LOG:  startup process (PID 4678) exited with exit code 1
20:04:51 4632 ERROR 2020-09-02 20:04:41.398 UTC [4676] LOG:  aborting startup due to startup process failure
20:04:51 4632 ERROR 2020-09-02 20:04:41.402 UTC [4676] LOG:  database system is shut down
20:04:51 4632 WARN  Failed to start Postgres instance at "/tmp/node2"
20:04:51 4633 ERROR Failed get postmaster pid, file "/tmp/node2/postmaster.pid" does not exists
20:04:51 4633 ERROR Failed to get Postgres pid, see above for details
20:04:51 4633 ERROR Failed to ensure that Postgres is running in "/tmp/node2"
20:04:51 4633 ERROR Failed initialize standby server, see above for details
20:04:51 4633 ERROR Failed to transition from state "wait_standby" to state "catchingup", see above.
20:04:51 4630 ERROR pg_autoctl service node-init exited with exit status 12
......
20:06:14 4630 ERROR pg_autoctl service node-init exited with exit status 12
20:06:14 4630 FATAL pg_autoctl service node-init has already been restarted 5 times in the last 83 seconds, stopping now
20:06:14 4632 ERROR Failed get postmaster pid, file "/tmp/node2/postmaster.pid" does not exists
20:06:14 4632 ERROR Failed to get Postgres pid, see above for details
20:06:14 4632 WARN  Postgres logs from "/tmp/node2/startup.log":
20:06:14 4632 ERROR 2020-09-02 20:06:04.385 UTC [5000] LOG:  listening on IPv4 address "0.0.0.0", port 5434
20:06:14 4632 ERROR 2020-09-02 20:06:04.385 UTC [5000] LOG:  listening on IPv6 address "::", port 5434
20:06:14 4632 ERROR 2020-09-02 20:06:04.394 UTC [5000] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5434"
20:06:14 4632 ERROR 2020-09-02 20:06:04.414 UTC [5000] LOG:  redirecting log output to logging collector process
20:06:14 4632 ERROR 2020-09-02 20:06:04.414 UTC [5000] HINT:  Future log output will appear in directory "log".
20:06:14 4632 WARN  Postgres logs from "/tmp/node2/log/postgresql-2020-09-02_200604.log":
20:06:14 4632 ERROR 2020-09-02 20:06:04.420 UTC [5002] LOG:  database system was interrupted; last known up at 2020-09-02 20:05:58 UTC
20:06:14 4632 FATAL 2020-09-02 20:06:04.496 UTC [5002] FATAL:  unrecognized recovery parameter "track_functions"
20:06:14 4632 ERROR 2020-09-02 20:06:04.498 UTC [5000] LOG:  startup process (PID 5002) exited with exit code 1
20:06:14 4632 ERROR 2020-09-02 20:06:04.498 UTC [5000] LOG:  aborting startup due to startup process failure
20:06:14 4632 ERROR 2020-09-02 20:06:04.500 UTC [5000] LOG:  database system is shut down
20:06:14 4632 WARN  Failed to start Postgres instance at "/tmp/node2"
20:06:14 4632 INFO  Postgres controller service received signal SIGTERM, terminating
20:06:14 4630 FATAL Something went wrong in sub-process supervision, stopping now. See above for details.
20:06:14 4630 INFO  Stop pg_autoctl
```

* inspect recovery.conf file 

```
postgres@c7950c4aaba4:/usr/src/pg_auto_failover$ cat /tmp/node2/recovery.conf 
# Settings by pg_auto_failover
standby_mode = 'on'
primary_conninfo = 'application_name=pgautofailover_standby_2 host=localhost port=5433 user=pgautofailover_replicator sslmode=prefer'
primary_slot_name = 'pgautofailover_standby_2'
recovery_target_timeline = 'latest'

# basic tuning computed by pg_auto_failover
track_functions = pl
shared_buffers = '7989 MB'
work_mem = '24 MB'
maintenance_work_mem = '512 MB'
effective_cache_size = '23 GB'
autovacuum_max_workers = 3
autovacuum_vacuum_scale_factor = 0.08
autovacuum_analyze_scale_factor = 0.02

```


```

**Comment by trecloux** [comment]
More details: on the same vagrant VM, with the same postgresql binary and same pg_auto_failover_binary, test suite is OK, my scenario is not.

**Comment by DimCitus** [comment]
Hi @trecloux ; thanks for using pg_auto_failover and testing the current development branch in advance of the next release. Also you found a bug that is best fixed before said release, so that's great for us!

> * pg_autofailover is generating PostgreSQL tuning parameters.

Oops. Fixed in #388, we will review and merge that internally and update this issue when you can try again.

> * in a container environment, it looks like the postgresql tuning is based on the host resources, not on the container/cgroup limits. Ex `7537 MB` for a container with 1GB memory limit.

We are using [sysinfo](https://man7.org/linux/man-pages/man2/sysinfo.2.html) for getting the host resources, and maybe that's not been made compatible with cgroups. I'm trying to look up if the information is available to a C program through some API, but I'm failing to find it. Do you know how to replace the call to `sysinfo` with something else when running in a Cgroup? How do we figure out we're running in a cgroup?

In the worst case, our numbers are not as helpful as we though they would be, and you will have to provision your own setting after `pg_autoctl create` and before `pg_autoctl run`.

> * `--nodename` parameter was replaced by `--hostname`, this is breaking existing scripts and CLI error message does not mention the new parameter name. It might be interesting to outline this change in the release notes, and/or in the CLI error message.

We go as far as migrating a pre-existing configuration file automatically, but it's true that we didn't implement a command line facility to take care of that. I'm not sure we want to. It's going to be included in the changelog, yes.

**Comment by DimCitus** [comment]
> > * pg_autofailover is generating PostgreSQL tuning parameters.
> 
> Oops. Fixed in #388, we will review and merge that internally and update this issue when you can try again.

Now that the fix has been merged, feel free to try again!

> > * `--nodename` parameter was replaced by `--hostname`, this is breaking existing scripts and CLI error message does not mention the new parameter name. It might be interesting to outline this change in the release notes, and/or in the CLI error message.
> 
> We go as far as migrating a pre-existing configuration file automatically, but it's true that we didn't implement a command line facility to take care of that. I'm not sure we want to. It's going to be included in the changelog, yes.

The work-in-progress changelog can be seen at https://github.com/citusdata/pg_auto_failover/blob/release/1.4.0/CHANGELOG.md ; feedback welcome!

**Comment by trecloux** [comment]
> Now that the fix has been merged, feel free to try again!

The fix solved the issue, good job ;-) 

You confirm that the tuning options were not generated in the test suite, that's why you did to detect the issue ?

> The work-in-progress changelog can be seen at https://github.com/citusdata/pg_auto_failover/blob/release/1.4.0/CHANGELOG.md ; feedback welcome!

Perfect.

**Comment by trecloux** [comment]
> We are using [sysinfo](https://man7.org/linux/man-pages/man2/sysinfo.2.html) for getting the host resources, and maybe that's not been made compatible with cgroups. I'm trying to look up if the information is available to a C program through some API, but I'm failing to find it. Do you know how to replace the call to `sysinfo` with something else when running in a Cgroup? How do we figure out we're running in a cgroup?

I will look for the answers and post my findings here.
> In the worst case, our numbers are not as helpful as we though they would be, and you will have to provision your own setting after `pg_autoctl create` and before `pg_autoctl run`.
> 
> > * `--nodename` parameter was replaced by `--hostname`, this is breaking existing scripts and CLI error message does not mention the new parameter name. It might be interesting to outline this change in the release notes, and/or in the CLI error message.
> 
> We go as far as migrating a pre-existing configuration file automatically, but it's true that we didn't implement a command line facility to take care of that. I'm not sure we want to. It's going to be included in the changelog, yes.

**Comment by DimCitus** [comment]
> You confirm that the tuning options were not generated in the test suite, that's why you did to detect the issue ?

Exactly, that's what happened. Our docker/Travis environment is not suited to run many Postgres instances at the same time when each of them is requiring 1/4th of the available RAM, so the tuning is discarded in the test environment. The old way to discard it was to refrain from installing any tuning at all, the new way of discarding it consists of installing our tuning with mostly Postgres default values, so that the single docker image is able to run several Postgres instances, and still we test the full config editing.

**Comment by s4ke** [comment]
I will hop in here as well as we are automating things as well at https://github.com/neuroforgede/pg_auto_failover_ansible and we will need to update our scripts as well to be ready for 1.4

> As of pg_autoctl 1.4 Postgres is running only when pg_autoctl is running. This simplifies systemd integration and allows a better upgrade process. It also makes pg_autoctl easier to run in containers.

So if I read this correctly, the proper way to restart postgres as of 1.4 is to restart the systemd service. But if I remember correctly, to reload the postgres settings in conf files we still have to run `pg_ctl reload`?

**Comment by DimCitus** [comment]
Hi @s4ke ; nice to see an Ansible integration project for pg_auto_failover, thanks!

So it seems you have several question here:

  1. reload Postgres: you can `pg_autoctl reload` and the SIGHUP signal will be relayed down to the Postgres instance
  2. restart Postgres: if you stop Postgres with `pg_ctl stop` it will be restarted within 100ms by the pg_autoctl postgres controller sub-process... you could also use `PG_AUTOCTL_DEBUG=1 pg_autoctl do service restart postgres` and it's going to do the same thing for you (stop Postgres and let the controller start it again within 100ms)
  3. the upgrade script we're working on is going to install default node names for you, and keep the current hostname, so you don't have to take care of that yourself, it's all included

Finally a note about the systemd service. Because it's using cgroups when you restart the pgautofailover systemd unit this would restart both pg_autoctl and Postgres when using 1.3. Now that we have a single process tree, it makes sense that this would be the case, and we can also restart the “node-active” sub-process of pg_autoctl without having to restart Postgres.

**Comment by s4ke** [comment]
Hey @DimCitus , no problem, but tbh, we have to thank you guys for an easy to setup HA solution for PostgreSQL!

Thanks for your quick feedback :)

From what I gather, we are basically already doing everything correctly in https://github.com/neuroforgede/pg_auto_failover_ansible/blob/master/roles/postgres-cluster-configure/tasks/restart_postgres.yml then. Good to know.

**Comment by DimCitus** [comment]
Closing this issue now. We won't have the cgroup resource changes in 1.4.0, you might want to open a new issue about only this point and we might be able to fix it later. We did fix the bug reported though (recovery setting files no longer including tuning bits), and the `--nodename` has now been made obvious in the release notes.
