### ISSUE TITLE
Adding a standby while another is in maintenance is not possible and cannot be killed by ctrl+C

### ISSUE THREAD

**Issue by JelteF** [citusdata/pg_auto_failover#392]
Setup:
```bash
pg_autoctl create postgres --pgdata node1 --run
pg_autoctl create postgres --pgdata node2 --run
pg_autoctl enable maintenance --pgdata node2 
```

Then this command fails continously and cannot be killed by ctrl+c anymore

```
pg_autoctl create postgres --pgdata node3
```
Output:
```
^C15:08:02 500 INFO  pg_autoctl received signal SIGINT, terminating
15:08:02 500 ERROR Failed to send signal Interrupt to service postgres with pid 505
15:08:02 506 ERROR Monitor ERROR:  primary node 172.28.149.103:5501 is already in state wait_primary
15:08:02 506 ERROR Monitor HINT:  Retry registering in a moment
15:08:02 506 ERROR SQL query: SELECT * FROM pgautofailover.register_node($1, $2, $3, $4, $5, $6, $7, $8::pgautofailover.replication_state, $9, $10, $11)
15:08:02 506 ERROR SQL params: 'default', '172.28.149.103', '5503', 'postgres', '', '6868238261832629440', '-1', 'init', 'standalone', '50', 'true'
15:08:02 506 WARN  Failed to register node 172.28.149.103:5503 in group -1 of formation "default" with initial state "init" because the monitor is already registering another standby, retrying in 1s
```

Current cluster state
```

  Name |  Node |           Host:Port |       LSN | Reachable |       Current State |      Assigned State
-------+-------+---------------------+-----------+-----------+---------------------+--------------------
node_1 |     1 | 172.28.149.103:5501 | 0/3000728 |       yes |        wait_primary |        wait_primary
node_2 |     2 | 172.28.149.103:5502 | 0/3000728 |       yes |         maintenance |         maintenance
```

**Comment by JelteF** [comment]
It would of course be best if it would allow a node to be added while another is in maintenance. I understand this might be problematic, because it could cause weird edge cases. The command should at least be able to be killed though.

**Comment by DimCitus** [comment]
We should allow the registration of a new standby in that state, I can't see what's getting in the way there (other than the current implementation that's a little too restrictive for its own good). 

The general case is there to make sure that the primary has had enough time to prepare the HBA entries, and really, we could lift the limitation about only one standby at a time now that we edit the HBA eagerly, but we still have the race condition that the primary reports having added all the standbys and then it missed one.

That said the worst case is that the standby fails to connect to the primary, waits for a while, and tries again, and now it works. So I'm thinking maybe we should also relax this and allow new standby to register at any time as long as the primary is either SINGLE, PRIMARY, or JOIN_PRIMARY.

**Comment by JelteF** [comment]
I think even if the behaviour is allowed, the Ctrl+C issue should be investigated as well. Maybe this can pop up in other cases too.

**Comment by DimCitus** [comment]
Ah yes, indeed. That's fixed in https://github.com/citusdata/pg_auto_failover/pull/387/files#diff-a91ed5bd9f887151af724a24c5977aa2 with using `pselect` and the atomic block/unblock signals dance, but only for the main keeper loop, not for the other call sites yet.

The main problem is that `select` with a timeout has a race condition with the signal handling functions, so it's not reliable.
