### ISSUE TITLE
is it possible to support logical replication?

### ISSUE THREAD

**Issue by thomasdba** [citusdata/pg_auto_failover#400]
If failover happened ,then monitor can make down stream follow the new master .
or any suggestion for streaming replication and logical replication work together .

**Comment by DimCitus** [comment]
Hi @thomasdba ; thanks for your interest in pg_auto_failover. At the moment Postgres itself does not provide with any way to support failover for logical replication slots, so I'm not sure what you would expect that we do in pg_auto_failover to automate logical replication support?

**Comment by thomasdba** [comment]
@DimCitus Sorry ,I'm not familiar with logical replication ,but no solution to support both physical and logical replication at the same time ?
Thanks !

**Comment by DimCitus** [comment]
This article explains the situation in more details: https://www.percona.com/blog/2020/05/21/failover-of-logical-replication-slots-in-postgresql/, and this one too: https://www.2ndquadrant.com/en/blog/failover-slots-postgresql/.
