### ISSUE TITLE
Placeholder ticket for v13 compatible release

### ISSUE THREAD

**Issue by devrimgunduz** [citusdata/pg_auto_failover#401]
Hi,

I see that v13 support is in the git repo. This is a placeholder ticket for a new release. We need that for building native packages.

Regards, Devrim

**Comment by DimCitus** [comment]
Hi @devrimgunduz ; thanks for this ticket. Please see https://github.com/citusdata/pg_auto_failover/milestone/8 if you want to follow along what's remaining to be done before release. We're almost there!

**Comment by DimCitus** [comment]
See https://github.com/citusdata/pg_auto_failover/releases/tag/v1.4.0
