### ISSUE TITLE
Where did the --group parameter go?

### ISSUE THREAD

**Issue by s4ke** [citusdata/pg_auto_failover#416]
Hey,

when checking what our Ansible scripts do not implement yet, I came across the issue that `--group` is missing on `pg_autoctl create postgres` even though the docs state it is supported.

![image](https://user-images.githubusercontent.com/719760/93852979-4d08f680-fcb3-11ea-8df8-11a6213a430e.png)

Version information: 

![image](https://user-images.githubusercontent.com/719760/93853914-0d430e80-fcb5-11ea-9972-40b74a0128e2.png)

![image](https://user-images.githubusercontent.com/719760/93853950-2481fc00-fcb5-11ea-9093-d0995fa5e701.png)

**Comment by s4ke** [comment]
Also https://readthedocs.org/projects/pg-auto-failover/downloads/pdf/latest/ is the uppermost hit on google and states it is the documentation for 1.3.1 but I dont think that is correct judging from all the extra command line options I have never seen (and are not supported on my installation)

**Comment by DimCitus** [comment]
The documentation is confused then, the `--group` option should not be there. Will review and fix, thanks!
About the PDF, we didn't upgrade all the version numbers and the hooking with readthedocs might be unfortunate at this moment given our development workflow is different from what they assume.

**Comment by s4ke** [comment]
Ah okay. How do we set the group of a server at creation time, then?

**Comment by DimCitus** [comment]
When using standalone Postgres you can't, there's only one group per formation, and that's group zero. That's it. That's why the option is not supported. It's useful with Citus support where you can have many groups (one group per worker) in a single formation, as covered in the docs at https://pg-auto-failover.readthedocs.io/en/latest/architecture.html#group.

**Comment by s4ke** [comment]
Ah, this makes sense. Thanks for the input. I will probably come back and ask you more questions about that in the future then, once Citus support is hitting our repository https://github.com/neuroforgede/pg_auto_failover_ansible/issues/6

**Comment by s4ke** [comment]
I think this can be closed for now.
