### ISSUE TITLE
Why can't I use asynchronous streaming replication?

### ISSUE THREAD

**Issue by MichaelDBA** [citusdata/pg_auto_failover#424]
I haven't used pg_auto_failover in a while (v 1.3), but I was wondering if this tool still requires replicas to be in synchronous replication mode, not asynchronous?  I do not want my commits to be dependent on acknowledgements from standbys.

**Comment by DimCitus** [comment]
Hi @MichaelDBA ; we are cooking the packages for version 1.4.0, the GitHub release (source form) is available already at https://github.com/citusdata/pg_auto_failover/releases/tag/v1.4.0. In this version, you can change the replication quorum property of every node and decide if you're using synchronous or asynchronous replication by default that way. It's all documented at https://pg-auto-failover.readthedocs.io/en/latest/architecture.html#synchronous-vs-asynchronous-replication and then https://pg-auto-failover.readthedocs.io/en/latest/architecture-multi-standby.html#replication-quorum.
