### ISSUE TITLE
The monitor node can only be built from scratch again

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#428]
I suggest to automate actions on case `The monitor node can only be built from scratch again`
```diff
diff --git a/src/bin/pg_autoctl/monitor.c b/src/bin/pg_autoctl/monitor.c
index b8483de..1962810 100644
--- a/src/bin/pg_autoctl/monitor.c
+++ b/src/bin/pg_autoctl/monitor.c
@@ -890,6 +890,9 @@ monitor_node_active(Monitor *monitor,
                                  "see previous lines for details",
                                  nodeId, groupId, formation, nodeStateString,
                                  pgsrSyncState, currentLSN);
+               if (!strncmp(parseContext.sqlstate, "FNDNT", sizeof("FNDNT") - 1)) {
+                       exit(EXIT_CODE_MONITOR);
+               }
                return false;
        }
 
diff --git a/src/bin/pg_autoctl/pgsql.c b/src/bin/pg_autoctl/pgsql.c
index c4f2b42..b7b12c2 100644
--- a/src/bin/pg_autoctl/pgsql.c
+++ b/src/bin/pg_autoctl/pgsql.c
@@ -856,6 +856,11 @@ pgsql_execute_with_params(PGSQL *pgsql, const char *sql, int paramCount,
                for (lineNumber = 0; lineNumber < lineCount; lineNumber++)
                {
                        log_error("%s %s", prefix, errorLines[lineNumber]);
+                       if (context && !strncmp(errorLines[lineNumber], "ERROR:  couldn't find node with nodeid ", sizeof("ERROR:  couldn't find node with nodeid ") - 1)) {
+                               AbstractResultContext *ctx = (AbstractResultContext *) context;
+                               strlcpy(ctx->sqlstate, "FNDNT", SQLSTATE_LENGTH);
+                               sqlstate = NULL;
+                       }
                }
 
                log_error("SQL query: %s", sql);
```
this exit keeper on ERROR:  couldn't find node with nodeid
then in start script may write
```sh
# if in monitor there is not current node
if [ "$(pg_autoctl show state --group "$(pg_autoctl config get pg_autoctl.group)" --formation "$(pg_autoctl config get pg_autoctl.formation)" | grep "$(hostname)" | wc -l)" -eq "0" ]; then

    # drop node ignores connection error to the monitor, and stops Postgres
    $ pg_autoctl drop node

    # register again, and restart Postgres on the node
    $ pg_autoctl create postgres --monitor <new monitor uri> <--same options --as the --first time>

fi

# run keeper
pg_autoctl run
```

but instead exit and use such script is better do drop and create in c-code

**Comment by DimCitus** [comment]
This is a good idea in principle, and I also want to allow for a monitor's “discovery“ mode where nodes can register themselves again when the monitor has “forgotten” about them. In most cases this approach could be fine. I would implement it in a different way, with the whole discovery protocol in C with a new API on the monitor that we could use in the client code.

There are some complex cases though. Imagine losing the primary, after 30 seconds the monitor fails over to the secondary, and now the monitor is lost too. A new monitor is made available, without data. The old primary is available again now, VM reboots or something. We have two primaries in the group: split brain! That's the worse that can happen.

As I didn't find a design that would allow preventing that situation in all cases, we didn't implement this idea yet. There are other ways to implement resilience for the monitor node (which is a SPOF). Simplest might be to allow for a monitor's secondary server and manual failover. Maybe some kind of integrated Disaster Recovery for the monitor would be a good option too. Some people are trying to imagine an implementation that would support a consensus driven monitor implementation using RAFT or another approved protocol (Paxos).

**Comment by RekGRpth** [comment]
How about made monitor not in postgres, but in distributed storage like etcd?
