### ISSUE TITLE
What do if host with monitor and primary is broken?

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#429]
What do if host with monitor and primary is broken?
I have 5 hardware servers.
On first I run monitor, on others - keepers.
When host with monitor and host with primary are broken, what I do?

**Comment by DimCitus** [comment]
At the moment pg_auto_failover is resilient to losing either the primary or the monitor, but not to losing both nodes at once. We intend on fixing that in a later release.
