### ISSUE TITLE
Do patch upgrades to pg_auto_failover require special care?

### ISSUE THREAD

**Issue by s4ke** [citusdata/pg_auto_failover#433]
I know that upgrades for minor versions (e.g. 1.3 to 1.4, 1.4 to 1.5) require following the procedure described in the docs, but I am wondering if that also applies to patch upgrades. If yes, I guess pinning versions in apt would be good idea, right?

EDIT: I guess it comes down to whether a monitor with e.g. 1.4.1 will work properly with a data node with 1.4.0 or vice versa.

**Comment by DimCitus** [comment]
So at the moment what we do in pg_auto_failover is that the first two digits are the version number for the extension's schema, and then the third digit is used as a patch version number. When the schema changes on the monitor, then we will version it 1.5 and this requires a full restart of the monitor to apply the extension upgrade script. 

In a patch release such as 1.4.0 to 1.4.1 we would only include “code” fixes, not SQL schema fixes. If the monitor code had bug fixes, then restarting the monitor is necessary. If the node-active “keeper” code had bug fixes, then restart the pg_autoctl process on the Postgres nodes is necessary too. This can be done without restarting Postgres, though it won't be auto-detected as when doing a schema upgrade on the monitor, so you might want to use the DEBUG commands to make it happen:

```
$ PG_AUTOCTL_DEBUG=1 pg_autoctl do service restart node-active
```

**Comment by s4ke** [comment]
This answers my question. I will close this issue.
