### ISSUE TITLE
Monitor has to be restarted twice to trigger upgrade from 1.3 to 1.4

### ISSUE THREAD

**Issue by s4ke** [citusdata/pg_auto_failover#434]
In our tests for upgrading automatically from 1.3 to 1.4 we found that we had to restart the monitor service twice after upgrading the libraries before it triggered the upgrade from 1.3 to 1.4.

This is the procedure we are using:

https://github.com/neuroforgede/pg_auto_failover_ansible/blob/master/roles/postgres-cluster-pg-auto-failover-upgrade-pre-1.4/tasks/upgrade.yml

If we leave out lines 73-77, the monitor does not trigger an upgrade. I was able to reproduce this multiple times. Once those lines are removed, I have to trigger the failover manually so that the step in lines 82-110 is completed.

The tests in question can be found here and require Vagrant:

https://github.com/neuroforgede/pg_auto_failover_ansible/tree/master/test/upgrade_1.3_to_1.4

EDIT:

one more thing: The docs state that we should watch for "ALTER EXTENSION pgautofailover UPDATE TO" in the logs, but at least for me when upgrading from 1.3 to 1.4 this did not show up.

**Comment by JelteF** [comment]
So the flow that should be possible to use to upgrade pg_auto_failover from 1.3 to 1.4 is documented here:
https://pg-auto-failover.readthedocs.io/en/latest/operations.html#upgrading-from-previous-pg-auto-failover-versions

These steps assume a systemd managed `pg_autoctl` process. If it's not managed by systemd on the monitor you should also stop the postgres process, not just `pg_autoctl`. 

As you can see [in the section above](https://pg-auto-failover.readthedocs.io/en/latest/operations.html#upgrading-pg-auto-failover-from-versions-1-4-onwward) the upgrade flow for future versions should be much more straightforward.

**Comment by s4ke** [comment]
We are provisioning the monitor node with a sytemd service like this:

```
- name: "create systemd config for cluster"
  shell: >
    su -c 'PATH="$PATH:{{ postgresql_cluster_bin_path }}" pg_autoctl -q show systemd --pgdata "{{ postgresql_cluster_data_dir }}"' postgres \
    | tee /etc/systemd/system/{{ postgresql_cluster_daemon }}.service
  when: (not pgdata_dir_version.stat.exists) and (postgresql_cluster_is_monitor | default('False') | bool)
```

This generates something similar to this (postgresql_main_cluster.service):

```
[Unit]
Description = pg_auto_failover

[Service]
WorkingDirectory = /home/postgres
Environment = 'PGDATA=/var/lib/postgresql/12/main_cluster/'
User = postgres
ExecStart = /usr/bin/pg_autoctl run
Restart = always
StartLimitBurst = 0

[Install]
WantedBy = multi-user.target                                
```

As I said, we need to restart this service twice and not once as the documentation states. Also I don't see anything in the logs that is described here:

![image](https://user-images.githubusercontent.com/719760/94549835-14d55b00-0253-11eb-9e42-31e1a97a9326.png)

**Comment by DimCitus** [comment]
Yeah it's better to check the extension version on the Postgres database, or the output of `pg_autoctl version --json` maybe, although that does not actually report the current installed version (we could fix that). We made the log line a `log_debug` now, so either we have to make it a `log_info` again, or change the docs.

**Comment by s4ke** [comment]
Okay, sounds good. @JelteF it should be correct how i created the service, right?

If yes, this should be probably added to the docs that you might have to restart the monitor twice when upgrading from 1.3 to 1.4. It is not "pretty", but I don't see any real downsides if people properly check the installed version with the psql query I posted above.

**Comment by JelteF** [comment]
yeah the way you create the service looks fine.

And yeah please make a docs PR. I don't think it's worth the effort to find out why this happens if this simple solution works. Mostly because it's the legacy upgrade flow and the new one likely doesn't have this issue.

**Comment by DimCitus** [comment]
I think that the need to restart twice comes from the following:
  1. in 1.3.1 the process `postgres` and `pg_autoctl` are separate, when you stop `pg_autoctl` then Postgres is still running
  2. then you upgrade to 1.4.0 and start `pg_autoctl` and Postgres is running, it will happily take it from there and won't restart it
  3. you stop `pg_autoctl` and this stops Postgres
  4. you restart `pg_autoctl` and this starts Postgres as a sub-process and it's all fine now.

Can you relate to that? is that what's happening for you?

We might want to force the monitor's Postgres instance to run as a sub-process of pg_autoctl: that is, ensure it's stopped early in the startup process of `pg_autoctl` so that we start it later as a sub-process.

**Comment by s4ke** [comment]
After upgrading before any restart:

![image](https://user-images.githubusercontent.com/719760/94795865-40388100-03de-11eb-9616-72d7728d2547.png)

After the first restart:

![image](https://user-images.githubusercontent.com/719760/94795940-5d6d4f80-03de-11eb-8378-ad415cb32d8e.png)

After the second restart:

![image](https://user-images.githubusercontent.com/719760/94796001-7249e300-03de-11eb-8b8e-0ada637b86b2.png)

So, yes. What you described looks like what is happening.
