### ISSUE TITLE
Execute command on state change

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#440]
How about to add some options into keeper config to execute some commands on every state change? 
(Instead listen channel `state`)

**Comment by RekGRpth** [comment]
For example, it may update pgbouncer config

**Comment by RekGRpth** [comment]
I solved it by using [pglisten](https://github.com/RekGRpth/pgsidekick)
```sh
pglisten --listen=state --conninfo="$(pg_autoctl show uri --monitor)" | jq --unbuffered --raw-output "select(.formation == \""$(pg_autoctl config get pg_autoctl.formation)"\" and .groupId == $(pg_autoctl config get pg_autoctl.group) and .health == \"good\" and .reportedState == \"primary\" and .goalState == \"primary\") | {host:.host, port:.port} | join(\" \")" | while read -r HOST PORT; do
    echo "* = host=$HOST port=$PORT" >"$HOME/databases.ini"
    sv reload pgbouncer
done
```
but it seems very bad, because it establish extra connection to monitor from each keeper (although each keeper connect to monitor already)

**Comment by DimCitus** [comment]
When we implement support for pgbouncer in pg_autoctl directly, it will most certainly use its own connection to the monitor and the notifications like you did. The only bit you're missing now is the “cache invalidation” part. You should have a way of producing the pgbouncer setup from scratch when you start the `pglisten` program, and ideally, that reset step should happen between the LISTEN command and processing the first notification.

**Comment by DimCitus** [comment]
Other than that I'm not sure about including a generic facility in `pg_autoctl` for hooks and extra command. I'm mostly worried about robustness and simplicity here. My experience with for example the `archive_command` setting in Postgres is that you can't have something that is that flexible and still is simple and robust. I'd rather include the features we need in the tool itself and make it simple on the users, and ensure we implement proper error handling.

**Comment by RekGRpth** [comment]
You may see how it done in repmgr

**Comment by DimCitus** [comment]
> You may see how it done in repmgr

  - do you have a link to the docs with a particular section of paragraph that I should review?
  - how do they prevent a failover from failing because the external script that is run in a hook is failing, or worse, taking a very long time, stuck somewhere?

**Comment by RekGRpth** [comment]
> how do they prevent a failover from failing because the external script that is run in a hook is failing, or worse, taking a very long time, stuck somewhere?

It needs to investigate their code
