### ISSUE TITLE
Multi-standby: Removing a standby doesn't update synchronous_standby_names on primary

### ISSUE THREAD

**Issue by rheaton** [citusdata/pg_auto_failover#445]
When there are at least 2 standby nodes, the following scenario can be created:

## Version
Master: db44bcb2feed71ceda746f5be348d62cbd93939c

## Summary
When we have a multi-standby setup, and we drop a standby from the cluster with `pg_autoctl drop node` does not update the` synchronous_standby_names` GUC on the primary to exclude the dropped standby. This can lead to situations where transactions can get stuck on the primary.

## Repro
1. Create a cluster with one primary and 3 standbys (default `replication_quorum` and `candidate_priority` )
1. `pg_autoctl set formation number-sync-standbys 2 --pgdata ~/failover/monitor/` 
1. On the primary:
```
postgres=# show synchronous_standby_names ;
               synchronous_standby_names                
--------------------------------------------------------------------------------------
 ANY 2 (pgautofailover_standby_2, pgautofailover_standby_3, pgautofailover_standby_4)
(1 row)
```
1. Let’s drop *two* of the standbys using `pg_autoctl drop node --destroy`
1. On the primary we can see that synchronous_standby_names has not been updated:
```
postgres=# show synchronous_standby_names ;
               synchronous_standby_names                
--------------------------------------------------------------------------------------
 ANY 2 (pgautofailover_standby_2, pgautofailover_standby_3, pgautofailover_standby_4)
(1 row)
```
 6. As a consequence transactions hang on the primary.

Branch with a failing test, illustrating the scenario: https://github.com/citusdata/pg_auto_failover/compare/master...rheaton:synchronous-standby-names-primary?expand=1

**Comment by DimCitus** [comment]
Hi @rheaton ; I think what you're reporting is that is works as designed. Please review https://pg-auto-failover.readthedocs.io/en/latest/architecture-multi-standby.html ; for the `synchronous_standby_names` to be allowed empty when losing standby nodes you need `number_sync_standby` to be zero.

**Comment by rheaton** [comment]
## Response

Thanks, Dmitri! I checked out the documentation, but I still have a few questions and another scenario that seems odd to me.


### Questions
1. Should we allow someone to remove a standby using `pg_autoctl drop node` if they set `number_sync_standby > 0` and
it would potentially (or definitely) stop writes to primary?
Since we don't allow setting `number_sync_standby` when they don't have enough nodes, a companion error when attempting to drop
a node may be helpful. It's possible this could be a situation that someone would want, but I yet don't know enough to say. :)

2. Removing a node updates the `synchronous_standby_names` on the monitor, but it isn't propagated to the primary. This is
true even when we haven't set `number_sync_standby` and switched from availability to durability.

If we run a primary with 3 secondaries, and drop one
```bash
mkdir -p /failover
pg_autoctl create monitor --pgport 7800 --auth trust --pgdata /failover/monitor -v --no-ssl --hostname 127.0.0.1 --run
pg_autoctl create postgres --pgdata /failover/primary --pgport=8800 --monitor postgres://autoctl_node@127.0.0.1:7800/pg_auto_failover?sslmode=prefer --auth trust --no-ssl --hostname 127.0.0.1 --run --pgctl=/usr/local/bin/pg_ctl
pg_autoctl create postgres --pgdata /failover/secondary0 --pgport=9800 --monitor postgres://autoctl_node@127.0.0.1:7800/pg_auto_failover?sslmode=prefer --auth trust --no-ssl --hostname 127.0.0.1 --run --pgctl=/usr/local/bin/pg_ctl
pg_autoctl create postgres --pgdata /failover/secondary1 --pgport=9801 --monitor postgres://autoctl_node@127.0.0.1:7800/pg_auto_failover?sslmode=prefer --auth trust --no-ssl --hostname 127.0.0.1 --run --pgctl=/usr/local/bin/pg_ctl
pg_autoctl create postgres --pgdata /failover/secondary2 --pgport=9802 --monitor postgres://autoctl_node@127.0.0.1:7800/pg_auto_failover?sslmode=prefer --auth trust --no-ssl --hostname 127.0.0.1 --run --pgctl=/usr/local/bin/pg_ctl
```

Drop a standby node
```bash
pg_autoctl drop node --pgdata /failover/secondary2 --destroy
```

Connect to the primary & get synchronous_standby_names
```bash
psql -p 8800 postgres
select current_setting('synchronous_standby_names');
```
returns
`ANY 1 (pgautofailover_standby_1, pgautofailover_standby_2, pgautofailover_standby_3)`

Run the CLI to get the standby names (on primary, monitor, etc.)
```bash
pg_autoctl show standby-names --pgdata=/failover/primary/
```
returns
`ANY 1 (pgautofailover_standby_1, pgautofailover_standby_2)`

These don't match up, because the monitor was updated when the node was dropped, but that was not propagated to the primary. Is this behavior intended?

**Comment by DimCitus** [comment]
Let's dive into the topic then!

> 1. Should we allow someone to remove a standby using `pg_autoctl drop node` if they set `number_sync_standby > 0` and
>    it would potentially (or definitely) stop writes to primary?
>    Since we don't allow setting `number_sync_standby` when they don't have enough nodes, a companion error when attempting to drop
>    a node may be helpful. It's possible this could be a situation that someone would want, but I yet don't know enough to say. :)

We consider that it should always be possible to drop a node at anytime. After all, a node might be dead and we don't know about it, and worst case, the Group FSM on the monitor could be stuck because of that. So we want to allow for `pg_autoctl drop node` to always be a possible action, and go to some lengths to ensure it is.

Also see https://github.com/citusdata/pg_auto_failover/blob/master/tests/test_multi_standbys.py#L129 for a test case that shows that we decrement `number_sync_standby` when a node is dropped.

> 2. Removing a node updates the `synchronous_standby_names` on the monitor, but it isn't propagated to the primary. This is
>    true even when we haven't set `number_sync_standby` and switched from availability to durability.

I think you just found a bug, congrats thanks! Do you want to see about fixing it? It might be that just adding some code to assign APPLY_SETTINGS to the primary when reaching code line at https://github.com/citusdata/pg_auto_failover/blob/master/src/monitor/node_active_protocol.c#L1104 is all that's needed.

For a proper PR, adding a test for the actual `synchronous_standby_names` settings on the primary node will be necessary too, of course. Maybe at the same place where we test the decrementing of it?

**Comment by rheaton** [comment]
@DimCitus Does this PR cover what you were asking about? https://github.com/citusdata/pg_auto_failover/pull/446 If not, we can adapt it :)

**Comment by DimCitus** [comment]
> @DimCitus Does this PR cover what you were asking about? #446 If not, we can adapt it :)

Just published a review there. And just understood that I missed the point entirely from the beginning, thanks for your patience walking me through the actual problem here!

**Comment by DimCitus** [comment]
I think finally #480 fixes it, with a mix of your early work and some more tweaks to it, and with your test case kept as it was.
