### ISSUE TITLE
Second node creation fails because of pg_hba issue

### ISSUE THREAD

**Issue by kevinelliott** [citusdata/pg_auto_failover#452]
Setting up the monitor on the monitor host has no problems:

```
postgres@db1-monitor:~$ pg_autoctl create monitor --ssl-self-signed --hostname db1-monitor.int --auth trust --run  --pgctl /usr/lib/postgresql/12/bin/pg_ctl 
18:07:16 5828 INFO  Using default --ssl-mode "require"
18:07:16 5828 INFO  Using --ssl-self-signed: pg_autoctl will create self-signed certificates, allowing for encrypted network traffic
18:07:16 5828 WARN  Self-signed certificates provide protection against eavesdropping; this setup does NOT protect against Man-In-The-Middle attacks nor Impersonation attacks.
18:07:16 5828 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details
18:07:16 5828 INFO  Initialising a PostgreSQL cluster at "./monitor"
18:07:16 5828 INFO  /usr/lib/postgresql/12/bin/pg_ctl initdb -s -D ./monitor --option '--auth=trust'
18:07:17 5828 INFO   /usr/bin/openssl req -new -x509 -days 365 -nodes -text -out /var/lib/postgresql/monitor/server.crt -keyout /var/lib/postgresql/monitor/server.key -subj "/CN=db1-monitor.int"
18:07:17 5828 INFO  Started pg_autoctl postgres service with pid 5848
18:07:17 5828 INFO  Started pg_autoctl listener service with pid 5849
18:07:17 5848 INFO   /usr/bin/pg_autoctl do service postgres --pgdata ./monitor -v
18:07:17 5854 INFO   /usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/monitor -p 5000 -h *
18:07:17 5848 INFO  Postgres is now serving PGDATA "/var/lib/postgresql/monitor" on port 5000 with pid 5854
18:07:17 5849 WARN  NOTICE:  installing required extension "btree_gist"
18:07:17 5849 INFO  Granting connection privileges on 10.116.0.0/20
18:07:17 5849 INFO  Your pg_auto_failover monitor instance is now ready on port 5000.
18:07:17 5849 INFO  Monitor has been successfully initialized.
18:07:17 5849 INFO   /usr/bin/pg_autoctl do service listener --pgdata ./monitor -v
18:07:17 5849 INFO  Managing the monitor at postgres://autoctl_node@db1-monitor.int:5000/pg_auto_failover?sslmode=require
18:07:17 5849 INFO  Reloaded the new configuration from "/var/lib/postgresql/.config/pg_autoctl/var/lib/postgresql/monitor/pg_autoctl.cfg"
18:07:17 5849 INFO  Contacting the monitor to LISTEN to its events.
```

Setting up the first node has no problems:

```
postgres@db1-node1:~$ pg_autoctl create postgres --hostname db1-node1.int --auth trust --ssl-self-signed --monitor 'postgres://autoctl_node@db1-monitor.int:5000/pg_auto_failover?sslmode=require' --run --pgctl /usr/lib/postgresql/12/bin/pg_ctl 
18:08:17 13589 INFO  Using default --ssl-mode "require"
18:08:17 13589 INFO  Using --ssl-self-signed: pg_autoctl will create self-signed certificates, allowing for encrypted network traffic
18:08:17 13589 WARN  Self-signed certificates provide protection against eavesdropping; this setup does NOT protect against Man-In-The-Middle attacks nor Impersonation attacks.
18:08:17 13589 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details
18:08:17 13589 INFO  Started pg_autoctl postgres service with pid 13591
18:08:17 13591 INFO   /usr/bin/pg_autoctl do service postgres --pgdata ./db1-node1 -v
18:08:17 13589 INFO  Started pg_autoctl node-active service with pid 13592
18:08:17 13592 INFO  Registered node 2 (db1-node1.int:5001) with name "node_2" in formation "default", group 0, state "single"
18:08:17 13592 INFO  Writing keeper state file at "/var/lib/postgresql/.local/share/pg_autoctl/var/lib/postgresql/db1-node1/pg_autoctl.state"
18:08:17 13592 INFO  Writing keeper init state file at "/var/lib/postgresql/.local/share/pg_autoctl/var/lib/postgresql/db1-node1/pg_autoctl.init"
18:08:17 13592 INFO  Successfully registered as "single" to the monitor.
18:08:17 13592 INFO  FSM transition from "init" to "single": Start as a single node
18:08:17 13592 INFO  Initialising postgres as a primary
18:08:17 13592 INFO  Initialising a PostgreSQL cluster at "./db1-node1"
18:08:17 13592 INFO  /usr/lib/postgresql/12/bin/pg_ctl initdb -s -D ./db1-node1 --option '--auth=trust'
18:08:18 13592 INFO   /usr/bin/openssl req -new -x509 -days 365 -nodes -text -out /var/lib/postgresql/db1-node1/server.crt -keyout /var/lib/postgresql/db1-node1/server.key -subj "/CN=db1-node1.int"
18:08:18 13618 INFO   /usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/db1-node1 -p 5001 -h *
18:08:18 13592 INFO  CREATE DATABASE postgres;
18:08:18 13592 INFO  The database "postgres" already exists, skipping.
18:08:18 13591 INFO  Postgres is now serving PGDATA "/var/lib/postgresql/db1-node1" on port 5001 with pid 13618
18:08:18 13592 INFO  CREATE EXTENSION pg_stat_statements;
18:08:18 13592 INFO  Contents of "/var/lib/postgresql/db1-node1/postgresql-auto-failover.conf" have changed, overwriting
18:08:18 13592 INFO  Transition complete: current state is now "single"
18:08:18 13592 INFO  keeper has been successfully initialized.
18:08:18 13592 INFO   /usr/bin/pg_autoctl do service node-active --pgdata ./db1-node1 -v
18:08:18 13592 INFO  Reloaded the new configuration from "/var/lib/postgresql/.config/pg_autoctl/var/lib/postgresql/db1-node1/pg_autoctl.cfg"
18:08:18 13592 INFO  pg_autoctl service is running, current state is "single"
```

When trying to add a second node:

```
postgres@db1-node2:~$ pg_autoctl create postgres --hostname db1-node2.int --auth trust --ssl-self-signed --monitor 'postgres://autoctl_node@db1-monitor.int:5000/pg_auto_failover?sslmode=require' --run --pgctl /usr/lib/postgresql/12/bin/pg_ctl
```

The following errors arise:

```
18:08:57 1419 INFO  Using default --ssl-mode "require"
18:08:57 1419 INFO  Using --ssl-self-signed: pg_autoctl will create self-signed certificates, allowing for encrypted network traffic
18:08:57 1419 WARN  Self-signed certificates provide protection against eavesdropping; this setup does NOT protect against Man-In-The-Middle attacks nor Impersonation attacks.
18:08:57 1419 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details
18:08:57 1419 INFO  Started pg_autoctl postgres service with pid 1422
18:08:57 1422 INFO   /usr/bin/pg_autoctl do service postgres --pgdata ./db1-node2 -v
18:08:57 1419 INFO  Started pg_autoctl node-active service with pid 1423
18:08:57 1423 INFO  Registered node 3 (db1-node2.int:5002) with name "node_3" in formation "default", group 0, state "wait_standby"
18:08:57 1423 INFO  Writing keeper state file at "/var/lib/postgresql/.local/share/pg_autoctl/var/lib/postgresql/db1-node2/pg_autoctl.state"
18:08:57 1423 INFO  Writing keeper init state file at "/var/lib/postgresql/.local/share/pg_autoctl/var/lib/postgresql/db1-node2/pg_autoctl.init"
18:08:57 1423 INFO  Successfully registered as "wait_standby" to the monitor.
18:08:57 1423 INFO  FSM transition from "init" to "wait_standby": Start following a primary
18:08:57 1423 INFO  Transition complete: current state is now "wait_standby"
18:08:57 1423 INFO  New state for node 2 "node_2" (db1-node1.int:5001): single ➜ wait_primary
18:08:57 1423 INFO  New state for node 2 "node_2" (db1-node1.int:5001): wait_primary ➜ wait_primary
18:08:57 1423 INFO  Still waiting for the monitor to drive us to state "catchingup"
18:08:57 1423 WARN  Please make sure that the primary node is currently running `pg_autoctl run` and contacting the monitor.
18:08:57 1423 WARN  Failed to connect to "port=5001 dbname=postgres host=db1-node1.int user=pgautofailover_replicator", retrying until the server is ready
18:08:57 1423 WARN  Connection to database failed: FATAL:  no pg_hba.conf entry for host "10.116.0.7", user "pgautofailover_replicator", database "postgres", SSL on
18:08:57 1423 WARN  FATAL:  no pg_hba.conf entry for host "10.116.0.7", user "pgautofailover_replicator", database "postgres", SSL off
18:08:57 1423 WARN  Failed to connect after successful ping, please verify authentication and logs on the server at "port=5001 dbname=postgres host=db1-node1.int user=pgautofailover_replicator"
18:08:57 1423 WARN  Authentication might have failed on the Postgres server due to missing HBA rules.
```

It is not clear from documentation what needs to be done here. I am following example commands found on the documentation site, GitHub, and have looked thoroughly in the Issues for any people experiencing the same issue with no luck.

I have also made some attempts to modify the pg_hba.conf directly, but have had very mixed results.

**Comment by DimCitus** [comment]
I think it boils down to this:

```
18:08:57 1423 WARN  Please make sure that the primary node is currently running `pg_autoctl run` and contacting the monitor.
```

The `pg_autoctl` service needs to be running on the first node. It is not. I'll see how to make it clearer in the docs and the README... could you confirm that when you actually run the `pg_autoctl` service on the first node, the second one makes progress indeed?

**Comment by seadba** [comment]
hi, i have same issue - my primary is running  

[pg12ha@linux2 ~]$ pg_autoctl status
20:59:16 63003 INFO  pg_autoctl is running with pid 28133
20:59:16 63003 INFO  Postgres is serving PGDATA "/data/pg12ha/data" on port 5433 with pid 28183

secondary  reports  
20:52:03 1340914 WARN  Failed to connect to "port=5433 dbname=pg12TEST host=linux2 user=pgautofailover_replicator", retrying until the server is ready
20:52:03 1340914 WARN  Connection to database failed: FATAL:  no pg_hba.conf entry for host "10.99.100.11", user "pgautofailover_replicator", database "pg12TEST", SSL off

20:52:15 1341221 WARN  Authentication might have failed on the Postgres server due to missing HBA rules.
20:52:15 1341221 ERROR Failed to connect to "port=5433 dbname=pg12TEST host=linux2 user=pgautofailover_replicator" after 14 attempts in 2 seconds, pg_autoctl stops retrying now
20:52:15 1341221 ERROR Failed initialize standby server, see above for details
20:52:15 1341221 ERROR Failed to transition from state "wait_standby" to state "catchingup", see above.
20:52:15 1340910 ERROR pg_autoctl service node-init exited with exit status 12
20:52:15 1340910 FATAL pg_autoctl service node-init has already been restarted 5 times in the last 10 seconds, stopping now


primary hba

host "pg12TEST" "pg12ha" linux2 trust # Auto-generated by pg_auto_failover
host all "pgautofailover_monitor" linux1.beerme.local trust # Auto-generated by pg_auto_failover
host replication "pgautofailover_replicator" linux4 trust # Auto-generated by pg_auto_failover
host "pg12TEST" "pgautofailover_replicator" linux4 trust # Auto-generated by pg_auto_failover

**Comment by DimCitus** [comment]
Hi @seadba ; could you read the pg_autoctl and Postgres logs from `linux2` in your environment and see why the connection is refused? Is it possible that you have firewall rules that prevent the connection from happening even before Postgres would have a chance to process it?

**Comment by seadba** [comment]
PGPORT is open on all 3 - is there a way to keep pg_autoctl from removing the $PGDATA after a failed create?

linux2 pg log   
2020-10-11 20:52:14.042 EDT [48379] FATAL:  no pg_hba.conf entry for host "10.99.100.11", user "pgautofailover_replicator", database "pg12TEST", SSL off
2020-10-11 20:52:14.042 EDT [48379] DETAIL:  Could not resolve client IP address to a host name: Name or service not known.
2020-10-11 20:52:14.611 EDT [48391] FATAL:  no pg_hba.conf entry for host "10.99.100.11", user "pgautofailover_replicator", database "pg12TEST", SSL off
2020-10-11 20:52:14.611 EDT [48391] DETAIL:  Could not resolve client IP address to a host name: Name or service not known.


from monitor server  

[pg12ha@linux1 ~]$ pg_autoctl show events
                    Event Time |   Node |       Current State |      Assigned State | Comment
-------------------------------+--------+---------------------+---------------------+-----------
  2020-10-11 20:31:42.10921-04 |    0/1 |                init |              single | Setting goal state of node 1 (linux2:5433) to single as there is no other node.
  2020-10-11 20:38:36.69381-04 |    0/1 |              single |              single | Node 1 (linux2:5433) reported new state "single"
 2020-10-11 20:50:16.790973-04 |    0/2 |        wait_standby |        wait_standby | Node 2 (linux4:5433) reported new state "wait_standby"
 2020-10-11 20:50:16.813419-04 |    0/1 |              single |        wait_primary | Setting goal state of 1 (linux2:5433) to wait_primary after node 2 (linux4:5433) joined.
 2020-10-11 20:50:16.853861-04 |    0/1 |        wait_primary |        wait_primary | Node 1 (linux2:5433) reported new state "wait_primary"
 2020-10-11 20:50:16.857911-04 |    0/2 |        wait_standby |          catchingup | Setting goal state of **node 2 (linux4:5433)** to catchingup after node 1 (linux2:5433) converged to wait_primary.

**Comment by DimCitus** [comment]
> PGPORT is open on all 3 - is there a way to keep pg_autoctl from removing the $PGDATA after a failed create?

I think what happens here is that `pg_autoctl create postgres` fails on a secondary node before it could try to `pg_basebackup`, in other words the PGDATA data directory never existed yet.

> linux2 pg log
> 
> ```
> 2020-10-11 20:52:14.042 EDT [48379] FATAL:  no pg_hba.conf entry for host "10.99.100.11", user "pgautofailover_replicator", database "pg12TEST", SSL off
> 2020-10-11 20:52:14.042 EDT [48379] DETAIL:  Could not resolve client IP address to a host name: Name or service not known.
> 2020-10-11 20:52:14.611 EDT [48391] FATAL:  no pg_hba.conf entry for host "10.99.100.11", user "pgautofailover_replicator", database "pg12TEST", SSL off
> 2020-10-11 20:52:14.611 EDT [48391] DETAIL:  Could not resolve client IP address to a host name: Name or service not known.
> ```

Could you paste your HBA setup on this primary node? It should be located in `$PGDATA/pg_hba.conf`, and we are only interested in the last lines as you will see.

**Comment by seadba** [comment]
very sorry for the delay and i appreciate the assistance - here is hba from primary  

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
host "pg12TEST" "pg12ha" linux2 trust # Auto-generated by pg_auto_failover
host all "pgautofailover_monitor" linux1.beerme.local trust # Auto-generated by pg_auto_failover
host replication "pgautofailover_replicator" linux4 trust # Auto-generated by pg_auto_failover
host "pg12TEST" "pgautofailover_replicator" linux4 trust # Auto-generated by pg_auto_failover

**Comment by DimCitus** [comment]
Ok, I see that you're using host names in your HBA file. For that to work with Postgres, you need to ensure that you have a working reverse DNS setup, and that it returns a single hostname for the IP address. See https://www.postgresql.org/docs/current/auth-pg-hba-conf.html and this part:

> If a host name is specified (anything that is not an IP address range or a special key word is treated as a host name), that name is compared with the result of a reverse name resolution of the client's IP address (e.g., reverse DNS lookup, if DNS is used). Host name comparisons are case insensitive. If there is a match, then a forward name resolution (e.g., forward DNS lookup) is performed on the host name to check whether any of the addresses it resolves to are equal to the client's IP address. If both directions match, then the entry is considered to match. (The host name that is used in pg_hba.conf should be the one that address-to-name resolution of the client's IP address returns, otherwise the line won't be matched. Some host name databases allow associating an IP address with multiple host names, but the operating system will only return one host name when asked to resolve an IP address.)

Please either double check your DNS resolution for the host names that you're using, or use IP addresses for the `--hostname` in pg_autoctl so that the HBA would be filled with IP addresses. You might also want to consider `--skip-pg-hba` and provide your own HBA file, typically replacing the default one after `pg_autoctl create postgres` and before `pg_autoctl run`.

**Comment by seadba** [comment]
ok, so if i switch hostname to ip - it does update the pg_hba on primary but still same issue - 
ost replication "pgautofailover_replicator" 10.99.100.11/32 trust # Auto-generated by pg_auto_failover
host "pg12TEST" "pgautofailover_replicator" 10.99.100.11/32 trust # Auto-generated by pg_auto_failover

but it does create the $PGDATA on the stanby tier  

11:43:01 116131 FATAL Something went wrong in sub-process supervision, stopping now. See above for details.
11:43:01 116131 INFO  Stop pg_autoctl
pg12ha@linux4:~$ ls $PGDATA
backup_label      pg_multixact  PG_VERSION
base              pg_notify     pg_wal
current_logfiles  pg_replslot   pg_xact
global            pg_serial     postgresql.auto.conf
log               pg_snapshots  postgresql-auto-failover.conf
pg_commit_ts      pg_stat       postgresql-auto-failover-standby.conf
pg_dynshmem       pg_stat_tmp   postgresql.conf
pg_hba.conf       pg_subtrans   standby.signal
pg_ident.conf     pg_tblspc     startup.log
pg_logical        pg_twophase


host "pg12TEST" "pg12ha" linux2 trust # Auto-generated by pg_auto_failover
host all "pgautofailover_monitor" linux1.beerme.local trust # Auto-generated by pg_auto_failover
host replication "pgautofailover_replicator" linux4 trust # Auto-generated by pg_auto_failover
host "pg12TEST" "pgautofailover_replicator" linux4 trust # Auto-generated by pg_auto_failover
host replication "pgautofailover_replicator" 10.99.100.11/32 trust # Auto-generated by pg_auto_failover
host "pg12TEST" "pgautofailover_replicator" 10.99.100.11/32 trust # Auto-generated by pg_auto_failover

**Comment by DimCitus** [comment]
I am not seeing the error lines from the `pg_autoctl` output on the new secondary (linux4 I believe) where it's failing to create the secondary using the IP address, can you paste more?

**Comment by DimCitus** [comment]
Is it possible that you redid the secondary node, but not the primary, and that the HBA now contains both the hostnames and the IP addresses? When that's the case, Postgres HBA first failure is all that matters, the lines after the failed one are never used, the connection attempt is already rejected.

You could either clean-up your HBA file manually until it works, or just create the whole cluster again using IP addresses this time, or install a DNS service that is compliant with the detailed expectations of PostgreSQL.

**Comment by seadba** [comment]
ok, i appreciate your time - i'll hammer through it, very curious to test it out - thanks again

**Comment by s4ke** [comment]
If it helps, this is the pg_hba and pg_ident configuration we are using with self signed certs:

pg_hba.conf on the datanodes:
```
hostssl autoctl autoctl_node <monitor-ip>/32   cert map=autoctl_node_remote
hostssl autoctl autoctl_node <node-1>/32   cert map=autoctl_node_remote
hostssl autoctl autoctl_node <node-2>/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node <monitor-ip>/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node <node-1>/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node <node-2>/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node <monitor-ip>/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node <node-1>/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node <node-2>/32   cert map=autoctl_node_remote
hostssl replication pgautofailover_replicator <monitor-ip>/32   cert map=pgautofailover_replicator_remote
hostssl replication pgautofailover_replicator <node-1>/32   cert map=pgautofailover_replicator_remote
hostssl replication pgautofailover_replicator <node-2>/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_monitor <monitor-ip>/32   cert map=pgautofailover_monitor_remote
hostssl postgres pgautofailover_monitor <node-1>/32   cert map=pgautofailover_monitor_remote
hostssl postgres pgautofailover_monitor <node-2>/32   cert map=pgautofailover_monitor_remote
local all postgres    peer
local replication postgres    peer
local all all    peer
host all all 127.0.0.1/32   md5
host all all ::1/128   md5
```

pg_ident.conf for all (we use CN=ip in self signed certs and then make postgres map users by ip):

```
autoctl_node_peer  postgres             autoctl_node
autoctl_node_remote <monitor> autoctl_node
pgautofailover_replicator_remote <monitor> pgautofailover_replicator
pgautofailover_monitor_remote <monitor> pgautofailover_monitor
autoctl_node_remote node-1 autoctl_node
pgautofailover_replicator_remote node-1 pgautofailover_replicator
pgautofailover_monitor_remote node-1 pgautofailover_monitor
autoctl_node_remote node-2 autoctl_node
pgautofailover_replicator_remote node-2 pgautofailover_replicator
pgautofailover_monitor_remote node-2 pgautofailover_monitor
```

**Comment by DimCitus** [comment]
Thanks @s4ke ! 

I suspect @seadba problem is related to using hostnames instead of IP addresses, in an environment where any local hostname (as per `hostname -I` or equivalent) is resolved correctly, but where other hostnames are not for lack of a proper local-domain DNS service being setup. My current guess is something like systemd-resolved, but it's a very wild guess.

I see that in your example you're using node IP addresses rather than hostnames, and that's a solution I shared with @seadba earlier too. This side steps Postgres requirements for forward and reverse DNS lookups entirely and can make deployments easier indeed.

**Comment by DimCitus** [comment]
Closing thanks to #458 ; consider re-opening or adding more information if you feel more work is needed in pg_auto_failover on that front!
