### ISSUE TITLE
Running postgres regression tests

### ISSUE THREAD

**Issue by rheaton** [citusdata/pg_auto_failover#464]
Hello!

Jacob and I spent a bit of time trying to get the regression tests running locally, but it looks like there may be some prerequisite set-up required. 

Would it be possible to document this or make an easy way to run them (especially since we haven't found a way to run them in CI yet)?

Here are our notes from trying to set them up locally (we were planning to add them to CONTRIBUTING.md if we got it working) 😇

 -------

#### Postgres Regress tests

If your installed version of postgres hasn't packaged `pg_regress`:

Clone [postgres](https://github.com/postgres/postgres/tree/master)
Checkout the branch of the stable version that matches your local postgres install

e.g.
```bash
psql --version
> psql (PostgreSQL) 12.4
git clone git@github.com:postgres/postgres.git
cd postgres
git co REL_12_stable
```

Configure and make postgres
```bash
./configure
make -j8 // set to the number of processors you want to run against
```

Make the regress test runner (you may need to make and chown directories)
```bash
cd src/test/regress
make
```

Generates an executable `/usr/local/pgsql/lib/pgxs/src/test/regress/pg_regress`

Set up a monitor
```bash
pg_autoctl create monitor --pgport 7800 --auth trust --pgdata ~/failover/monitor -v --no-ssl --hostname 127.0.0.1 --run
```

Running a test
_Note_: it appears the tests may need to be run in an order, but there isn't
a schedule for running them. Additionally, other nodes may need to be set up.

`/usr/local/pgsql/lib/pgxs/src/test/regress/pg_regress --port 7800 --dbname pg_auto_failover --use-existing workers`

cc @jchampio

**Comment by DimCitus** [comment]
Hi,

So the pgautofailover extension regression test can be run thanks to PGXS `make installcheck` target. This requires that a Postgres instance is running and setup correctly with the extension installed and loaded, and the easiest way to achieve that is of course `pg_autoctl create monitor`.

So here's my personal recipe to run the extension regression tests:

```
$ export PGDATA=/tmp/pgaf/m
$ export PGPORT=5000
$ ./src/bin/pg_autoctl/pg_autoctl create monitor --auth trust --no-ssl --hostname localhost --run
```

Then in another terminal

```
$ PGPORT=5000 make -C src/monitor/ installcheck
```

And now I realise that https://postgresapp.com is very well packaged indeed. I have `/Applications/Postgres.app/Contents/Versions/{10,11,12,13}/lib/postgresql/pgxs/src/test/regress/pg_regress` on my system without having the whole Postgres source tree and having to prepare and compile everything. I don't think this should be what we use in our contributing requirements though.

What I hope we can achieve is to use the `postgresql-server-dev-all` package in debian in the Dockerfile and add the `make -C src/monitor installcheck` somewhere in our test suite. This requires allowing docker to generate a core file, which by default is not allowed. It might be that we only need to add `--ulimit core=-1` to our `DOCKER_RUN_OPTS` to be able to add that, I am just finding that now and didn't try that yet.
