### ISSUE TITLE
how to work with fdw sharding?

### ISSUE THREAD

**Issue by thomasdba** [citusdata/pg_auto_failover#465]
it is possible to use multiple hosts(primary and standbys) to create foreign server , then if the foreign server failover , fdw still works ,rt ?

**Comment by DimCitus** [comment]
I think the `postgres_fdw` extension uses `libpq` to connect to the remote server, so you should be able to use the connection URI that is provided by the monitor (with `pg_autoctl show uri --formation default`) as the FDW server connection string. What happens when you try?

**Comment by thomasdba** [comment]
not tried yet , will test if FDW server connection support multiple hosts.
