### ISSUE TITLE
Passwords are logged in plain text

### ISSUE THREAD

**Issue by rheaton** [citusdata/pg_auto_failover#466]
Even when not using the most [secure type](https://pg-auto-failover.readthedocs.io/en/latest/security.html#authentication-with-passwords) of connection, we should attempt to scrub the connection string when logging. 

Debug logs:
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L359
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L454
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L573
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L704

Info Logs:
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L607

Error Logs:
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L482
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L554

Warn Log:
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L530
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L650
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgsql.c#L678

**Comment by rheaton** [comment]
We did the recommended connection via the pgpass file, and we still see the pw in plain text in the logs.

**Comment by DimCitus** [comment]
Have a look at the functions [parse_pguri_info_key_vals](https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/parsing.c#L522) and [buildPostgresURIfromPieces](https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/parsing.c#L648) that we use already when editing the SSL properties of a connection string. Those functions should make it easy for you to write a obfuscating password utility to use in those call sites.

**Comment by rheaton** [comment]
Working on a PR for this

**Comment by rheaton** [comment]
In progress: https://github.com/citusdata/pg_auto_failover/compare/master...rheaton:pw-in-log?expand=1 
Need to actually use the function.

@DimCitus You'll notice that I've added some unit tests for the C code. What do you think? :)

**Comment by rheaton** [comment]
Breaking this work into a few PRs:
The above PR will not be covering the logging of the settings (search for `Settings by pg_auto_failover`) or when there is incomplete data in the pguri (e.g. `Failed to find dbname in the pguri ...`) in order to create a small change.
