### ISSUE TITLE
test_multi_standbys has intermittent failures

### ISSUE THREAD

**Issue by jchampio** [citusdata/pg_auto_failover#481]
The `test_014_update_standby_names_when_adding_and_removing_a_standby` committed recently occasionally fails with

```
======================================================================
FAIL: test_multi_standbys.test_014_update_standby_names_when_adding_and_removing_a_standby
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/src/pg_auto_failover/tests/test_multi_standbys.py", line 245, in test_014_update_standby_names_when_adding_and_removing_a_standby
    eq_(node1.get_synchronous_standby_names(),
AssertionError: '' != '*'
```

It's likely missing some synchronization code to ensure that the primary in question has actually transitioned to the final state.

The test has commented calls such as `assert node1.wait_until_state(...)`, which we were having trouble with while writing the test. For example, waiting until `primary` is probably correct, but waiting for `join_primary` earlier in the test causes a race where, if we don't call it fast enough, the primary will have already transitioned to `primary` state and the test will fail.

**Comment by DimCitus** [comment]
The test was removed in https://github.com/citusdata/pg_auto_failover/pull/494 and should be added back later on, in a version that actually covers the problem area, and in a stable way. Meanwhile I'm closing this issue, I think #483 is where the work happens?
