### ISSUE TITLE
Keeper fails at startup with systemd service

### ISSUE THREAD

**Issue by axl8713** [citusdata/pg_auto_failover#484]
When restarting the host machine, the systemd service created with `pg_autoctl -q show systemd` cannot start the keeper, that fails with this error:
```
FATAL:  could not open directory "/var/run/postgresql/13-main.pg_stat_tmp": No such file or directory
```
I've fixed the issue adding this to the systemd unit file:
```
ExecStartPre = mkdir -p /var/run/postgresql/13-main.pg_stat_tmp
```
Have I misconfigured something to get this behavior?

**Comment by DimCitus** [comment]
Hi @axl8713 ; thanks for using pg_auto_failover and opening an issue! Are you setting https://www.postgresql.org/docs/13/runtime-config-statistics.html#GUC-STATS-TEMP-DIRECTORY to that value? I don't think pg_auto_failover is responsible for that behaviour you're experiencing, on a first read here.

**Comment by axl8713** [comment]
Seems it's set correctly
```
$ grep stats_temp /var/lib/postgresql/pgdata/postgresql.conf
stats_temp_directory = '/var/run/postgresql/13-main.pg_stat_tmp'
```
There's a bug filed for `postgresql-common` that explains the issue: https://bugs.launchpad.net/ubuntu/+source/postgresql-common/+bug/1749283

**Comment by DimCitus** [comment]
Thanks for diving into the problem @axl8713 ; can you share the steps you followed when creating this Postgres instance and registering it with pg_auto_failover?

**Comment by axl8713** [comment]
Sure.
Starting with a clean installation of Postgresql 13 on Ubuntu 20.04, I followed the instructions to install pg_auto_failover (postgresql-12-auto-failover-1.4).
Next, ran the `create postgres` command:
```
pg_autoctl create postgres \
--hostname ... \
--auth trust \
--ssl-self-signed \
--monitor 'postgres://autoctl_node@...:5000/pg_auto_failover?sslmode=require' \
--pgdata /var/lib/postgresql/pgdata \
--pgctl /usr/lib/postgresql/13/bin/pg_ctl \
--pgport 5432 \
--run
```
And finally created the systemd service with `pg_autoctl -q show systemd`, before rebooting and get the error.

**Comment by DimCitus** [comment]
Kk thanks for sharing.

So you're using the Postgres instance that has been created for you by the debian packaging system, and that we then re-own by de-debianizing it (moving the configuration files back in PGDATA, mainly). We missed that problem with the temp stats directory and should fix that.

Meanwhile, you can also use the following provisioning method, allowing to install the Postgres package without creating a default debian cluster. Then your `pg_autoctl create postgres` will do the Postgres `initdb` step and you will be fine without the debian/ubuntu specificities.

``` bash
$ sudo apt-get install -q -y postgresql-common
$ echo 'create_main_cluster = false' | sudo tee -a /etc/postgresql-common/createcluster.conf
$ sudo apt-get build-dep -q -y postgresql-13
```

**Comment by axl8713** [comment]
Great! 
Thanks.
