### ISSUE TITLE
Single mode to maintenance mode

### ISSUE THREAD

**Issue by berlin-ab** [citusdata/pg_auto_failover#485]
I'm curious if this project has considered allowing a node in the `single` state to be put into maintenance mode. It does not seem to be possible in v1.4.

**Our use-case:**

We want to be able to put the single instance into maintenance mode, allowing the pg_autoctl keeper to continue running, and then perform a restore from a backup. We're using pg_autoctl's existence to keep our container alive in Kubernetes.

**Comment by DimCitus** [comment]
Hi @berlin-ab ; thanks for considering pg_auto_failover and opening an issue!

The SINGLE state is but a step during the bootstrap of a system, not something that should be supported with the rest of the tooling. You can `pg_autoctl create postgres` and target a PGDATA that has already been populated with a backup, I would consider adjusting your provisioning scripts that way. Also note that when in the SINGLE state, an `initdb` has already been done, and your backup won't be compatible with it. As we register the Postgres `system_identifier` on the monitor, I don't think we will support what you're attempting here at all.

Closing the issue for triage purposes, please feel free to open it again with more information and questions if necessary.

**Comment by berlin-ab** [comment]
Hi @DimCitus - Thanks for your quick reply

The backup we've taken is from an instance when it was in `single` mode.

Here's our setup:

We create a monitor and a single node formation, and we optionally allow our customers to spin up the secondary. One of the scenarios we're testing:

1. set up a monitor, primary, and secondary
1. we then take a backup of the primary
1. restore the primary
  
To restore the primary, we've found this work-around:

1. drop the secondary node
1. pause the start/stop process on the primary
1. restore the primary
1. unpause the start/stop process primary
1. add a new secondary

**Comment by DimCitus** [comment]
I wonder if removing all the nodes and starting again from backups would be easier. Also, how do you pause and unpause the start/stop process exactly?
