### ISSUE TITLE
Hooks for Node Failover/Switchover - Virtual IP?

### ISSUE THREAD

**Issue by s4ke** [citusdata/pg_auto_failover#490]
One of our application is based on Django and uses the standard libpq high availability capabilities so that we don't have to do anything in case of a failover.

Other applications in our stack (such as Superset which uses SQLAlchemy) do not support this at the application layer.

We try to go as far as we can go without requiring a load balancer/proxy to keep everything as simple as possible (exactly the reason we opted to go for pg_auto_failover in the first place :) ).

Now, I am thinking how to solve our issue with HA for the rest of our application stack: We could introduce a virtual ip that always points to the current master (or secondary if we only do analytics) of the replication set.

One way we could implement this is by having a daemon that checks all database nodes for their state and have this as a separate software in our cluster - or we could implement something that hooks into the lifecycle pg_auto_failover. What do you think? Is this something that pg_auto_failover could support?

**Comment by DimCitus** [comment]
Hi @s4ke ; I'm surprised SQLAlchemy has no way to setup a multi-host Postgres connection string, but I must admit I never tried, so I'll take your word for it.

About v-ip we have had a similar discussion and approach with using pgbouncer. It is already possible to use the LISTEN/NOTIFY based notifications for any client program to know when something is happening on a formation on the monitor, and you can also use the SQL API directly with `pgautofailover.get_primary('default', 0)` and such.

We could see about how to contribute that piece of software directly in the pg_auto_failover tool set if we have a portable enough way to maintain a virtual IP address. The current thinking about this has been, I believe, related t pgbouncer, as in the following pre-existing issues:

  - https://github.com/citusdata/pg_auto_failover/issues/440
  - https://github.com/citusdata/pg_auto_failover/issues/427

**Comment by s4ke** [comment]
Hey @DimCitus ,

I was confused by that as well, but I think SQLAlchemy wants you to implement HA via some kind of database router just like Django does normally as well. But since Django uses libpq internally all you have to do to get proper HA is to do something like this:

```
    DATABASES = {
        'default': {
            'ENGINE': 'django_db_geventpool.backends.postgresql_psycopg2',
            'NAME': '{{ dbname }}',
            'USER': '{{ db_user }}',
            'PASSWORD': '{{ db_passwd }}',
            'HOST': '{{ db_hosts }}',
            'CONN_MAX_AGE': 0,
            'PORT': '{{ skipper_db_ports }}',
            'OPTIONS': {
                'application_name': {{ app_name }},
                'options': '-c search_path={{ search_path }}',
                'sslcert': '/certs/server.crt',
                'sslkey': '/certs/server.key',
                'sslrootcert': '/certs/rootCA.crt',
                'sslmode': 'verify-full',
                'target_session_attrs': 'read-write',
                'MAX_CONNS': {{ max_conns }}
            },
            'ATOMIC_REQUESTS': True
        }
    }
```

But I digress...

Yeah, it would be great to have some kind of integration hook that does the failover itself. I imagine this could be something that could have some kind of RESTful integration? Send that event via HTTP to notify the failover handler that it needs to failover and keep sending that event until it is acknowledged by a HTTP 200? This would be the least intrusive way that would probably also work nicely in a containerized environment that I have seen used by others on the issues in this repository.

**Comment by DimCitus** [comment]
First, thanks again @ louiseGrandjonc! ;-)

Then I am not sure I follow your suggestion with the RESTful integration. I you want to implement a kind of HTTP based application that uses CGI scripts to call into `pg_autoctl perform switchover`, that should be easy enough I guess.

Finally, please see also https://github.com/citusdata/pg_auto_failover/pull/508 in which we are going to implement and provide support for pgbouncer. One idea with supporting pgbouncer would be to offer a connection end-point that redirects to the current primary server at any time. It's not as good as a virtual IP as this is a proxy and incurs some overhead, and it's not fully transparent... it might still fit the bill for you?

Other than that, again, if there is a simple portable and open source virtual IP solution out there that we could integrate with, we could see about the same level of integration as in #508 for this target. Do you have one in mind, or would you just use something like CARP anyway?

**Comment by s4ke** [comment]
About the RESTful integration: yes that would definitely work, but I am concerned about the possibility of the failover event being lost. Therefore I thought about some guaranteed delivery mechanism that would have an event in the monitors db that is sent until it is acknowledged by a HTTP 200. This might be overcomplicating things, though.

It might fit the bill, yes, but as you said it is "just" a proxy which is another piece of hardware we would have to maintain. pgBouncer would add other things like connection pooling for arbitrary applications though.

We are using Hetzner for a lot of our infrastructure and they have a REST API for their robot interface. At the start we would probably simply be using something like this https://community.hetzner.com/tutorials/failover-script .

**Comment by s4ke** [comment]
I have thought about it and maybe "simply" running HAProxy would be a simpler and more portable solution altogether?

https://www.percona.com/blog/2019/10/31/postgresql-application-connection-failover-using-haproxy-with-xinetd/

Scenario with only the datanodes: Each datanode gets a HAProxy instance configured like this. Secondary nodes redirect to the primary for write operations and do read operations on the local machine (if available). This would solve the problem of "I only have one IP, and a swtichover happened, I don't want to reconfigure my setup".

Scenario with a separate load balancer: Normal setup for HAProxy. If you want failover between HAProxy instances - as in the proxy goes down - you can use libpq.

**Comment by DimCitus** [comment]
Hi @s4ke ; I think what you're proposing now is converging nicely with what is being implemented at https://github.com/citusdata/pg_auto_failover/pull/539, using pgbouncer there instead of haproxy. We could envision haproxy support too, if necessary, later, and the work we do in adding the pgbouncer support should make it easier then to implement haproxy support. Feel free to get organised around contributing haproxy support to pg_auto_failover is that's a better option for you compared to using pgbouncer.

Closing this issue now for triage, feel free to re-open with more information/questions if needed.

**Comment by s4ke** [comment]
Just adding some information regarding the actual solution that we are using nowadays for haproxy (in docker swarm):

```
# 50 connections as we have two instances of haproxy running
global
    maxconn 50
    external-check
    insecure-fork-wanted
 
defaults
    log global
    mode tcp
    retries 2
    timeout client 30m
    timeout connect 4s
    timeout server 30m
    timeout check 5s
 
listen stats
    mode http
    bind *:5002
    stats enable
    stats uri /
 
listen ReadWrite
    bind *:5000
    option external-check
    external-check command /etc/haproxy/check_primary.sh
    fullconn 50
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server data-01 192.168.0.7:5433 maxconn 50 check
    server data-02 192.168.0.9:5433 maxconn 50 check

listen ReadOnly
    bind *:5001
    option external-check
    external-check command /etc/haproxy/check_secondary.sh
    fullconn 50
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server data-01 192.168.0.7:5433 maxconn 50 check
    server data-02 192.168.0.9:5433 maxconn 50 check
```

check_primary.sh (returns exit code 0 if server is a primary):

```
#!/bin/bash

_PGPASSWORD=$(/bin/cat /run/secrets/postgres_haproxy_pgpassword)

VALUE=$(
    PGPASSWORD="$_PGPASSWORD" \
    PGSSLROOTCERT=/run/secrets/postgres_rootCA \
    PGSSLCERT=/run/secrets/postgres_haproxy_crt  \
    PGSSLKEY=/run/secrets/postgres_haproxy_key \
    /usr/bin/psql -t -h "$3" -p "$4" -c "select pg_is_in_recovery()" -X -A -U healthuser "dbname=template1 sslmode=verify-ca"
)

if [ "$VALUE" == "t" ]
then
    # echo "$0: $3:$4 - standby"
    exit 1
elif [ "$VALUE" == "f" ]
then
    # echo "$0: $3:$4 - primary"
    exit 0
else
    echo "$0: $3:$4 - error"
    exit 255
fi
```

check_secondary.sh (returns exit code 0 if server is secondary):

```
#!/bin/bash

_PGPASSWORD=$(/bin/cat /run/secrets/postgres_haproxy_pgpassword)

VALUE=$(
    PGPASSWORD="$_PGPASSWORD" \
    PGSSLROOTCERT=/run/secrets/postgres_rootCA \
    PGSSLCERT=/run/secrets/postgres_haproxy_crt  \
    PGSSLKEY=/run/secrets/postgres_haproxy_key \
    /usr/bin/psql -t -h "$3" -p "$4" -c "select pg_is_in_recovery()" -X -A -U healthuser "dbname=template1 sslmode=verify-ca"
)

if [ "$VALUE" == "t" ]
then
    # echo "$0: $3:$4 - standby"
    exit 0
elif [ "$VALUE" == "f" ]
then
    # echo "$0: $3:$4 - primary"
    exit 1
else
    echo "$0: $3:$4 - error"
    exit 255
fi
```
