### ISSUE TITLE
using with citus data extension

### ISSUE THREAD

**Issue by tibudiyanto** [citusdata/pg_auto_failover#50]
Hi,

I would like to know if this extension is compatible with citus data extension. As far as I know, the citus extension only provide distribution of the data, and query, but not auto failover.

If it is compatible, is there a writeup somewhere I can learn how to do it?

Thank you

**Comment by lfittl** [comment]
@tibudiyanto Thanks for trying out pg_auto_failover!

We don’t support integration of the open-source pg_auto_failover and the open-source Citus extension at this point. We offer automated HA capabilities such as automatic failover as part of the Citus Enterprise product, as well as in our [Azure-based cloud offering](https://www.citusdata.com/blog/2019/05/06/introducing-hyperscale-citus-on-azure-database-for-postgres/).
 
If you’d like to learn more about the HA capabilities in Citus Enterprise, we’d recommend to reach out through our contact us form: https://www.citusdata.com/about/contact_us
