### ISSUE TITLE
Is it possible to run monitor and replication on seperate network interfaces ? 

### ISSUE THREAD

**Issue by brsc2909** [citusdata/pg_auto_failover#500]
Hi,
Is it possible to configure pg_auto_failover so that the monitor node monitors my cluster over the public interface but have the cluster replication over private network? 
Currently my cluster is configured so that all the cluster services run over an network interface on a private VLAN and users connect via public interface. This works perfectly in the scenario that the Postgres service were to crash or a node rebooted. However if the network was to drop on the public interface users would not be able to connect and the cluster would not fail-over as the monitor would still view it as up. I could configure everything to run over the public interface but I'd prefer to keep things separate.

Brendan

**Comment by DimCitus** [comment]
Hi @brsc2909 ; parts of what you're asking is possible, but maybe not the whole thing.

The idea is to use the `--hostname` and the `--monitor` parameters in the way that makes sense with your question. On the monitor the `--hostname` should be the public interface IP address, and on the Postgres nodes the `--monitor` should use the public interface and then the `--hostname` should use the private IP addresses.

The Postgres nodes `--hostname` is used when the monitor connects to its nodes and also when setting up replication in between nodes. Given that I don't think that it is possible today to have the monitor use the public IP addresses of the Postgres nodes for its probing of them while using another set of IP address when setting up the replication streams in between nodes.
