### ISSUE TITLE
How does pg_auto_failover ensure high availability when the monitor node is down?

### ISSUE THREAD

**Issue by siu91** [citusdata/pg_auto_failover#501]

**Comment by DimCitus** [comment]
Hi @siu91 ; please read the following documentation sections:

  - https://pg-auto-failover.readthedocs.io/en/latest/fault-tolerance.html
  - https://pg-auto-failover.readthedocs.io/en/latest/faq.html#the-monitor-is-a-spof-in-pg-auto-failover-design-how-should-we-handle-that

I think the docs contain the answers you are looking for. If after reading the docs you have more questions on this topic, please feel free to ask them here, and if needed to re-open the issue with more details.
