### ISSUE TITLE
When the postgres server is shut down, the primary node status is reachable

### ISSUE THREAD

**Issue by siu91** [citusdata/pg_auto_failover#507]
![image](https://user-images.githubusercontent.com/4889213/99047542-5043a300-25cf-11eb-8c93-b2388f9808e2.png)

**Comment by s4ke** [comment]
How did you stop the service?

If you do not demote the primary before stopping pg_auto_failover, I don't think that pg_auto_failover initiates the failover automatically just by stopping the service. The node must be detected to not be reachable the usual way:

https://pg-auto-failover.readthedocs.io/en/latest/ref/configuration.html

**Comment by siu91** [comment]
@s4ke 
I stop the service through the `systemctl  stop pgautofailover` command,in CentOS 7.

**Comment by DimCitus** [comment]
Hi @siu91 ; @s4ke,

When you stop the primary, obviously `pg_autoctl` is not running anymore and won't connect to the monitor to report that Postgres is not running. So then we are relying on the monitor health check system, which is a background process that connects every once in a while to each Postgres node registered, and maintains the health status depending on whether it could connect or not. 

By default the monitor background process attempt to connect every 5s to each node, with a connect timeout of 5s, and then retry a connection twice, each retry separated by at least 2s. So the monitor needs something like 15s to 30s minimum (depending on specific TCP connection errors and timeouts) before updating the “reachable” column in the `pg_autoctl show state` output as you're monitoring.

**Comment by DimCitus** [comment]
This might be useful:
```
pg_auto_failover> select name, setting from pg_settings where name ~ 'pgautofailover\.*health*';
                  name                   │ setting 
─────────────────────────────────────────┼─────────
 pgautofailover.health_check_max_retries │ 2
 pgautofailover.health_check_period      │ 5000
 pgautofailover.health_check_retry_delay │ 2000
 pgautofailover.health_check_timeout     │ 5000
(4 rows)
```
