### ISSUE TITLE
About Client HA

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#511]
Hello,

About https://pg-auto-failover.readthedocs.io/en/latest/architecture.html => Client-side HA 

we have some applications where it is not possible to set two host on the connections string (there is a box when creating connexions and we just can set one server)

We'll have to use some  load balancer (F5), but how can we tell it to choose the primary server (is there an http check) ?

Thank you 

Tiago    ANASTACIO

**Comment by DimCitus** [comment]
Hi @jacks33 ;

First, is it possible to have your box understand client-side HA and multi-host connection strings? That would be the ideal solution of course, if you could simply use the connection string as shown per `pg_autoctl show uri`.

Please see also #427 and #440 and #490 and #508, all issues where an external software/agent would like to know which node is the current primary. The monitor exports a `pgautofailover.get_primary(formation, groupId)` function that you can use to fetch the current primary node (at some point in times, there is no primary). Then you can use our LISTEN/NOTIFY channels on the monitor to have a chance of reacting quickly to changes.

I believe it would be easy to write a very simple HTTP application that connects to the monitor and call the `pgautofailover.get_primary()` function and formats the result as needed for your proprietary load balancer, and call it a day?

**Comment by rioberkas** [comment]
https://github.com/rioberkas/heatlhchecks-pg_auto_failover

i hope this help
