### ISSUE TITLE
Use pg_config to find pg_ctl if no pg_ctl is in PATH

### ISSUE THREAD

**Issue by JelteF** [citusdata/pg_auto_failover#514]
On Ubuntu 18.04 `pg_ctl` is not in `PATH` by default, but `pg_config` is. It would be nice if we would use `pg_config` to find `pg_ctl` if it is not in `PATH`. This should be fairly easy, because of the changes from https://github.com/citusdata/pg_auto_failover/pull/510

**Comment by DimCitus** [comment]
Hey @JelteF I came up with https://github.com/citusdata/pg_auto_failover/pull/515 and tested it locally, but my local test environment is not a debian/ubuntu machine... I figured I would ask you to test there and hopefully we're good already, if not I'll see about spinning a VM for finishing the task.
