### ISSUE TITLE
About Client HA (suite)

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#516]
Salut Dimitri,

continuing my previous question : [(https://github.com/citusdata/pg_auto_failover/issues/511)]
about client HA.

I have a possibility throught the load balancer(F5) to directly send a postgres query to primary and standby (tough it must be at a certain period  example 30 seconds)

But I have a few restrictions : 
- this must be periodic (example 30s)

- Based on the result of the query, load balancer would consider this server primary or not 
so I can't target monitor to get primary and then target primary (to complex for F5) (and shut down monitor would shut down connections to postgres at any time)

- if the server is not reachable or postgres NOK it is not a problem, this node would **not** be considered the primary

My question is:

is it safe to send this query: select pg_is_in_recovery() to  primary and standby to determine current primary ?
or maybe querying pg_autofailover metadata on these servers ? 

Thank you  

Tiago ANASTACIO

**Comment by DimCitus** [comment]
I would use `select pg_is_in_recovery()` in your case then, yes. Feel free to re-open issues that I closed when you have new material to add to the conversation, of course. I makes it way easier for people following your tracks to see where you ended at ;-)
