### ISSUE TITLE
monitor location

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#522]
Hello,

Because of logistics reasons I will have for some time two datacenter (instead of three) primary an standby will be in a different datacenter and monitor will be in one of these datacenters. 
I know it's bad, but it will be temporary.
My question is :
*In that context*, when a half of full partitionning network occurs, do some failovers happen while it shouldn't or worse could it cause a split-brain situation ?

Thank you.

**Comment by DimCitus** [comment]
Hi @jacks33 ; thanks for your patience. You can review how things work in details at https://pg-auto-failover.readthedocs.io/en/latest/fault-tolerance.html. Short answer is that you should be fine: pg_auto_failover checks connections in two different places before making decisions, and network splits are accounted for and checked in our design and implementation. We even cover network splits in our test suite.

**Comment by jacks33** [comment]
Thanks for your answer, I trust 100% that tool, and read the documentation.
Just I have for a few months only two datacenter each one with a postgresql node, and unfortunately I will have to install monitor in one of these two nodes(and that's very bad).
And I would like to know if it could lead in very bad things or not.
If yes I will install pg_auto_failover and keep it in manage mode, if in some cases it will  not just  trigger the failover that's not a problem as long as primary could be fenced.
Again I know that's wrong but that's for a few months.

Thank you
