### ISSUE TITLE
community packages for release 1.4.1

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#557]
It may be the wrong place to ask for it.

community packages for 1.4.1 are missing : http://download.postgresql.org/pub/repos/yum/10/redhat/

**Comment by DimCitus** [comment]
Hi @jacks33 ; we prepare our own packages over at https://packagecloud.io/citusdata/community ; the Postgres community packages are maintained by volunteers. Feel free to ping them.
