### ISSUE TITLE
"primary" to "single" undefined in state machine

### ISSUE THREAD

**Issue by siu91** [citusdata/pg_auto_failover#559]
I found that in practice, "primary" state can become "single". There are three nodes,node1(primary),node2(secondary),node3(secondary),when i delete node2 and node3,node1 state become "single",different from what I see in the [state machine](https://github.com/citusdata/pg_auto_failover/blob/master/docs/tikz/fsm.svg).

**Comment by DimCitus** [comment]
Per documentation online at https://pg-auto-failover.readthedocs.io/en/latest/failover-state-machine.html#state-reference we can read:

> The following diagram shows the pg_auto_failover State Machine. It’s missing links to the single state, which can always been reached when removing all the other nodes.
