### ISSUE TITLE
Cluster to Receive from Existing External PG Database 

### ISSUE THREAD

**Issue by kevinelliott** [citusdata/pg_auto_failover#564]
Is there any ability to have the new failover cluster receive/mirror an existing external PG database and then cut over to the new failover cluster as primary? I am trying to minimize loss by allowing the new cluster to act as a secondary until ready.

**Comment by DimCitus** [comment]
Hi @kevinelliott ; if I understand your question correctly I think the best way forward is to add the pre-existing Postgres instance to the monitor as the first node. The existing Postgres instance is then registered as the primary, and the next nodes are setup as secondary nodes. To do that, simply use `pg_autoctl create postgres ...` on the already running Postgres instance.

See https://pg-auto-failover.readthedocs.io/en/latest/ref/reference.html#pg-auto-failover-postgres-node-initialization for more information, specifically item _2. Initialize an already existing primary server_.
