### ISSUE TITLE
question on systemd service file name and wal_keep_segments

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#566]
Hello,

we have several postgres instances in the same server.

I follow the official documentation when it comes to create the systemd service file:

```
pg_autoctl -q show systemd --pgdata ~ha-admin/ha > pgautofailover.service
  sudo mv pgautofailover.service /etc/systemd/system
  sudo systemctl daemon-reload
  sudo systemctl enable pgautofailover
  sudo systemctl start pgautofailover
```

my question is : 

Is there any caveat in customizing the name of the service file e.g.

``` 
pg_autoctl -q show systemd --pgdata ~myfirstapplication > pgautofailovermyfirstapplication.service
pg_autoctl -q show systemd --pgdata ~mysecondapplication > pgautofailovermysecondapplication.service
```

and in running these services in the sameserver ?

my second question is related to wal_keep_segments:
I notice it is set to 100 in postgresql.auto.conf.
As you use replication_slots , I wonder why set a value to wal_keep_segments ?

thank you very much.

**Comment by DimCitus** [comment]
Hi @jacks33,

When running several Postgres instances on the same Operating System, in a production context, for security reasons it is advised that you use a different system user to own each of the Postgres instances. Then I suppose that you can have one Systemd unit integration per Postgres instance, sure.

About wal_keep_segments, it's a cheap protection to have in case other things go wrong, so I still think it's good to have as a default, just in case.
