### ISSUE TITLE
pg_hba.conf error when creating secondary if reverse DNS is unavailable 

### ISSUE THREAD

**Issue by marcocitus** [citusdata/pg_auto_failover#6]
I tried setting up pg_auto_failover on a CentOS 7 Azure VM (locally), but when setting up the standby I ran into the following issue:
```
$ pg_autoctl create postgres --monitor postgres://autoctl_node@pgaf-test.dmqu0iik0f1uppllrfdl2ayvwe.bx.internal.cloudapp.net:6000/pg_auto_failover --pgport 6002 --nodename `hostname --fqdn`  --pgdata node2   
...
03:39:15 ERROR pg_basebackup: could not connect to server: FATAL:  no pg_hba.conf entry for replication connection from host "10.1.19.4", user "pgautofailover_replicator", SSL off

03:39:15 ERROR Failed to run pg_basebackup: exit code 1
03:39:15 ERROR Failed initialise standby server, see above for details
03:39:15 ERROR Failed to transition from state "wait_standby" to state "catchingup", see above.
```

In the pg_hba.conf, the following entries were added:
```
host all "pgautofailover_monitor" pgaf-test.dmqu0iik0f1uppllrfdl2ayvwe.bx.internal.cloudapp.net trust # Auto-generated by pg_auto_failover
host replication "pgautofailover_replicator" pgaf-test.dmqu0iik0f1uppllrfdl2ayvwe.bx.internal.cloudapp.net trust # Auto-generated by pg_auto_failover
host "postgres" "pgautofailover_replicator" pgaf-test.dmqu0iik0f1uppllrfdl2ayvwe.bx.internal.cloudapp.net trust # Auto-generated by pg_auto_failover
```

Using hostnames in pg_hba.conf relies on reverse DNS of the client IP. However, reverse DNS of internal IPs does not work on Azure.

Adding pg_hba.conf records for `10.1.19.4/32` on the primary and running `SELECT pg_reload_conf()` before creating the standby resolved the problem.

**Comment by DimCitus** [comment]
See https://github.com/citusdata/pg_auto_failover/pull/9#issuecomment-490107561 for more context about a search of a good solution for this one. In particular:

> We might want to revisit the whole HBA management in pg_auto_failover and come up with a nicer overall implementation here, including facilities for users to provide their own HBA rules and then have pg_auto_failover only check that everything works as intended.

Discussion can continue from here.

**Comment by DimCitus** [comment]
@adrianlzt I failed to reproduce the error you have, can you try again now with the current code? If you still have the issue, please consider opening a new issue so that we can track it separately. Thanks!
