### ISSUE TITLE
pg_autoctl failed to create monitor on mac

### ISSUE THREAD

**Issue by mtuncer** [citusdata/pg_auto_failover#60]
I was unable to create monitor using 1.0.4 release with the following command

```
pg_autoctl create monitor --pgdata ${WORK_DIR}/monitor --pgport 6000 --nodename localhost
```
It failed with
```
 LOG:  syntax error in file "/Users/mtuncer/dev/ha/test/monitor/postgresql-auto-failover.conf" line 4, near end of line
 FATAL:  configuration file "/Users/mtuncer/dev/ha/test/monitor/postgresql.conf" contains errors
```

when I checked `postgresql-auto-failover.conf` failure was port setting file with no value set.

```
port = 
```

I checked `monitor/pg_autoctl.cfg` that is stored in temporary cache. Port setting was correctly applied. We just failed to move that setting into `postgresql-auto-failover.conf`

I tested this with ubuntu, it was fine.
I also testhed v1.0.3 with mac which is also fine. It must be something we introduced along 1.0.4

**Comment by mtuncer** [comment]
Note : this is blocking my development at the moment

**Comment by mtuncer** [comment]
https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgctl.c#L425

seems to be the issue. It returns a value allocated on stack, this value is changed in subsequent function call.

**Comment by DimCitus** [comment]
See https://github.com/citusdata/pg_auto_failover/pull/59/commits/eeeaed44fd8bb5246cfa006374353ba1892c6630 ; I think we should get this out of my WIP branch to master one and re-schedule our release plan. I though I shared that with you last week already, in an email or something, I'm sorry if you missed it?

**Comment by mtuncer** [comment]
yeah I remember the diff but I could not find it afterwards. We should get this change separately and preferably soon.
