### ISSUE TITLE
Feature: Clean up unmanaged replication slots

### ISSUE THREAD

**Issue by giner** [citusdata/pg_auto_failover#602]
To run an external to the cluster consumer (such as [Barman](https://github.com/2ndquadrant-it/barman)) we have to create a replication slot. Everything is fine until the first failover happens and Barman re-connects to the new primary node. The previous primary and now standby PostgreSQL node keeps accumulating wal files for the Barman's replication slot unboundedly .

Would it make sense for pg_auto_failover to drop unknown replication slots from standby nodes which were not used for some time?

Ideally this should be handled by PostgreSQL itself however the closed thing I could find was `max_slot_wal_keep_size` which is only supported from PostgreSQL 13.

**Comment by DimCitus** [comment]
Hi @giner ; thanks for reporting an issue!

I think pg_auto_failover should refrain from managing replication slots that it knows nothing about. I agree with the risks involved, but on the other hand, the owner of the replication slot is in charge. The other risk is that when barman attempts to use the replication slot that it created, it's been dropped behind its back, and now you can't archive some of the WAL files and your archiving solution has holes in it...

**Comment by giner** [comment]
I see your point which makes sense to me. On the other hand this would require the client to know about all standby nodes and be able to connect to them directly in order to delete the replication slots.
