### ISSUE TITLE
Add PG_AUTOCTL_LISTEN_NOTIFICATIONS_TIMEOUT as a modifiable option

### ISSUE THREAD

**Issue by KennethcLee** [citusdata/pg_auto_failover#604]
Getting below error while performing `pg_autoctl perform switchover` on the monitor instance.

```
00:04:41 6265 ERROR Failed to receive monitor's notifications
00:04:41 6265 ERROR Failed to wait until a new primary has been notified
```

Database size: 10 GB
Transfer over LAN network
Both primary and standby are idle beside performing the switchover.

The switchover eventually completed successfully.
```
$ /usr/pgsql-11/bin/pg_autoctl show state
  Name |  Node |       Host:Port |          LSN | Reachable |       Current State |      Assigned State
-------+-------+-----------------+--------------+-----------+---------------------+--------------------
node_1 |     1 | postgres-0:5432 | 81F/90758658 |       yes |             primary |             primary
node_2 |     2 | postgres-1:5432 | 81F/90758658 |       yes |           secondary |           secondary
```

I believe it is the `#define PG_AUTOCTL_LISTEN_NOTIFICATIONS_TIMEOUT 60` setting.
[https://github.com/citusdata/pg_auto_failover/blob/5ef1078d20e2c99ffe7d9df7469836281d1e89d0/src/bin/pg_autoctl/defaults.h#L81](url)

Is there a way to allow that value to be modified?
[https://github.com/citusdata/pg_auto_failover/blob/e5ba4f08f8543dfd4ac9b217e6d8b86f091acea6/src/bin/pg_autoctl/keeper_config.c#L179-L212](url)

**Comment by DimCitus** [comment]
Hi @KennethcLee ; thanks for reporting an issue. At the moment the listen notification timeout is not exposed as something that you can tweak. We could easily enough add it the configuration file in our existing timeout section. I believe it's a nice first contribution opportunity. Do you want to have a try at it?
