### ISSUE TITLE
Spawning a secondary node requires pgdata createable, but there is no error message

### ISSUE THREAD

**Issue by Tjstretchalot** [citusdata/pg_auto_failover#605]
Essentially what happens is that pgdata is removed and then copied into, but it's not possible to remove the pgdata directory if the directory that `pgdata` is in doesn't have sufficient permissions for creating pgdata. In my case, I had pgdata set to `/pgdata`, and obviously the postgres user cannot delete and recreate that directory. This itself is fine, I moved it to `/postgres/pgdata`, but there is no error message

```
23:31:44 24638 INFO  Started pg_autoctl postgres service with pid 24641
23:31:44 24641 INFO   /usr/bin/pg_autoctl do service postgres --pgdata /pgdata -v
23:31:44 24638 INFO  Started pg_autoctl node-active service with pid 24642
23:31:44 24642 INFO  Continuing from a previous `pg_autoctl create` failed attempt
23:31:44 24642 INFO  PostgreSQL state at registration time was: PGDATA does not exists
23:31:45 24642 INFO  FSM transition from "wait_standby" to "catchingup": The primary is now ready to accept a standby
23:31:45 24642 INFO  Initialising PostgreSQL as a hot standby
23:31:45 24642 INFO   /usr/bin/pg_basebackup -w -d application_name=pgautofailover_standby_2 host=ip-10-1-3-188.us-west-2.compute.internal port=5432 user=pgautofailover_replicator sslmode=disable --pgdata /backup/node_2 -U pgautofailover_replicator --verbose --progress --max-rate 100M --wal-method=stream --slot pgautofailover_standby_2
23:31:45 24642 INFO  could not change directory to "/home/ec2-user": Permission denied
23:31:45 24642 INFO  pg_basebackup: initiating base backup, waiting for checkpoint to complete
23:31:45 24642 INFO  pg_basebackup: checkpoint completed
23:31:45 24642 INFO  pg_basebackup: write-ahead log start point: 0/3B000028 on timeline 1
23:31:45 24642 INFO  pg_basebackup: starting background WAL receiver
23:31:45 24642 INFO      0/24348 kB (0%), 0/1 tablespace (/backup/node_2/backup_label        )
23:31:45 24642 INFO  24357/24357 kB (100%), 0/1 tablespace (/backup/node_2/global/pg_control   )
23:31:45 24642 INFO  24357/24357 kB (100%), 1/1 tablespace
23:31:45 24642 INFO  pg_basebackup: write-ahead log end point: 0/3B000100
23:31:45 24642 INFO  pg_basebackup: waiting for background process to finish streaming ...
23:31:45 24642 INFO  pg_basebackup: syncing data to disk ...
23:31:45 24642 INFO  pg_basebackup: renaming backup_manifest.tmp to backup_manifest
23:31:45 24642 INFO  pg_basebackup: base backup completed
23:31:45 24638 WARN  pg_autoctl service node-active failed with exit status 0
```

I added some log statements in and verified that the program dies while trying to remove pgdata at https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/pgctl.c#L1208

Suggestion: Determine why it exits with status code 0, rather then emitting the log message on line 1210.

**Comment by godwhoa** [comment]
I think this is related to #313. 
Could you run  `pg_autoctl do service node-active` and see if you get a seg fault? 
Note: You need to set env. variable `PG_AUTOCTL_DEBUG=1` for that command to be available.
If it does segfault it is most likely the same issue, I have a [PR](https://github.com/citusdata/pg_auto_failover/pull/612) which tries to address it.

**Comment by DimCitus** [comment]
Hi @Tjstretchalot ; please read the Postgres documentation advice about where to place PGDATA at https://www.postgresql.org/docs/current/creating-cluster.html#CREATING-CLUSTER-MOUNT-POINTS 

> Many installations create their database clusters on file systems (volumes) other than the machine's “root” volume. If you choose to do this, it is not advisable to try to use the secondary volume's topmost directory (mount point) as the data directory. Best practice is to create a directory within the mount-point directory that is owned by the PostgreSQL user, and then create the data directory within that. This avoids permissions problems, particularly for operations such as pg_upgrade, and it also ensures clean failures if the secondary volume is taken offline.

Given that Postgres itself is better installed somewhere else, there is no reason why pg_auto_failover should be improved to work better when PGDATA is a top-level mount-point directory.
