### ISSUE TITLE
drop node not really drop 

### ISSUE THREAD

**Issue by laurent6** [citusdata/pg_auto_failover#608]
Hi, 
I've another issues. 
I have 3 nodes: 
node0: the monitor
node1 <=>node_16
node2 <=> node_17 

I want auto change state node. At the beginning  it'st work. node_16 promote to pimary and node_17 set secondary. I simulated breakdown node_16 but système not promote node_17 to primary. 
The first question Why not promot auto node_17 to primary when the first down ? 
After I drop node. The system change and the node_17 is single. 
Another issus when I restart node_16 ( delete and recreate it )

What can I forget or what worng in my config ? 

1] 
``` postgres@t-os-postgres-dev2:~$ pg_autoctl show state
   Name |  Node |           Host:Port |       LSN | Reachable |       Current State |      Assigned State
--------+-------+---------------------+-----------+-----------+---------------------+--------------------
node_16 |    16 | 192.168.10.166:5000 | 0/3000148 |       yes |             primary |             primary
node_17 |    17 |   192.168.10.5:5000 | 0/3000148 |       yes |           secondary |           secondary
```

2] breackdown node_16 

3] show state 
```postgres@t-os-postgres-dev2:~$ pg_autoctl show state
   Name |  Node |           Host:Port |       LSN | Reachable |       Current State |      Assigned State
--------+-------+---------------------+-----------+-----------+---------------------+--------------------
node_16 |    16 | 192.168.10.166:5000 | 0/3000148 |        no |             primary |      demote_timeout
node_17 |    17 |   192.168.10.5:5000 | 0/3000310 |       yes |    stop_replication |    stop_replication
....


postgres@t-os-postgres-dev2:~$ pg_autoctl show state
   Name |  Node |           Host:Port |       LSN | Reachable |       Current State |      Assigned State
--------+-------+---------------------+-----------+-----------+---------------------+--------------------
node_16 |    16 | 192.168.10.166:5000 | 0/3000148 |        no |             primary |             demoted
node_17 |    17 |   192.168.10.5:5000 | 0/3000310 |       yes |        wait_primary |        wait_primary

``` 
4] drop state
``` postgres@t-os-postgres-dev2:~$ pg_autoctl drop node  --hostname 192.168.10.166 --pgport 5000 node_16 ``` 

5] show state 
``` postgres@t-os-postgres-dev2:~$ pg_autoctl show state
   Name |  Node |         Host:Port |       LSN | Reachable |       Current State |      Assigned State
--------+-------+-------------------+-----------+-----------+---------------------+--------------------
node_17 |    17 | 192.168.10.5:5000 | 0/3000310 |       yes |              single |              single
``` 

6] I try to rexcreate node_16 
```
postgres@t-os-postgres-dev0:~/.config/pg_autoctl/var/lib/postgresql$ pg_autoctl create postgres \
>     --hostname  192.168.10.5\
>     --auth trust \
>     --ssl-self-signed \
>     --pgdata node_2 \
>     --pgport 5000\
>     --monitor 'postgres://autoctl_node@192.168.10.184:5000/pg_auto_failover?sslmode=require' \
>     --run >/tmp/node.log 2>&1 & 
[1] 875
postgres@t-os-postgres-dev0:~/.config/pg_autoctl/var/lib/postgresql$ tail -f  /tmp/node.log 
09:01:46 888 ERROR SQL query: SELECT * FROM pgautofailover.register_node($1, $2, $3, $4, $5, $6, $7, $8::pgautofailover.replication_state, $9, $10, $11)
09:01:46 888 ERROR SQL params: 'default', '192.168.10.5', '5000', 'postgres', '', '0', '-1', 'init', 'standalone', '50', 'true'
09:01:46 888 ERROR Failed to register node 192.168.10.5:5000 in group -1 of formation "default" with initial state "init", see previous lines for details
09:01:46 888 WARN  WARNING:  there is no transaction in progress
09:01:46 888 ERROR Failed to register the existing local Postgres node "192.168.10.5:5000" running at "node_2"to the pg_auto_failover monitor at postgres://autoctl_node@192.168.10.184:5000/pg_auto_failover?sslmode=require, see above for details
```

it'st just to have good procedure to auto  restart. I can resolved it with  change nodename to node_16  

  Another bug: when I change port in pg_autocl.cfg and run it again the state doesn't change. and isn't reachable

**Comment by DimCitus** [comment]
Hi @laurent6 ;

Please have a look at our documentation about states at https://pg-auto-failover.readthedocs.io/en/latest/failover-state-machine.html#state-reference. 

> The first question Why not promot auto node_17 to primary when the first down ?

It did. The node has reached the state `wait_primary`, which means it's accepting both reads and writes and your application can work normally. The node does NOT have a secondary at this moment though, so it is not labelled “primary”, because a failover can't happen anymore.

> After I drop node. The system change and the node_17 is single.

Again, that's expected. When you have a single node in the system, its state is `single`, and the nodes accepts read and writes, so your application is okay. Without a secondary node though, we can't implement failover, so it's not a primary node at this point.

The last error is strange and might require more diving. How can I reproduce this error, can you provide me with the whole script of things you did so that I can see if that's a bug and how to fix it?

**Comment by laurent6** [comment]
Hi,

**Comment by DimCitus** [comment]
Okay, so if you drop node_1 without the `--destroy` argument, you keep the PGDATA and pg_autoctl configuration file around, in case those are useful to you still. When you try to run the node_1, it's not registered anymore, so of course this doesn't work. You need to register the node again, with the `pg_autoctl create postgres` command.

That said, why drop a node and then re-add it? We support this only as the last step when everything else failed.

**Comment by DimCitus** [comment]
I @laurent6 ; would the PR at #617 help you with the new output? I'm trying to see if we can make things more obvious to new users...

```
$ pg_autoctl show state
 Name |  Node |      Host:Port |       LSN |   Connection |       Current State |      Assigned State
------+-------+----------------+-----------+--------------+---------------------+--------------------
node1 |     1 | localhost:5501 | 0/3000000 | read-write * |        wait_primary |        wait_primary
node2 |     2 | localhost:5502 |       0/0 |       none ? |        wait_standby |          catchingup
```
