### ISSUE TITLE
systemd template file do not provide reload

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#613]
pg_autoctl 1.4.1

```
sudo systemctl reload pgautomonitor
Failed to reload pgautomonitor.service: Job type reload is not applicable for unit pgautomonitor.service.
See system logs and 'systemctl status pgautomonitor.service' for details.
```

I used this :

```
pg_autoctl show systemd -q --pgdata "$PGDATA" | sudo tee /etc/systemd/system/${NOMSERVICEPGAUTO}.service
[Unit]
Description = pg_auto_failover

[Service]
WorkingDirectory = /home/postgres
Environment = 'PGDATA=/home/postgres/10/ipgsprd/'
User = postgres
ExecStart = /usr/pgsql-10/bin/pg_autoctl run
Restart = always
StartLimitBurst = 0

[Install]
WantedBy = multi-user.target

sudo systemctl daemon-reload
sudo systemctl enable pgautomonitor
sudo systemctl start pgautomonitor
```

In case reload is really  missing , can you provide the line to add to service file (just for manual fix)  (rhel 7) ?

Thank you

**Comment by jacks33** [comment]
I tried ExecReload=/bin/kill -HUP $MAINPID it seems to work

**Comment by DimCitus** [comment]
Can you test with using `/usr/pgsql-10/bin/pg_autoctl reload` instead? if that works, I'll need to write a patch to fix that in our systemd output.

**Comment by jacks33** [comment]
Mar 05 12:23:27 (in logs) 
It seems ok the output looks the same as with kill function:

[postgres-v10@T38A3 ipgsdev1:54320 /etc/systemd/system]$ sudo vi pgautomonitor.service
[postgres-v10@T38A3 ipgsdev1:54320 /etc/systemd/system]$ sudo systemctl daemon-reload
[postgres-v10@T38A3 ipgsdev1:54320 /etc/systemd/system]$ sudo systemctl reload pgautomonitor.service
[postgres-v10@T38A3 ipgsdev1:54320 /etc/systemd/system]$ sudo systemctl status -l pgautomonitor.service
● pgautomonitor.service - pg_auto_failover
   Loaded: loaded (/etc/systemd/system/pgautomonitor.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-03-05 11:16:49 CET; 1h 6min ago
  Process: 112253 ExecReload=/usr/pgsql-10/bin/pg_autoctl reload (code=exited, status=0/SUCCESS)
 Main PID: 62772 (pg_autoctl)
   CGroup: /system.slice/pgautomonitor.service
           ├─62772 /usr/pgsql-10/bin/pg_autoctl run
           ├─62778 pg_autoctl: start/stop postgres
           ├─62779 pg_autoctl: monitor listener
           ├─62797 /usr/pgsql-10/bin/postgres -D /home/postgres/10/ipgsprd -p 55555 -h *
           ├─62802 postgres: pg_auto_failover monitor: logger process
           ├─62805 postgres: pg_auto_failover monitor: checkpointer process
           ├─62806 postgres: pg_auto_failover monitor: writer process
           ├─62807 postgres: pg_auto_failover monitor: wal writer process
           ├─62808 postgres: pg_auto_failover monitor: autovacuum launcher process
           ├─62809 postgres: pg_auto_failover monitor: stats collector process
           ├─62810 postgres: pg_auto_failover monitor: bgworker: pg_auto_failover monitor
           ├─62811 postgres: pg_auto_failover monitor: bgworker: logical replication launcher
           ├─62812 postgres: pg_auto_failover monitor: bgworker: pg_auto_failover monitor worker
           ├─62814 postgres: pg_auto_failover monitor: bgworker: pg_auto_failover monitor worker
           └─62817 postgres: pg_auto_failover monitor: autoctl_node pg_auto_failover [local] idl

Mar 05 11:16:49 T38A3.cepme150.fr pg_autoctl[62772]: 11:16:49 62778 INFO  Postgres is now serving PGDATA "/home/postgres/10/ipgsprd" on port 55555 with pid 62797
Mar 05 11:16:49 T38A3.cepme150.fr pg_autoctl[62772]: 11:16:49 62779 INFO  The version of extension "pgautofailover" is "1.4" on the monitor
Mar 05 11:16:49 T38A3.cepme150.fr pg_autoctl[62772]: 11:16:49 62779 INFO  Contacting the monitor to LISTEN to its events.
Mar 05 12:23:27 T38A3.cepme150.fr systemd[1]: Reloading pg_auto_failover.
Mar 05 12:23:27 T38A3.cepme150.fr pg_autoctl[62772]: 12:23:27 62772 INFO  pg_autoctl received a SIGHUP signal, reloading configuration
Mar 05 12:23:27 T38A3.cepme150.fr pg_autoctl[62772]: 12:23:27 62772 INFO  Reloading service "postgres" by signaling pid 62778 with SIGHUP
Mar 05 12:23:27 T38A3.cepme150.fr pg_autoctl[62772]: 12:23:27 62772 INFO  Reloading service "listener" by signaling pid 62779 with SIGHUP
Mar 05 12:23:27 T38A3.cepme150.fr pg_autoctl[62772]: 12:23:27 62778 INFO  Reloading pg_autoctl postgres service [62797]
Mar 05 12:23:27 T38A3.cepme150.fr systemd[1]: Reloaded pg_auto_failover.
Mar 05 12:23:27 T38A3.cepme150.fr pg_autoctl[62772]: 12:23:27 62779 INFO  Reloaded the new configuration from "/home/postgres/.config/pg_autoctl/home/postgres/10/ipgsprd/pg_autoctl.cfg"
 
Just a question what is the service "listener" started by pg_autoctl ?

Thank you 

Tiago ANASTACIO

**Comment by DimCitus** [comment]
Hi Tiago, the pg_autoctl monitor listener service is the part that does the LISTEN part of the LISTEN/NOTIFY protocol, and outputs every state change to the logs.
