### ISSUE TITLE
Question reload and restart parameters

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#614]
Hello,

1 - For keeper and monitor is it possible to document wich parameters requires reload and wich restart (for pg_autoctl --config).
2 - Monitor extensions parameters all require a postgres reload. Do they require a reload/restart  of the monitor service as well ?
3 - Does pg_autoctl set,  trigg a reload (particulary when pg_autoctl service is launched as a systemd unit ) ?

Thank you very much.

**Comment by DimCitus** [comment]
1. See WIP at https://github.com/citusdata/pg_auto_failover/pull/632 and specifically https://github.com/citusdata/pg_auto_failover/blob/docs/ref-and-man-pages/docs/ref/pg_autoctl_config_set.rst. Does this answer your first question?

  2. Reload of the monitor Postgres instance is all that is needed.
  3. You can do several edits and then `pg_autoctl reload`.

**Comment by jacks33** [comment]
Merci Dimitri.

Perfect, I wonder if mention something like (you can use configuration tools) would be good (you already notice it elsewhere). 

Tiago

**Comment by DimCitus** [comment]
Well technically the pg_autoctl configuration file could be provided by a deployment tool, though in practice we lack a command that would do the setup all based on that file. In a way the command `pg_autoclt create postgres --run` could be used with most/all of the options read from the configuration file... but I'm not sure we can claim that this mode of operation (provision the configuration file separately) is fully supported by pg_autoctl at this time.

Did you try using a provisioning tool for the configuration and then start/restart/reload when the new version of the file has been synced? Does it work well?

**Comment by jacks33** [comment]
Hello, not yet we, but we are planning to use ansible in near time, for now weuse pg_autoctl create postgres and it helps very much.
