### ISSUE TITLE
Feature Request: skip management of pg_hba.conf

### ISSUE THREAD

**Issue by gmr** [citusdata/pg_auto_failover#62]
I'm using Ansible to manage my PostgreSQL nodes and have to account for the line added by pg_auto_failover to pg_hba.conf in my Ansible config.

The line is also much more permissive than I'd prefer to allow.

Having an option that is along the lines of "--skip-pg_hba" that lets me manage that when using "create monitor" and "create postgres" would be ideal.

**Comment by DimCitus** [comment]
Hi @gmr, this is something we have had in our internal list of wish list item and that was not given priority yet. I think it's fair to say we should have a look. Also it's a rather small contribution I believe, so if you would want to have a look I could provide help and guidance... otherwise I will just assign it to myself!

**Comment by Bouke** [comment]
I'm looking for something similar as well. We use Puppet to manage `pg_hba.conf`. Any modifications outside of puppet are seen as deviations from the desired config state and are removed. However this also triggers a restart of the postgres service to make the new config apply. When the pgautofailover service starts, it'll make the same changes to `pg_hba.conf`, and on the next run of Puppet it'll detect those changes, causing another restart. As a result, the primary role continuously moves back and forth both nodes, causing disruption. For now, I think I'll disable the automatically triggered restart, but that would require manual intervention when I want to change those rules.

**Comment by Markus-** [comment]
Anything new here?

**Comment by gmr** [comment]
Yeah, I've slowly been making requested changes, just have been very limited on my time to do so. Sorry!

**Comment by DimCitus** [comment]
Released now in version 1.2, `--skip-pg-hba`. Thanks for your contributions, enjoy the new release!
