### ISSUE TITLE
Can you publish the Docker images with release tags?

### ISSUE THREAD

**Issue by amontalban** [citusdata/pg_auto_failover#627]
Hi Citus team 👋 ,

I'm working on some web interface to view the state of a pg_auto_failover and I'm using your Docker image for my testing.

It was working properly (In 1.4.2) but looks like 1.5 will have some changes to the schema and therefore my app does not work properly.

I checked the Dockerhub releases but looks like the `latest` is always pointing to `master` branch and no other tags are available.

Also, I tried to find any reference to the Dockerhub publish process but looks like that is done off-band so I couldn't submit a PR for this.

It would be great if you can do release tagging also in Dockerhub so the users can do upgrade/downgrade testings, obviously, I know I can build the image myself but just pointing it out as a nice thing to have.

Thank you!

**Comment by DimCitus** [comment]
Hi @amontalban ; thanks for opening this issue! I have now changed the dockerhub settings to also maintain docker images for tags v1.5.1 and v1.4.2. I would love to see the web UI you're coming up with! Any way I can see it?
