### ISSUE TITLE
Unable to specify a different port

### ISSUE THREAD

**Issue by sacrophyte** [citusdata/pg_auto_failover#630]
When I try to use a non-default port, I get an error saying that the port I specified (which is utterly incorrect) does not match the correct port number.

```
[postgres@urblimsdbdev2b ~]$ PGPORT=5433
[postgres@urblimsdbdev2b ~]$ pg_autoctl run --pgdata `pwd`/12/d1 --pgport 5433
10:49:23 909947 ERROR Given --pgport 5432 doesn't match PostgreSQL port 5433 from "/var/lib/pgsql/12/d1/postmaster.pid"
10:49:23 909947 FATAL Failed to discover PostgreSQL setup, please fix previous errors.
```

**Comment by DimCitus** [comment]
Hi @sacrophyte,

Which version of pg_auto_failover are you using? In versions 1.4.x and more recent, `pg_autoctl` is supposed to be the parent process of Postgres, which means that we expect `pg_autoctl run` to start Postgres and use the `--pgport` option when doing so.

It seems that in your case here Postgres already runs in the background when `pg_autoctl run` is used. That situation is supported to install pg_auto_failover on a pre-existing Postgres instance, though it's not the expected scenario. In that situation, please adjust the Postgres port number in the `pg_autoctl` setup to the actual already-running Postgres port.
