### ISSUE TITLE
pg_auto_failover 1.4.2 in yum.postgresql.org

### ISSUE THREAD

**Issue by allanharry** [citusdata/pg_auto_failover#631]
Hi 

Unfortunately I can only fetch pg_auto_failover from yum.postgresql.org but latest version 1.4.2 not available yet from there.
Alternatively I have to compile it from source.
Possible to have 1.4.2 available in yum.postgres.org ?

Regards Allan

**Comment by DimCitus** [comment]
Hi @allanharry ; we don't maintain packages for yum.postgresql.org.
