### ISSUE TITLE
clarifications on perform failover and promote

### ISSUE THREAD

**Issue by jacks33** [citusdata/pg_auto_failover#634]
Hello,

We understand switchover is a failover then a faillback.
We used a two cluster node  pg_autofailover 1.4.1 / rhel 7 /PG10

we tried perform failover and perform promote. 
They had the same behaviour : when standby is not reachable both commands fail.

Could you please clarify the behaviour and the use cases for these two commands ?

Thank you.

**Comment by DimCitus** [comment]
Hi @jacks33,

A switchover is the same as a “controlled failover”, which is a kind of a failover scenario where the primary we switch from is still online rather than unavailable. If you have two nodes registered and the standby isn't available, then we can't failover, and we can't switchover.
