### ISSUE TITLE
fail to upgrade from 1.5.0.1 to 1.5

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#657]
```log
10:19:45 632 INFO  Managing the monitor at postgres://autoctl_node@tasks.monitor:5432/pg_auto_failover?sslmode=prefer
10:19:45 632 INFO  Reloaded the new configuration from "/home/.config/pg_autoctl/tmp/pg_data/pg_autoctl.cfg"
10:19:45 632 INFO  Reloading Postgres configuration and HBA rules
10:19:46 632 WARN  This version of pg_autoctl requires the extension "pgautofailover" version "1.5" to be installed on the monitor, current version is "1.5.0.1".
10:19:46 632 ERROR Error 22023 while running Postgres query: ALTER EXTENSION "pgautofailover" UPDATE TO "1.5": ERROR:  extension "pgautofailover" has no update path from version "1.5.0.1" to version "1.5"
10:19:46 632 FATAL Failed to update extension "pgautofailover" to version "1.5" on the monitor, see above for details
10:19:46 42 WARN  pg_autoctl service listener exited with exit status 0
10:19:46 42 INFO  Restarting service listener
10:19:46 647 INFO   /usr/local/bin/pg_autoctl do service listener --pgdata /tmp/pg_data -v```

**Comment by DimCitus** [comment]
Hi @RekGRpth ; the 4-digit version numbers such as 1.5.0.1 and 1.5.0.2 have been only used in the development version of pg_auto_failover. Meaning in the `master` branch of the git repository, and never part of a release. When preparing the release we removed support for those versions and we have 1.4.2 to 1.5.1 upgrade path, and 1.5.0.x are not part of the repository anymore.

I suppose you've been using 1.5.0.1 on a lab / development / testing environment. To upgrade to 1.5.1 you will need to reinstall pg_auto_failover from scratch.

**Comment by RekGRpth** [comment]
Which branch I should use instead of master?

**Comment by DimCitus** [comment]
That depends on why you're using a development version instead of a released version... what are you trying to achieve?

**Comment by RekGRpth** [comment]
Which branch correspond release version? (as in postgres for example it is REL_13_STABLE)

**Comment by DimCitus** [comment]
We're a much smaller team than Postgres, and so we typically only maintain one current stable version. We don't have stable branches, only tags, and you can see that in the GitHub release tab at https://github.com/citusdata/pg_auto_failover/releases.
