### ISSUE TITLE
how do I connect to database from my application or psql ?

### ISSUE THREAD

**Issue by changchichung** [citusdata/pg_auto_failover#66]
I follow the readme to build a monito-primary-secondary cluster 
now replication is working , and when I shutdown primary, the secondary server will take over , and when the old primary comes back , it will join to the cluster as secondary , and the original secondary will promote to primary server , that's perfect !!
but I don't know to to connect to the database ??
I think it should not be connect via primary ip or secondary ip , if so , when the node goes down , the connection will fail.
in readme , it says connect URI is somewhing like
```
postgres://autoctl_node@monitor:5432/pg_auto_failover
```
yes , I can connect to the URI , but via that URI , I can not connect to the database which I just created in cluster.

so , what URI should I use in application or psql connect string ?

**Comment by DimCitus** [comment]
Hi @changchichung,

For documentation purposes, your issue has a misunderstanding between the monitor connection string and the main database connection string. You can retrieve the connection string to use for the application with the following command, as per documentation at https://pg-auto-failover.readthedocs.io/en/latest/ref/reference.html#pg-autoctl-show-command

    pg_autoctl show uri --formation default

If you're using another name for the formation, of course, change it in the command above.
