### ISSUE TITLE
xmin stuck at old transaction (vacuum can't remove dead rows)

### ISSUE THREAD

**Issue by porsager** [citusdata/pg_auto_failover#662]
Hi.

I have a setup with 1 standby node and an async standby node.

I'm finding that there are a lot of dead rows that can't be removed by vacuum, and I think I've found the issue to be the replication slot of the standby hanging on to an old transaction. It's `xmin` value is very far behind (339515 vs 1606623). 

I don't know where to look now, and I'm not entirely sure this is an actual issue, but I was hoping you might have some pointers?

Output from `pg_replication_slots`

```
slot_name                       active  active_pid  xmin        restart_lsn
pgautofailover_standby_1	TRUE	1251321	    339515	A/2493B440
pgautofailover_standby_3	TRUE	1251320	    1606623	A/2493B440
```

Output of `show state`

```
      Name |  Node |      Host:Port |        LSN |   Connection |       Current State |      Assigned State
-----------+-------+----------------+------------+--------------+---------------------+--------------------
postgres-a |     1 | 10.0.0.11:5432 | A/2493B440|    read-only |           secondary |           secondary
postgres-b |     2 | 10.0.0.12:5432 | A/2493B440|   read-write |             primary |             primary
postgres-c |     3 | 10.0.0.13:5432 | A/2493B440|    read-only |           secondary |           secondary
```

**Comment by DimCitus** [comment]
Hi @porsager ; thanks for using pg_auto_failover and opening an issue here. This is a new case to me. You can safely drop the replication slot `pgautofailover_standby_1` on the node where you're observing the situation, and pg_autoctl will create the slot again for you, automatically. With luck the xmin problem will just have disappeared.

Use the SQL function `pg_drop_replication_slot ` (see https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-REPLICATION) to drop a replication slot.

**Comment by porsager** [comment]
Thanks a lot for reply Dimitri.

`pg_drop_replication_slot` errored with `ERROR:  replication slot "pgautofailover_standby_1" is active for PID 1251321`, so I took down the standby node for maintenance, but there was still an active_pid on the replication slot, so I stopped the postgresql service. 

That allowed me to run `pg_drop_replication_slot` successfully, but after bringing the standby node up again it got xmin `339515` again.

**Comment by porsager** [comment]
Interesting. 

So even though `xmin` didn't change, the dead rows could now be vacuumed. I haven't done anything but the above, so I think it was somehow related to the standby holding on to the dead rows.

I don't really have any ideas to investigate more, but I'm still curious why `xmin` is that far behind.

**Comment by porsager** [comment]
It's been a little while now, and this issue keeps coming back for us. Dead tuples won't be removed until I do a failover, and `xmin` keeps hanging at that old value of 339515 for the hot standby. I actually don't think this is related to pg_auto_failover, so we can probably close this issue, but if someone has ideas for how to proceed investigating I'd love to hear.

**Comment by porsager** [comment]
This is not the best ending, since I don't have an answer for what caused the stuck xmin in pg_replication_slots, but it's fixed itself now. I only just found out now, unrelated to any changes, but my best bet is that it happened during a failed update from 1.5 to 1.6 about a week ago.

Oh well - closing for now.
