### ISSUE TITLE
How to set up on debian

### ISSUE THREAD

**Issue by googol** [citusdata/pg_auto_failover#668]
I'm setting pg_auto_failover up on debian, but I'm running into problems with the debian layout for postgres, with the data files (in `/var/lib/postgresql/<version>/<name>´) being separated from the configuration (in `/etc/postgresql/<version>/<name>`). 

Seems like `pg_autoctl` doesn't have support for this, as it wriites its configuration in the data directory and fails when it tries to modify the `postgres.conf` to include the extension config.

Is this layout supported in some way? If yes, how do I get `pg_autoctl` to work with the layout? Otherwise, what is your suggested workaround?

**Comment by googol** [comment]
We're using the postgresql apt repository for installing postgres (https://www.postgresql.org/download/linux/debian/)

**Comment by DimCitus** [comment]
I believe https://github.com/citusdata/pg_auto_failover/pull/681 should fix it. Closing. Consider opening with more information if your issue isn't solved entirely.
