### ISSUE TITLE
Citus does not recognise failover of worker nodes in the citus_nodes table.

### ISSUE THREAD

**Issue by hvvit** [citusdata/pg_auto_failover#670]
we have a streaming replication of workers in pg_autofailover and we have added the nodes in citus as primary and secondary as per the formation of pg_autofailover. When we restart the worker node the primary node changes. The effect of the restart can be seen in the pg_autofailover table but the same is not replicated in the citus node table, hence we have to go and manually update the citus_node as primary.

for creating citus-controller formation in pg_autofailover,
pg_autoctl create formation --formation citus-controller --kind pgsql --dbname pg_citus_controller --enable-secondary --monitor 'postgres://autoctl_node@xxx.xxx.xxx.xxx:xxx/pg_auto_failover?sslmode=prefer'

for the worker node we create it using the command,
pg_autoctl create formation --formation citus-worker --kind citus --dbname pg_citus_worker --disable-secondary  --monitor 'postgres://autoctl_node@xxx.xxx.xxx.xxx:xxxx/pg_auto_failover?sslmode=prefer'

under the citus-worker formation we add two machines primary-worker-node and secondary-worker-node,

then i use the command
select * from citus_add_node('primary-worker-node', 12345);
to add new worker node as primary

then i use the command
select * from citus_add_secondary_node('secondary-worker-node', 12345, 'primary-node', 12345);
this adds the secondary machine as secondary machine as failover in citus node table...

But it in this case whenever there is a switchover the same is not reflected in the citus_node_table

**Comment by Navid2zp** [comment]
Hello,  @hvvit

I had the same problem. Wrote a simple program to monitor the changes and then update the primary worker for citus.
It's fairly new and probably not tested as much but it might help:

https://github.com/Navid2zp/citus-failover

**Comment by hvvit** [comment]
Thank you @Navid2zp , I also approached on the same solution...amazing work...Thanks again.
