### ISSUE TITLE
memory leak in process pg_autoctl: node active

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#679]
memory leak in process pg_autoctl: node active
over 2 Gb RES by one day!

**Comment by RekGRpth** [comment]
pg_autoctl from git in docker alpine

**Comment by JelteF** [comment]
Which commit did you use from git? There have been a few memory leak fixes in the past couple of weeks, but they have not been released yet.

**Comment by RekGRpth** [comment]
> Which commit did you use from git?

last

**Comment by RekGRpth** [comment]
> There have been a few memory leak fixes in the past couple of weeks

some times ago everything is been ok

**Comment by RekGRpth** [comment]
since 25 April process pg_autoctl: node active eat over 9 Gb!

**Comment by JelteF** [comment]
Thanks for the report, we are working through a list of valgrind issues in the linked PR.

**Comment by RekGRpth** [comment]
I don't use passwords in uri

**Comment by JelteF** [comment]
The leak was in checking if there was a password in the URL, it doesn't matter if there is or is not. So you would still be affected by this leak.

**Comment by RekGRpth** [comment]
about hour the size of process pg_autoctl: node active is about 7 Mb

**Comment by RekGRpth** [comment]
again memory leak in process pg_autoctl: node active
over 415 Mb RES by 5 day!

**Comment by DimCitus** [comment]
> again memory leak in process pg_autoctl: node active
> over 415 Mb RES by 5 day!

Thanks for re-opening the issue, I just did another round of valgrind checks and we fixed a couple of leaks that way. The current approach would be to run those valgrind checks at release preparation time. Please keep testing and re-opening either this PR or another one when you witness memory leaks though, that's appreciated!
