### ISSUE TITLE
pg_auto_failover monitor.  Single point of failure

### ISSUE THREAD

**Issue by cmolatch** [citusdata/pg_auto_failover#702]
I installed pg_auto_failover monitoring the primary and two slaves.  The failover works great, however, what happens when the monitor fails.  Is there a configuration available to a secondary monitor?  I'm using version 1.4.  Thank you

**Comment by DimCitus** [comment]
Hi @cmolatch ; thanks for your interest in pg_auto_failover. Did you read the FAQ entry related to the monitor being a SPOF in the documentation, at https://pg-auto-failover.readthedocs.io/en/master/faq.html#the-monitor-is-a-spof-in-pg-auto-failover-design-how-should-we-handle-that ?

If you didn't, hopefully this contains all the answers you are looking for. If not, please consider opening this issue again with the questions you still have!

**Comment by cmolatch** [comment]
thank you Dimitri for the link.  I will give it a try.

**Comment by dblife1024** [comment]
> thank you Dimitri for the link. I will give it a try.


you can search “replacing-monitor-online”

https://pg-auto-failover.readthedocs.io/en/v2.0/operations.html#replacing-monitor-online
