### ISSUE TITLE
no auto start after reboot with default systemd configuration ?

### ISSUE THREAD

**Issue by changchichung** [citusdata/pg_auto_failover#71]
OS: ubuntu 18.04
pg_autofailover: 1.0.4

I follow the document to create a systemd file using command
```
pg_autoctl -q show systemd --pgdata "/var/lib/postgresql/11/main" | sudo tee /etc/systemd/system/pgautofailover.service
```
and the pgautofailover.service
```
2019-09-20 16:52:55 [administrator@pg-slave ~]$ sudo cat /etc/systemd/system/pgautofailover.service 
[Unit]
Description = pg_auto_failover

[Service]
WorkingDirectory = /var/lib/postgresql/11/main
Environment = 'PGDATA=/var/lib/postgresql/11/main'
User = postgres
ExecStart = /usr/bin/pg_autoctl run
Restart = always
StartLimitBurst = 0

[Install]
WantedBy = multi-user.target
```
I can control pg_autofailover manually with systemd , like
```
sudo systemctl stop pgautofailover
sudo systemctl start pgautofailover
```
but when the node goes to reboot , pgautofailover not automatically start
I have to login to node and do  sudo systemctl start pgautofailover 

any suggestions ?

**Comment by changchichung** [comment]
I change the way to manage pg_auto_failover service to supervisor. and everything works great !
I will not use systemd configuration for now , but I hope this issue could be fixed .

**Comment by nats** [comment]
You need to enable the service to run at boot:
systemctl enable pgautofailover

**Comment by changchichung** [comment]
Yes, I know that,and I already do that, but it’s just not working

**Comment by KeynesLee** [comment]
I got the same issue too. 

My environment is 
  CentOS 7.7  
  Postgresql 12
  pg_autofailover: 1.0.5
  
I found the issue was caused  by "systemd" cannot bring up postgresql up, then the pgautofailover daemon continuously to restart.

**Comment by philipmattingly** [comment]
Same Issue as KeynesLee:
CentOS 7.5
Postgresql: 11
pg_autofailover: 1.0.5

It always spins in a loop attempting to start postgresql inside of systemd. just repeats the base copy since it fails to start and can't pg_rewind.. very frustrating, I run the process is a detached gnu screen/tmux in the mean time ala 1997, until I can figure out why systemd fails to start the db via subcmds ran by pg_autoctl or a different process manager
