### ISSUE TITLE
how to join a new node to exists cluster when one of the nodes was failure?

### ISSUE THREAD

**Issue by changchichung** [citusdata/pg_auto_failover#72]
I already build a cluster with 3 nodes , and I want to simulate that one of the nodes were permanently failure and I want to join a new node to the cluster to replace the failure one.

so I shutdown one of the nodes , create a new node , and run the command 
```
sudo runuser -l postgres -c "pg_autoctl create postgres --pgdata /var/lib/postgresql/11/main --pgport 5432 --nodename pg-third --monitor postgres://autoctl_node@monitor:5432/pg_auto_failover"
```

here comes the error
```
14:38:03 ERROR Failed to execute "SELECT * FROM pgautofailover.register_node($1, $2, $3, $4, $5, $6::pgautofailover.replication_state, $7)": ERROR:  group 0 already has 2 members

14:38:03 ERROR Failed to register node pg-third:5432 in group 0 of formation "default" with initial state "init", see previous lines for details
14:38:03 ERROR Failed to register the existing local Postgres node "pg-third:5432" running at "/var/lib/postgresql/11/main"to the pg_auto_failover monitor at postgres://autoctl_node@monitor:5432/pg_auto_failover, see above for details
```

maybe the process should be remove a node using pg_autoctl drop node first , then join the new node , but that command can only drop the host self, not able to drop other node in cluster . BUT , the node need to be drop was already dead and unrecoverable , then how to drop the dead node and join a new node into the cluster  ?

**Comment by DimCitus** [comment]
In the documentation at https://pg-auto-failover.readthedocs.io/en/latest/operations.html#operations you can see a part of the SQL API that is available on the monitor. One of the functions you can call there is `pgautofailover.remove_node()`. That's how you remove a node that does not exists anymore.

Then you're right, this `remove_node` call needs to happen before attempting to create a new node.

**Comment by changchichung** [comment]
thanks for reply , I had read that document for several times , but I can not find any keyword of "remove" or how to use remove_node . is there any other documents to show the SOP of remove_node ?

**Comment by DimCitus** [comment]
Hi,

The `remove_node` function does not appear to be covered in the documentation at this moment, I will have to take care of that. Meanwhile here's the link to its SQL definition (that you can obtain with `\df` on the monitor when connected with `psql`):

  https://github.com/citusdata/pg_auto_failover/blob/master/src/monitor/pgautofailover.sql#L218

**Comment by DimCitus** [comment]
We have released pg_auto_failover with multiple standby nodes support now, closing this issue.
