### ISSUE TITLE
Restoring a pg_basebackup coming from a cluster with primary and secondary into a single node should set synchronous_standby_names to ''

### ISSUE THREAD

**Issue by s4ke** [citusdata/pg_auto_failover#721]
This is something that came up with our experiments in migrating our cluster from 1.3 to 1.5.

Our process is essentially as follows:

1. create cluster as is with a single primary
3. disable monitor on primary with --force on it `pg_autoctl disable monitor --force --pgdata /var/lib/postgresql/12/main_cluster/`
4. stop pg_autoctl service with `sudo service postgresql_main_cluster stop`
5. ensure postgres is actually stopped by running `/usr/lib/postgresql/12/bin/pg_ctl stop --pgdata /var/lib/postgresql/12/main_cluster/` and double check it with `psql -p 5433`
6. keep a backup of the old pgdata dir `cp -r /var/lib/postgresql/12/main_cluster/ /var/lib/postgresql/12/main_cluster_backup/`
7. destroy data with `pg_autoctl drop node --destroy --pgdata /var/lib/postgresql/12/main_cluster/`
7. `rm -rf /var/lib/postgresql/12/main_cluster/`
8. `mkdir /var/lib/postgresql/12/main_cluster/ && chmod 700 /var/lib/postgresql/12/main_cluster/`
7. `tar xvf /home/vagrant/basebackup_test/pg_basebackup/base.tar.gz -C /var/lib/postgresql/12/main_cluster/`
8. `tar xvf /home/vagrant/basebackup_test/pg_basebackup/pg_wal.tar.gz -C /home/postgres/backup_wal`
10. `rm /var/lib/postgresql/12/main_cluster/postgresql.auto.conf && touch /var/lib/postgresql/12/main_cluster/postgresql.auto.conf`
11. `rm /var/lib/postgresql/12/main_cluster/postgresql-auto-failover-standby.conf`
12. `rm /var/lib/postgresql/12/main_cluster/postgresql-auto-failover.conf && touch /var/lib/postgresql/12/main_cluster/postgresql-auto-failover.conf`
12. remove lines in postgresql.conf that include `postgresql-auto-failover-standby.conf` and `postgresql-auto-failover.conf`
9. put `restore_command = 'cp /home/postgres/backup_wal/%f "%p" '` into postgresql.auto.conf
10. `rm /var/lib/postgresql/12/main_cluster/standby.signal`
11. `touch /var/lib/postgresql/12/main_cluster/recovery.signal`
12. `cp /var/lib/postgresql/12/main_cluster_backup/pg_ident.conf /var/lib/postgresql/12/main_cluster/pg_ident.conf`
13. `cp /var/lib/postgresql/12/main_cluster_backup/pg_hba.conf /var/lib/postgresql/12/main_cluster/pg_hba.conf`
12. `PATH=$PATH:/usr/lib/postgresql/12/bin/ pg_autoctl create postgres --pgdata /var/lib/postgresql/12/main_cluster --skip-pg-hba --formation default --ssl-ca-file /data/ansible/certs/postgres_server/rootCA.crt --server-key /data/ansible/certs/postgres_server/server.key --server-cert /data/ansible/certs/postgres_server/server.crt --hostname 10.0.0.11 --name 10.0.0.11 --pghost 10.0.0.11 --pgport 5433 --monitor postgres://autoctl_node@10.0.0.10:5433/pg_auto_failover`
10. `sudo service postgresql_main_cluster start`
8. verify primary and monitor can talk to each other
9. create secondary (optional)

As you can see in the list above, we have to remove the config in postgresql.auto.conf in order for this process to work. This is because the backup includes `synchronous_standby_names = '*'`. I guess the problem is that if we are initializing a single node from a backup coming from a cluster, pg_autoctl does not change `synchronous_standby_names` to `''`. Could we maybe include this as a step when creating a new cluster which usually starts off with a single node anyways?

**Comment by s4ke** [comment]
I guess killing all auto.conf files might be overkill, but we wanted to be sure that we dont have any stale configs from the original cluster in there.

**Comment by DimCitus** [comment]
Hi @s4ke ; thanks for the very detailed context. I see that in some cases in `fsm.c` we already disable sync rep:

``` c
	/*
	 * other node(s) was forcibly removed, now single
	 */
	{ PRIMARY_STATE, SINGLE_STATE, COMMENT_PRIMARY_TO_SINGLE, &fsm_disable_replication },
	{ WAIT_PRIMARY_STATE, SINGLE_STATE, COMMENT_PRIMARY_TO_SINGLE, &fsm_disable_replication },
	{ JOIN_PRIMARY_STATE, SINGLE_STATE, COMMENT_PRIMARY_TO_SINGLE, &fsm_disable_replication },
```

I believe we should make sure that the transition functions (in `src/bin/pg_autoctl/fsm_transition.c`) used in all transitions that lead to SINGLE_STATE should include a call to either `fsm_disable_replication` or maybe directly `primary_disable_synchronous_replication`, depending on what's happening there already.

This looks to me as a good way to get started contributing to pg_auto_failover. Do you want to try it?

**Comment by s4ke** [comment]
@DimCitus If I were to do this, I could start in 1 month the earliest as I have other things on my schedule right now. Then, since I haven't developed much directly in C I would at least need some getting used to the tooling et al. Maybe some other issue in the future, though ;)
