### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint "node_nodename_nodeport_key"

### ISSUE THREAD

**Issue by adiep-cdpq** [citusdata/pg_auto_failover#73]
I'm running the monitor and the master in two Docker container on a container orchestrator. The first deployment works great. The master registers itself on the monitor node. But as soon as I kill the master node container and start it again, it can't register itself anymore and gives me this error. 
```
16:47:05 ERROR Failed to execute "SELECT * FROM pgautofailover.register_node($1, $2, $3, $4, $5, $6::pgautofailover.replication_state, $7)": ERROR:  duplicate key value violates unique constraint "node_nodename_nodeport_key"
DETAIL:  Key (nodename, nodeport)=(_mymasternodename_, 5432) already exists.
CONTEXT:  SQL statement "INSERT INTO pgautofailover.node (formationid, groupid, nodename, nodeport, goalstate, reportedstate) VALUES ($1, $2, $3, $4, $5, $6) RETURNING nodeid"
```

I start my node with the following command :
`su postgres -c 'pg_autoctl create postgres --pgctl /usr/lib/postgresql/11/bin/pg_ctl --pgdata /home/postgres/data --monitor postgres://autoctl_node@_mymonitornodename_:5432/pg_auto_failover --nodename _mymasternodename_'`

**Comment by adiep-cdpq** [comment]
Found the problem. Because it is running in a container, the pgdata folder gets created with the container and pg_auto_failover tried to create a new postgres instance(because it is a new pgdata folder), with the same nodename as before, which raises the error above.

**Comment by DimCitus** [comment]
Hi @adiep-cdpq ; the `pg_autoctl create postgres` step is only supposed to happen once in the whole lifetime of the server. At boot time, you can `pg_autoctl run` instead. So if you have a provisioning step for your containers, the `create` step should run when provisioning, not at each boot.

About the volume, it is considered that any Postgres volume is persistent yes. If that's not the case for you, I encourage you to find a way to make it the case. Any other integration will be open to data loss, which usually is not welcomed in the case of a database service.

**Comment by adiep-cdpq** [comment]
Alright, I will find a way to do that. Thank you! I will close this issue.
