### ISSUE TITLE
pg_autoctl perform switchover --formation <formation_name> runs on incorrect formation

### ISSUE THREAD

**Issue by agrahamlincoln** [citusdata/pg_auto_failover#741]
## Background

Brief topology of our setup:

api-0: default formation primary
zkjc-0: default formation secondary
monitor-0: monitor node
c-worker-0-p: citus_shard_0 formation primary
c-worker-0-s: citus_shard_0 formation secondary

## What happened?

When running `pg_autoctl perform switchover --formation citus_shard_0` on api-0, I found that the `default` formation was failed over, instead of the formation I specified.

```$ pg_autoctl perform switchover --formation citus_shard_0
22:40:02 31448 INFO  Targetting group 0 in formation "default"
22:40:02 31448 INFO  Listening monitor notifications about state changes in formation "default" and group 0
22:40:02 31448 INFO  Following table displays times when notifications are received
    Time |   Name |  Node |   Host:Port |       Current State |      Assigned State
---------+--------+-------+-------------+---------------------+--------------------
22:40:02 | node_8 |     8 |  api-0:5432 |             primary |            draining
22:40:02 | node_9 |     9 | zkjc-0:5432 |           secondary |   prepare_promotion
22:40:02 | node_9 |     9 | zkjc-0:5432 |   prepare_promotion |   prepare_promotion
22:40:02 | node_9 |     9 | zkjc-0:5432 |   prepare_promotion |    stop_replication
22:40:02 | node_8 |     8 |  api-0:5432 |             primary |      demote_timeout
22:40:02 | node_8 |     8 |  api-0:5432 |            draining |      demote_timeout
22:40:02 | node_8 |     8 |  api-0:5432 |      demote_timeout |      demote_timeout
22:40:03 | node_9 |     9 | zkjc-0:5432 |    stop_replication |    stop_replication
22:40:03 | node_9 |     9 | zkjc-0:5432 |    stop_replication |        wait_primary
22:40:03 | node_8 |     8 |  api-0:5432 |      demote_timeout |             demoted
22:40:03 | node_8 |     8 |  api-0:5432 |             demoted |             demoted
22:40:03 | node_9 |     9 | zkjc-0:5432 |        wait_primary |        wait_primary
22:40:03 | node_8 |     8 |  api-0:5432 |             demoted |          catchingup
22:40:15 | node_8 |     8 |  api-0:5432 |          catchingup |          catchingup
22:40:15 | node_8 |     8 |  api-0:5432 |          catchingup |           secondary
22:40:15 | node_8 |     8 |  api-0:5432 |           secondary |           secondary
22:40:15 | node_9 |     9 | zkjc-0:5432 |        wait_primary |             primary
22:40:16 | node_9 |     9 | zkjc-0:5432 |             primary |             primary
```

this is scary, because I never wanted to operate on the 'default' formation, but it didn't even warn it just went ahead and did it.

When I run the switchover from the monitor node, the correct formation is selected.

## What did I expect?

I expect the command to fail (because the current host is part of a different formation than specified), or for the switchover to be performed against the correct formation.

Running against a different formation than requested seems like it would always be unintentional.

## Question for developers

If I attempt to perform a switchover on a host that is part of a formation, will it always act on the current formation, and ignore the formation specified?

**Comment by DimCitus** [comment]
Hi @agrahamlincoln ; thanks for opening this issue, and for your patience. Please consider providing the following additional information about your situation:

  1. What version of pg_auto_failover are you using?
  2. Can you paste the output of the command `pg_autoctl show state --formation citus_shard_0`
  3. Can you paste the output of the command `pg_autoctl perform switchover -vvv --formation citus_shard_0`

Meanwhile I will try to reproduce the error locally and see what happens when using multiple formations.

**Comment by DimCitus** [comment]
Closing for trade purposes. Feel free to open again with more information and the answers to my questions above.
