### ISSUE TITLE
BUG: requested to open an already open connection in non PGSQL_CONNECTION_MULTI_STATEMENT mode

### ISSUE THREAD

**Issue by JelteF** [citusdata/pg_auto_failover#746]
When using make cluster I got this error on the primary:
![image](https://user-images.githubusercontent.com/1162278/123952274-17154300-d9a6-11eb-99fa-9f6fd23241ae.png)

**Comment by JelteF** [comment]
this might be related too, the monitor starts up much slower on current master than on 1.5.2:
![image](https://user-images.githubusercontent.com/1162278/124144459-48683e80-da8c-11eb-9d34-7a3aafc564dc.png)

**Comment by JelteF** [comment]
A few extra logs for some more context:
![image](https://user-images.githubusercontent.com/1162278/124251840-a21d4700-db26-11eb-89ac-afdf0fff1e91.png)

**Comment by DimCitus** [comment]
I believe this is all solved now thanks to your work in #751 and #752.
