### ISSUE TITLE
"/usr/bin/ld: cannot find -lXXXX" build error on Ubuntu 20.04

### ISSUE THREAD

**Issue by linto2528** [citusdata/pg_auto_failover#760]
I tried pg_auto_failover in Ubuntu 20.04.2 LTS
psql server 12.7
and follwed the below shared steps...

```
#  curl https://install.citusdata.com/community/deb.sh | sudo bash
#  apt-get install postgresql-12-auto-failover-1.4
#  /usr/bin/pg_autoctl --version
```

and got the installation confirmation as

```
# pg_autoctl version 1.4.2
pg_autoctl extension version 1.4
compiled with PostgreSQL 13.1 (Ubuntu 13.1-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
compatible with Postgres 10, 11, 12, and 13
```

after running the command,

```
#  sudo apt-get install postgresql-server-dev-12 libssl-dev libkrb5-dev
```

cloned the repo

```
git clone https://github.com/citusdata/pg_auto_failover.git
```

even I have installed almost all the libs

```
#  apt-get install clang
#  apt install libgl-dev libglu-dev libglib2.0-dev libsm-dev libxrender-dev libfontconfig1-dev libxext-dev
```

while go for  **make** getting this error 

```
/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
/usr/bin/ld: cannot find -lxslt
/usr/bin/ld: cannot find -lxml2
/usr/bin/ld: cannot find -lpam
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -ledit
/usr/bin/ld: cannot find -lreadline
collect2: error: ld returned 1 exit status
```

**Comment by DimCitus** [comment]
Hi @linto2528 ; thanks for trying pg_auto_failover out!

I am not sure to follow, what's your goal here? do you want to use pg_auto_failover from our binary packages, or do you want to build the project yourself, maybe contribute to it? Those two approaches are quite different, and your report here seems to be mixing them.

**Comment by linto2528** [comment]
Hi,
I was trying to setup pg_auto_failover from your binary packages.

**Comment by DimCitus** [comment]
Adding @gurkanindibay and @hanefi to this issue then, as they work on the packaging side of things. They should be able to better help you with installing pg_auto_failover from the binary packages. Thanks.

**Comment by linto2528** [comment]
Ok Thanks,

**Comment by linto2528** [comment]
Hi,
any update on this...

**Comment by DimCitus** [comment]
Hi @linto2528 ; thanks for the nice ping. So if your goal is to install from packages, you do not have to compile anything, and you do not have to use `git clone`.  When `pg_autoctl version` works, you have the tool you need.

Then there is a subtlety with out packaging, as we package the monitor extension separately from the command line. So your `apt-get install postgresql-12-auto-failover-1.4` does the right thing for the monitor. On the other nodes, you can only install the CLI only with `apt-get install pg-auto-failover-cli-1.6` for the new version 1.6.1 that we just released today.

**Comment by linto2528** [comment]
Hi @DimCitus ; thanks for the info, its working now.
