### ISSUE TITLE
Debian Buster support

### ISSUE THREAD

**Issue by HOSTED-POWER** [citusdata/pg_auto_failover#78]
Detected operating system as debian/buster.
Unfortunately, your operating system distribution and version are not supported by this script.

Since it's out for a few months now, it would be great if packages were built :)

**Comment by mtuncer** [comment]
Hey @HOSTED-POWER 
Thanks for raising the issue. We are aware of the situation, and will support buster in the next release.

**Comment by DimCitus** [comment]
Support for Debian buster is there now, with the release of 1.0.6. See https://packagecloud.io/citusdata/community/packages/debian/buster/postgresql-12-auto-failover-1.0_1.0.6_amd64.deb.
