### ISSUE TITLE
Reported repstate - unknown

### ISSUE THREAD

**Issue by nenominal** [citusdata/pg_auto_failover#788]
I have three nodes and a monitor with the following configuration

**pg_autoctl show state**

```
  Name |  Node |               Host:Port |           TLI: LSN |   Connection |       Current State |      Assigned State
-------+-------+-------------------------+--------------------+--------------+---------------------+--------------------
node_1 |     1 |   tesla.xxx.lan:5432 |   1: 17C2/F27D63F8 |   read-write |             primary |             primary
node_2 |     2 |  edison.xxx.lan:5432 |   1: 17C2/F27D63F8 |    read-only |           secondary |           secondary
 volta |    20 | volta.xxx.lan:5432 |   1: 17C2/F27D85F8 |  read-only ! |           secondary |           secondary
```

**pg_autoctl show settings**

```
  Context |    Name |                   Setting | Value
----------+---------+---------------------------+------
formation | default |      number_sync_standbys | 0    
  primary |  node_1 | synchronous_standby_names | ''   
     node |  node_1 |        candidate priority | 50   
     node |  node_2 |        candidate priority | 50   
     node |   volta |        candidate priority | 0    
     node |  node_1 |        replication quorum | false
     node |  node_2 |        replication quorum | false
     node |   volta |        replication quorum | false
```

I took a look in the monitor's database and I saw this

![Screenshot-20210828154139-2921x202](https://user-images.githubusercontent.com/21262237/131218445-81fb63e6-08fe-4db7-9a5f-db4b4ea1be53.png)

Why there is an unknown reportedrepstate? Is the state unknown because those servers are secondaries nodes?

Thanks.

**Comment by DimCitus** [comment]
The `reportedrepstate` column is filled-in from the [pg_stat_replication](https://www.postgresql.org/docs/14/monitoring-stats.html#PG-STAT-REPLICATION-VIEW) with its `sync_state` column. When we don't have an entry in the view, we get an empty string, and we translate the empty string to "unknown" in the monitor. The `pg_stat_replication` view misses an entry for a node when it's not currently connected via the streaming replication.

I'm closing this issue for triage, feel free to re-open if you have more questions!
