### ISSUE TITLE
pg_hba.conf issue adding a worker or coordinator by IP address 

### ISSUE THREAD

**Issue by colton-citus** [citusdata/pg_auto_failover#79]
Problem occurs when you create a worker or coordinator with a nodename of an IP address like this:

`pg_autoctl create worker --nodename 10.0.0.20`

pg_hba.conf entries don't have the /32 suffix added to indicate that they're single-IP CIDR blocks, and the pg_hba.conf is not valid.

**Comment by DimCitus** [comment]
I tried to reproduce and got the `/32` properly added. Will need more information to be able to reproduce and debug:

```
host "postgres" "dim" 192.168.1.39/32 trust # Auto-generated by pg_auto_failover
host all "pgautofailover_monitor" localhost trust # Auto-generated by pg_auto_failover
```

**Comment by DimCitus** [comment]
Closing this issue for clean-up purposes. Please re-open with more information if we still have something to fix here.
