### ISSUE TITLE
Enabling checksums with pg_autoctl

### ISSUE THREAD

**Issue by Eulerizeit** [citusdata/pg_auto_failover#829]
I was looking through the docs and I can't find a way to enable checksums using the `pg_autoctl create postgres` command. Am I missing this or is there another command / workflow we should be following?

**Comment by DimCitus** [comment]
Hi @Eulerizeit ; thanks for your interest in pg_auto_failover. We don't support every possible option that `initdb` offers. What we support instead is that you would `initdb` your cluster at your choice of PGDATA location on-disk, and then run `pg_autoctl create postgres` on-top of the already existing PGDATA. The command then simply adopts the Postgres cluster and registers it to the monitor, and then manages it.

See https://pg-auto-failover.readthedocs.io/en/master/ref/pg_autoctl_create_postgres.html#description for more details about the different modes of operations of the command.
