### ISSUE TITLE
point in time backups

### ISSUE THREAD

**Issue by lagleki** [citusdata/pg_auto_failover#83]
It'd be nice to have recommendations on how to do backups:

1. is it okay to edit pg_hba.conf of the primary node?
2. what's the best way to change wal replication for backups when the primary node changes?

**Comment by DimCitus** [comment]
Hi @lagleki. 

  1. it is okay to edit the HBA yourself, and required in many cases. pg_auto_failover makes no attempt to own the file.
  2. the best way to handle that depends on the backup tooling you're using, usually that would be either [pgbackrest](https://pgbackrest.org) or [pgbarman](https://www.pgbarman.org)

We have it on our roadmap to include more help in pg_auto_failover with respect to Disaster Recovery and backup management. That might land in the project early next year. As always, contributions are welcome!

**Comment by DimCitus** [comment]
Closing now, feel free to open again with more specific questions if you feel the answers need refinements / improvements!

**Comment by porsager** [comment]
Hi @DimCitus .. Very curious if you've made any inroads with regards to disaster recovery. Is there anything in the cards?

p.s. just used pgcopydb to move our production db yesterday (the simple way without `--follow` though) - worked beautifully! Thanks!
