### ISSUE TITLE
Does it have connection pool?

### ISSUE THREAD

**Issue by seaurching** [citusdata/pg_auto_failover#831]
#### Here is an help for pg_auto_failover.
I want to known that even if has connection pool like pgpool-II.

**Comment by DimCitus** [comment]
Hi @seaurching ; thanks for your interest in pg_auto_failover. Have you read the docs, and specifically the Client-Side HA part of it at https://pg-auto-failover.readthedocs.io/en/master/architecture.html#client-side-ha ; and then, do you have a specific question?

If you have specific questions in mind, then please consider re-opening this issue with more details.
