### ISSUE TITLE
monitor does not restart when running with pg_autoctl run

### ISSUE THREAD

**Issue by thanodnl** [citusdata/pg_auto_failover#86]
If the postgres of the monitor gets killed or crashes it is not correctly restarted by the 'keeper'.
This can be reproduced in 2 sessions:

Session 1
```bash
pg_autoctl run --pgdata /path/of/monitor
```

Session 2
```bash
kill <pid of monitor postgres>
```
(or a killall postgres for that matter)

`pg_autoctl` will be in an error loop but not restarting the postgres process. This is different behaviour than we have when running a postgres node.

**Comment by Bouke** [comment]
The loop prints the following:
```
14:51:25 WARN  Lost connection.
14:51:25 WARN  Re-establishing connection. We might miss notifications.
14:51:25 ERROR Connection to database failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
