### ISSUE TITLE
Monitor node high availability

### ISSUE THREAD

**Issue by qiuwenhuifx** [citusdata/pg_auto_failover#877]
The current monitor node is a single node，if monitor node went down ,the cluster  is in a non-highly available state，
Will zk or etcd be used to monitor the status of the cluster in the future?

**Comment by DimCitus** [comment]
If the monitor node is down, the only impact is that no failover is possible. But if the monitor node is the only node down, no failover is needed. See also https://github.com/citusdata/pg_auto_failover/issues/867. Closing for duplicate.
