### ISSUE TITLE
Pg_autofailover installation

### ISSUE THREAD

**Issue by ambrosea91** [citusdata/pg_auto_failover#881]
Hello how, 

l am unable to run curl https://install.citusdata.com/community/rpm.sh | sudo bash because my server doesn’t have access to the internet. Is there a code l can download and do the installation manually?

Regards,
Ambrose.

**Comment by DimCitus** [comment]
Consider using [apt.postgresql.org](https://wiki.postgresql.org/wiki/Apt), which might make it easier for you to download packages and prepare your server when it's offline.
