### ISSUE TITLE
packages for postgresql 12 ?

### ISSUE THREAD

**Issue by changchichung** [citusdata/pg_auto_failover#90]
I am trying to upgrade postgresql to postgresql-12 , but from the citusdata apt repository , there is only postgresql-11-auto-failover-1.0 , and with the package , postgresql-11 will be installed.
so there are two versions of postggresql in one node 
```
2019-10-23 07:01:07 [administrator@pg_primary ~]$ sudo apt list --installed|grep postgresql

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

postgresql-11/bionic-pgdg,now 11.5-3.pgdg18.04+1 amd64 [installed,automatic]
postgresql-11-auto-failover-1.0/bionic,now 1.0.5 amd64 [installed]
postgresql-12/bionic-pgdg,now 12.0-2.pgdg18.04+1 amd64 [installed]
postgresql-client-11/bionic-pgdg,now 11.5-3.pgdg18.04+1 amd64 [installed,automatic]
postgresql-client-12/bionic-pgdg,now 12.0-2.pgdg18.04+1 amd64 [installed]
postgresql-client-common/bionic-pgdg,now 207.pgdg18.04+1 all [installed,automatic]
postgresql-common/bionic-pgdg,now 207.pgdg18.04+1 all [installed,automatic]
```
even I run the postgresql only in version 12.
```
2019-10-23 07:08:59 [administrator@pg_primary ~]$ sudo runuser -l postgres -c "psql postgres://pg_secondary:5432,pg_primary:5432/testdb1?target_session_attrs=read-write -c 'show server_version;'"
          server_version          
----------------------------------
 12.0 (Ubuntu 12.0-2.pgdg18.04+1)
(1 row)

```

hope the offical packages will been released soon

**Comment by DimCitus** [comment]
We are still working on all the Postgres 12 packages for the list of currently supported distributions, and should be able to update this issue soon with packages uploaded.

**Comment by changchichung** [comment]
glad to hear that , thanks.

**Comment by Bouke** [comment]
For CentOS, the Postgres yum repo includes packages for the current release (1.0.5): https://yum.postgresql.org/repopackages.php#pg12 (e.g. https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-8-x86_64/)

**Comment by DimCitus** [comment]
We have uploaded packages for pg_auto_failover 1.0.6 including debian buster support and PostgreSQL 12 support. You can now use them, finally!
