### ISSUE TITLE
Please honor $XDG_STATE_HOME

### ISSUE THREAD

**Issue by Tiago-DBA** [citusdata/pg_auto_failover#935]
Salut Dimitri,
on issue: https://github.com/citusdata/pg_auto_failover/issues/908 you state that :

**In pg_autoctl we use the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to determine where to store and read our files. See for instance the following source:**

Indeed it works fine for $XDG_RUNTIME_DIR (and recently TMPDIR)
also $XDG_CONFIG_HOME works fine for configuration file.

But $XDG_STATE_HOME is not honored, everything is written to ~/.local

Could you please fix it ?

Thank you
Tiago

**Comment by DimCitus** [comment]
Try XDG_DATA_HOME.

See https://github.com/citusdata/pg_auto_failover/blob/e5bc71cf84dd7db779238e28ea5478d50ab900c4/src/bin/pg_autoctl/config.c#L54 and around in this file.
