### ISSUE TITLE
Question about monitor with different PostgreSQL major versions 

### ISSUE THREAD

**Issue by Tiago-DBA** [citusdata/pg_auto_failover#963]
SAlut,

I know there are yet some tickets about this topic. But mine may be different.

Basically I have several clusters in PostgreSQL 13, monitor node is also PostgreSQL 13 and it is mutualized, 
I would like to know if it is possible to add some new clusters in postgreSQL 14  using current monitor node (so a PostgreSQL 13) ( off course everything will be up to date in keeper nodes binaries (pg_autoctl 14,  pg_ctl 14, ...)  and so on) ?

Thank you.

**Comment by DimCitus** [comment]
Yes that should just work, as long as the extension version on the monitor is compatible with all the nodes it is meant to manage (first two digits should be the same, 1.6, or 1.7, or current 2.0).

**Comment by Tiago-DBA** [comment]
Ok, so no dependency on PostgreSQL but, in case of major pg_autoctl upgrade, RPM should be upgraded in all nodes. Moreover I take a look as the new monitor upgrade feature. From 1.4.0 release onwards, It's seems that only rpm replacement (in *all* nodes) then restart of monitor service, should work without any disturb of service in keeper nodes (so no restart of pg_autoctl service nor PostgreSQL), right ?
