### ISSUE TITLE
pg_autoctl version does not mention Postgres 15 compatibility

### ISSUE THREAD

**Issue by epolkerman** [citusdata/pg_auto_failover#968]
Installed pg_auto_failover version 2.0
Running pg_autoctl version gives following output:

> pg_autoctl version
pg_autoctl version 2.0
pg_autoctl extension version 2.0
compiled with PostgreSQL 15.1 on powerpc64le-unknown-linux-gnu, compiled by gcc (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2], 64-bit
compatible with Postgres 10, 11, 12, 13, and 14

The last line doesn't mention PostgreSQL version 15 although that is supported with pg_auto_failover 2.0

**Comment by DimCitus** [comment]
Hi @epolkerman ; thanks for reporting the issue. It's been fixed in https://github.com/citusdata/pg_auto_failover/pull/951 ; yet to be released. Somehow I forgot about that when cooking the release.
