### ISSUE TITLE
Primary Server not Push pg_wal to Standby Server

### ISSUE THREAD

**Issue by vkk74in** [citusdata/pg_auto_failover#975]
1. We configured the Streaming Replication on Azure VMs. Primary VM on East Region, Standby on West Region 
2. Postgresql 12 Version we are using. 
3. used repmgr to configure the Replication. 
4. Today we ran load test and identifed pg_wal directory consumed 100%. on Primary Server. and no change pg_wal directory. 
5. We have archive in place. But Replication lag is 70GB. Databasse size is 4 GB only and no change on data from last one week.

**Comment by vkk74in** [comment]
How to mitigate the Lag 
-[ RECORD 1 ]---------------
redo_lsn    | 3C85/C80000D8
slot_name   | node_a_repslot
restart_lsn | 3C75/69CC0000
gb_behind   | 65.47

**Comment by DimCitus** [comment]
Hi @vkk74in ; you mention using repmgr in your issue, so I don't suppose you have a problem with pg_auto_failover? In any case, if might get better results with hiring Postgres consultants to help you diagnose and fix your immediate problem and maybe architecture, depending on details not shared.
