### ISSUE TITLE
Unable to get --pgdata value in pg_autoctl get config command

### ISSUE THREAD

**Issue by mtuncer** [citusdata/pg_auto_failover#99]
I hit this while implementing `pg_autoctl set node candidate-priority xxx` command. When investigated found existing `pg_autoctl config get ...` command also exhibits the same behavior.

I have a monitor and a primary node set up in the same machine.

When I run the command  `pg_autoctl config get timeout.network_partition_timeout --pgdata /Users/mtuncer/dev/ha/test/primary/`
 I got

```
11:01:32 INFO  Managing PostgreSQL installation at "/Users/mtuncer/dev/ha/test/primary/"
pg_autoctl config get: Get the value of a given pg_autoctl configuration variable
usage: pg_autoctl config get [ section.option ]

  --pgdata      path to data directory
```

if I set `PGDATA= /Users/mtuncer/dev/ha/test/primary/ ` and run  the same command without --pgdata I got successful. 
```
11:05:08 INFO  Managing PostgreSQL installation at "/Users/mtuncer/dev/ha/test/primary"
20
```

However, if I run the earlier command while PGDATA is set I still get the same error

```
pg_autoctl config get timeout.network_partition_timeout --pgdata /Users/mtuncer/dev/ha/test/primary/
11:06:13 INFO  Managing PostgreSQL installation at "/Users/mtuncer/dev/ha/test/primary"
pg_autoctl config get: Get the value of a given pg_autoctl configuration variable
usage: pg_autoctl config get [ section.option ]

  --pgdata      path to data directory
```

This is happening on Mac OS 10.14 with Apple Clang 11.0.0

**Comment by mtuncer** [comment]
It turned out that the way I am using config get command was not right. I should have been using

```
pg_autoctl config get  --pgdata /Users/mtuncer/dev/ha/test/primary/ timeout.network_partition_timeout
```

That is --pgdata before the configuration name

**Comment by DimCitus** [comment]
We could improve the documentation of the commands to remind that options come before arguments, or maybe improve the command line parsing. In the documentation at https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html#Argument-Syntax I just found the following:

> The implementations of getopt and argp_parse in the GNU C Library normally make it appear as if all the option arguments were specified before all the non-option arguments for the purposes of parsing, even if the user of your program intermixed option and non-option arguments. They do this by reordering the elements of the argv array. This behavior is nonstandard; if you want to suppress it, define the _POSIX_OPTION_ORDER environment variable. See Standard Environment.

I'm not sure how to take advantage of it though.

**Comment by DimCitus** [comment]
Also note that we have the following in `main.c`, which has an impact on our option parsing. It might be that we can unset this environment variable just before parsing the options on the last subcommands level and get things to be more flexible wrt to positioning of options and arguments...

``` c
	/*
	 * We need to follow POSIX specifications for argument parsing, in
	 * particular we want getopt() to stop as soon as it reaches a non option
	 * in the command line.
	 *
	 * GNU and modern getopt() implementation will reorder the command
	 * arguments, making a mess of our nice subcommands facility.
	 */
	setenv("POSIXLY_CORRECT", "1", 1);
```
